### ISSUE TITLE
how to disable valet autostart on ubuntu 16.04 ?

### ISSUE THREAD

**Issue by ibnumusyaffa** [cpriego/valet-linux#101]

**Comment by TheNodi** [comment]
To disable valet you have to disable nginx and php-fpm. 

You can do that using:
```
systemctl disable nginx
systemctl disable php7.0-fpm
```

Note: php-fpm service name may change based on installed PHP version.

**Comment by antimech** [comment]
I've met a problem:
```bash
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable nginx
update-rc.d: error: Permission denied
```

**Comment by antimech** [comment]
I've tried to uninstall Valet but I've lost internet connection that way, so I installed it back.

**Comment by antimech** [comment]
Nevermind, I added `$ sudo` before the command.
