### ISSUE TITLE
Pinging blog.dev pings to 127.0.53.53

### ISSUE THREAD

**Issue by besrabasant** [cpriego/valet-linux#102]
After installing Valet, I added a Test site under `~/Sites/blog` directory. as mentioned by the docs, pinging `blog.dev` should give me `127.0.0.1` but it gives me `127.0.53.53` instead

**Comment by cpriego** [comment]
The new default TLD was changed from **.dev** to **.test**

**Comment by cpriego** [comment]
I have updated Valet Linux website to reflect the change
