### ISSUE TITLE
After updating, valet stop working

### ISSUE THREAD

**Issue by santigarcor** [cpriego/valet-linux#103]
After updating to the most recent version, valet stop working, if i try to access through the .test domain it redirects me to google search. If i ping the .test domain i get response from the 127.0.0.1, but in chrome it doesn't work.

**Comment by TheNodi** [comment]
DNS looks fine. 

Check the actual response with curl:
```
curl http://example.test -v
```

**Comment by cpriego** [comment]
Try with the full address http://<your-site>.test
This is one of those times I don't like the omnibar assuming I am making a search.

**Comment by santigarcor** [comment]
@cpriego it worked, now the thing is, do you know how can i make that bar to asume that i'm not making a search like when typing the .dev domain?

**Comment by TheNodi** [comment]
Unfortunatly this is a `wontfix` for the chrome team, see https://bugs.chromium.org/p/chromium/issues/detail?id=30636

For the records, the other option is to type the trailing `/`, like `example.test/` instead of `example.test`. It's quicker than the protocol, still annoying, but after the domain is visited it should give you it instead of search.

**Comment by cpriego** [comment]
@TheNodi is right, Google will not fix this. There is are a couple of workarounds. The first is the one previously mentioned, the seconds involves a custom search engine: https://stackoverflow.com/questions/7877705/chrome-browser-doesnt-like-a-domain-with-loc-tld-for-localhost-domain-testing

By the way, the use of the **.dev** TLD is no longer recommended for Chrome will redirect that TLD to https in the next release (thanks again Google)

**Comment by santigarcor** [comment]
Too bad for people using Chrome.

Thank you anyway!
