### ISSUE TITLE
After restart internet seems not working!

### ISSUE THREAD

**Issue by susonwaiba** [cpriego/valet-linux#108]
I am using Ubuntu 16.04 LTS and latest composer with latest valet-linux ps. everything updated to latest version. But it seems when I install valet and restart my pc, after reboot internet doesn't seem to work may be due to DNS problem or something like that until I uninstall valet to gain access. Does anyone knows how to resolve it.
During uninstall following message appear:-

- Stopping nginx...
- Stopping php7.0-fpm...
- Restarting network-manager...
- Restarting dnsmasq...
- Valet DNS changes have been rolled back
- If your system depended on systemd-resolved (like Ubuntu 17.04), please enable it manually
- Valet has been uninstalled.

**Comment by susonwaiba** [comment]
It seems I can visit or ping IP address !! But cant domain names.

**Comment by TheNodi** [comment]
Can you give us the output of the following commands?
```
dig example.test
dig google.com
```

**Comment by susonwaiba** [comment]
dig example.test
![one](https://user-images.githubusercontent.com/20234104/31047057-8455db38-a623-11e7-9470-bef001bc4854.png)

dig google.com
![two](https://user-images.githubusercontent.com/20234104/31047066-91fe4266-a623-11e7-8279-9b05edb9a426.png)

**Comment by TheNodi** [comment]
Can you also paste the following: 
```
cat /opt/valet-linux/dns-servers
cat /opt/valet-linux/watch.log
cat /etc/resolv.conf
```

@cpriego , I haven't yet looked at your latest updates to dns. You might be needed here.

**Comment by susonwaiba** [comment]
adding below line to *tail* file solved the problem.
/etc/resolvconf/resolv.conf.d/tail
`
nameserver 8.8.8.8
`
I don't know this is the best solution but kind of working.  totally found on another forum.

**Comment by susonwaiba** [comment]
```
cat /opt/valet-linux/dns-servers
cat /opt/valet-linux/watch.log
cat /etc/resolv.conf
```
![three](https://user-images.githubusercontent.com/20234104/31047332-33ea56c4-a628-11e7-8f57-21b802ea3166.png)

**Comment by cpriego** [comment]
OK, you do have your nameservers (192.168.1.1 and 8.8.8.8) where they should, name resolutions should work as intended. One last thing. What's the status of `systemctl status dnsmasq` ?

**Comment by susonwaiba** [comment]
@cpriego 
Actually, now it is working after changing the `tail` file as above mentioned. though the output is below:-

`dig @192.168.1.1 vimeo.com`
![one](https://user-images.githubusercontent.com/20234104/31051808-ff02cdfa-a691-11e7-92ae-97341a6d66c6.png)

`dig @127.0.0.1 vimeo.com`
![two](https://user-images.githubusercontent.com/20234104/31051813-1adea4a4-a692-11e7-811e-5e8484371ff2.png)

`systemctl status dnsmasq`
![three](https://user-images.githubusercontent.com/20234104/31051814-27838d3c-a692-11e7-8ae2-ff317fd2ae12.png)
