### ISSUE TITLE
Valet Share: Command not found

### ISSUE THREAD

**Issue by JapSeyz** [cpriego/valet-linux#110]
When attempting to run `valet share` in a project root or in the parked directory in general, an error pops up  saying that the command is not found:
`/usr/local/bin/valet: line 83: jq: command not found`.

The line refers to the `valet port` command, and albeit the port has been set to port 80, it still gives me the same error.

**Comment by JapSeyz** [comment]
I am sorry, the /usr/local/bin/valet script is different from the valet script in the root of this repo, the line it acutally points to is: `PORT=$(cat "$HOME/.valet/config.json" | jq -r ".port")`

Where `jq` seems to be the issue at hand. I am using ElementaryOS Loki.
I can download `jq` manually, and hopefully this will fix the issue.

**Comment by TheNodi** [comment]
The port changes aren't released yet.

`jq` is a requirement, see https://cpriego.github.io/valet-linux/requirements#ubuntu

You can install it using `apt-get`:
```
sudo apt-get install jq
```

**Comment by JapSeyz** [comment]
Ah, I am sorry, I completely missed that section.
