### ISSUE TITLE
Magento 2 error

### ISSUE THREAD

**Issue by roasted-toast** [cpriego/valet-linux#111]
I work on a Magento 2 gateway for Laravel on homestead and I wanted to import my work to my valet sites folder but when I try to access the Magento page through the .test domain I get an error:

`DOCUMENT_ROOT variable is unavailable`

Any idea on what's going wrong? Where do i edit the Nginx configuration to fix this?

**Comment by TheNodi** [comment]
I've never worked with Magento 2 before. 

Magento seems to need `$_SERVER['DOCUMENT_ROOT']` to work, can you dump your `$_SERVER` to see if it's available?

We might have to set it manually inside `server.php`.

I would have expected someone else to notice before now, since Magento 2 Driver has been available for quite some time.

**Comment by roasted-toast** [comment]
Here is a complete `var_dump` of the `$_SERVER` variable:

`
array(33) { ["USER"]=> string(5) "david" ["HOME"]=> string(11) "/home/david" ["HTTP_ACCEPT_LANGUAGE"]=> string(11) "fr,en;q=0.8" ["HTTP_ACCEPT_ENCODING"]=> string(13) "gzip, deflate" ["HTTP_DNT"]=> string(1) "1" ["HTTP_ACCEPT"]=> string(85) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" ["HTTP_USER_AGENT"]=> string(135) "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.100 Chrome/61.0.3163.100 Safari/537.36" ["HTTP_UPGRADE_INSECURE_REQUESTS"]=> string(1) "1" ["HTTP_CONNECTION"]=> string(10) "keep-alive" ["HTTP_HOST"]=> string(12) "phptest.test" ["REDIRECT_STATUS"]=> string(3) "200" ["SERVER_NAME"]=> string(0) "" ["SERVER_PORT"]=> string(2) "80" ["SERVER_ADDR"]=> string(9) "127.0.0.1" ["REMOTE_PORT"]=> string(5) "55674" ["REMOTE_ADDR"]=> string(9) "127.0.0.1" ["SERVER_SOFTWARE"]=> string(12) "nginx/1.12.1" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["REQUEST_SCHEME"]=> string(4) "http" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["DOCUMENT_ROOT"]=> string(25) "/home/david/Sites/phptest" ["DOCUMENT_URI"]=> string(66) "/home/david/.config/composer/vendor/cpriego/valet-linux/server.php" ["REQUEST_URI"]=> string(1) "/" ["SCRIPT_NAME"]=> string(10) "/index.php" ["SCRIPT_FILENAME"]=> string(35) "/home/david/Sites/phptest/index.php" ["CONTENT_LENGTH"]=> string(0) "" ["CONTENT_TYPE"]=> string(0) "" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["FCGI_ROLE"]=> string(9) "RESPONDER" ["PHP_SELF"]=> string(66) "/home/david/.config/composer/vendor/cpriego/valet-linux/server.php" ["REQUEST_TIME_FLOAT"]=> float(1508227440.3992) ["REQUEST_TIME"]=> int(1508227440) }
`
And here is the full Magento 2 report:

`
{"0":"DOCUMENT_ROOT variable is unavailable.","1":"#0 \/home\/david\/Sites\/magento2\/lib\/internal\/Magento\/Framework\/App\/Http.php(234): Magento\\Framework\\App\\SetupInfo->__construct(Array)\n#1 \/home\/david\/Sites\/magento2\/lib\/internal\/Magento\/Framework\/App\/Http.php(265): Magento\\Framework\\App\\Http->redirectToSetup(Object(Magento\\Framework\\App\\Bootstrap), Object(Exception))\n#2 \/home\/david\/Sites\/magento2\/lib\/internal\/Magento\/Framework\/App\/Http.php(157): Magento\\Framework\\App\\Http->handleBootstrapErrors(Object(Magento\\Framework\\App\\Bootstrap), Object(InvalidArgumentException))\n#3 \/home\/david\/Sites\/magento2\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(261): Magento\\Framework\\App\\Http->catchException(Object(Magento\\Framework\\App\\Bootstrap), Object(InvalidArgumentException))\n#4 \/home\/david\/Sites\/magento2\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#5 \/home\/david\/.config\/composer\/vendor\/cpriego\/valet-linux\/server.php(203): require('\/home\/david\/Sit...')\n#6 {main}","url":"\/\/home\/david\/Sites\/magento2\/pub\/errors\/default\/css\/styles.css","script_name":"\/home\/david\/.config\/composer\/vendor\/cpriego\/valet-linux\/server.php"}
`

Everything works on homestead but I remember using a specific Nginx configuration file to make it work:
https://gist.github.com/Lewiscowles1986/f68dbf82b532838a76ed

Do you see anything that is missing from valet and that should be added?

**Comment by TheNodi** [comment]
`$_SERVER["DOCUMENT_ROOT"]` looks to be set correctly.

All the logic inside your nginx config should be part of the `Magento2ValetDriver`.

The error comes from here: https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/App/SetupInfo.php#L59
Can you dump `$this->server` before the conditional?

I think that should be a "copy" of `$_SERVER`, but somehow a property is missing.

**Comment by roasted-toast** [comment]
Sure, here is the dump and yeah the `DOCUMENT_ROOT` value seems to be empty:

`array(34) { ["USER"]=> string(5) "david" ["HOME"]=> string(11) "/home/david" ["HTTP_ACCEPT_LANGUAGE"]=> string(11) "fr,en;q=0.8" ["HTTP_ACCEPT_ENCODING"]=> string(13) "gzip, deflate" ["HTTP_DNT"]=> string(1) "1" ["HTTP_ACCEPT"]=> string(85) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" ["HTTP_USER_AGENT"]=> string(135) "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.100 Chrome/61.0.3163.100 Safari/537.36" ["HTTP_UPGRADE_INSECURE_REQUESTS"]=> string(1) "1" ["HTTP_CONNECTION"]=> string(10) "keep-alive" ["HTTP_HOST"]=> string(13) "magento2.test" ["REDIRECT_STATUS"]=> string(3) "200" ["SERVER_NAME"]=> string(0) "" ["SERVER_PORT"]=> string(2) "80" ["SERVER_ADDR"]=> string(9) "127.0.0.1" ["REMOTE_PORT"]=> string(5) "36652" ["REMOTE_ADDR"]=> string(9) "127.0.0.1" ["SERVER_SOFTWARE"]=> string(12) "nginx/1.12.1" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["REQUEST_SCHEME"]=> string(4) "http" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["DOCUMENT_ROOT"]=> string(0) "" ["DOCUMENT_URI"]=> string(66) "/home/david/.config/composer/vendor/cpriego/valet-linux/server.php" ["REQUEST_URI"]=> string(1) "/" ["SCRIPT_NAME"]=> string(66) "/home/david/.config/composer/vendor/cpriego/valet-linux/server.php" ["SCRIPT_FILENAME"]=> string(66) "/home/david/.config/composer/vendor/cpriego/valet-linux/server.php" ["CONTENT_LENGTH"]=> string(0) "" ["CONTENT_TYPE"]=> string(0) "" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["FCGI_ROLE"]=> string(9) "RESPONDER" ["PHP_SELF"]=> string(66) "/home/david/.config/composer/vendor/cpriego/valet-linux/server.php" ["REQUEST_TIME_FLOAT"]=> float(1508342128.8327) ["REQUEST_TIME"]=> int(1508342128) ["MAGE_DIRS"]=> array(4) { ["pub"]=> array(1) { ["uri"]=> string(0) "" } ["media"]=> array(1) { ["uri"]=> string(5) "media" } ["static"]=> array(1) { ["uri"]=> string(6) "static" } ["upload"]=> array(1) { ["uri"]=> string(12) "media/upload" } } }
`

**Comment by roasted-toast** [comment]
I've managed to make it work. Using the CLI installer solves the problem:
![david ubuntu -sites-magento2_012](https://user-images.githubusercontent.com/10560326/31729698-0be88bee-b430-11e7-9127-9179d8ebe102.png)

I still have some 404 errors to fix but that should be such a big deal:
![selection_013](https://user-images.githubusercontent.com/10560326/31729778-4bee613c-b430-11e7-94f1-0cf446f495ec.png)
