### ISSUE TITLE
where to put projects

### ISSUE THREAD

**Issue by anuj9196** [cpriego/valet-linux#114]
I currently intalled valet-linux

I have changed `html` directory from `/var/www/html` to `/home/user/www/html`
and have created project using composer in it which created a project folder as `myproject`.

When I visit, `myproject.test` it gives 404 error.

How to register `home/user/www/html` to access all projects like `dir.test`?

**Comment by Ljz7** [comment]
Hello, use the `link` command : https://cpriego.github.io/valet-linux/#the-link-command

**Comment by Ljz7** [comment]
Hello, use the `park` command ---> https://cpriego.github.io/valet-linux/#the-park-command

**Comment by cpriego** [comment]
You can put the projects wherever you desire.

Just `cd` into the projects parent folder and run `valet park`

If you have the following structure
```
home
└── username
    └── www
        └── html
            ├── project1
            ├── project2
            └── project3
```

Just run
```
cd /home/username/www/html
valet park
```
and after that you should be able to access all the projects within your browser at the `project1.test`, `project2.test` or `project3.test` URL
