### ISSUE TITLE
can not access localhost/phpmyadmin

### ISSUE THREAD

**Issue by anuj9196** [cpriego/valet-linux#117]
I have setup `DocumentRoot` to `/home/user/www/html` instead of `/var/www/html`.

I have parked `/home/user/www/html` to valet which is working perfectly.

But now, I cannot access `localhost`. I have to access my `phpmyadmin` installation which was earlier accessed using
```
localhost/phpmyadmin
```
It throws 404 error of valet.

**How to whitelist localhost domains?**

**Comment by Ljz7** [comment]
Hello, 

did you tried access it through `127.0.0.1/phpmyadmin` directly ?

**Comment by Ljz7** [comment]
Why don't you `valet link` the phpmyadmin application ? 

You'll be able to access it simply using

```
phpmyadmin.test
```
