### ISSUE TITLE
Returns 404 when trying to serve a site with an underscore - 'my_site'

### ISSUE THREAD

**Issue by beefjeff** [cpriego/valet-linux#118]
Using a fresh laravel 5.5 install.

**Comment by Ljz7** [comment]
It's not a valet issue. Underscore are not allowed in host name : 

>The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the minus sign ('-')

source : https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
