### ISSUE TITLE
valet share can't do properly

### ISSUE THREAD

**Issue by lembupeteng** [cpriego/valet-linux#120]
![image](https://user-images.githubusercontent.com/6700004/32821651-1916a3ea-ca07-11e7-89f0-1cbdca0ccaf1.png)
can't show my project.always got 404 not found. help me pls.

**Comment by TheNodi** [comment]
Sorry for the late response.

Does the project works correctly visiting laravelCRUD.dev? 
Can you share other projects?

**Comment by JapSeyz** [comment]
@TheNodi I am having the same issue.

The projects works fine when I access <url>.test, but as soon as I try the valet share command, the ngrok connection sends all requests to a 404
![screenshot from 2018-01-03 23 55 47](https://user-images.githubusercontent.com/2234034/34543533-a58444d0-f0e1-11e7-9da2-40c7a4781bb2.png)
