### ISSUE TITLE
504 Gateway Time-out on all projects

### ISSUE THREAD

**Issue by anuj9196** [cpriego/valet-linux#122]
I have installed `valet-linux` on my ubuntu machine

Due to some time taking script in one of my parked project resulted in `504 Gateway Time-out`. Now no parked projects are working and all are giving same error.

I tried increasing `max_execution_time` from `30` to `600` in `/etc/php/7.0/apache2/php.ini` and restart nginx using
```
sudo service nginx restart
```
and
```
sudo service nginx stop
sudo service nginx start
```
But error is still there. Since this is development machine and there might come such errors frequently. 
**How can I reset the error or the server to start developing again.**

**Comment by TheNodi** [comment]
I'm not sure `/etc/php/7.0/apache2/php.ini ` is the correct php.ini file. Isn't there a `/etc/php/7.0/fpm/` folder in Ubuntu?

You can check the execution timeout using:
```php
ini_get('max_execution_time'); 
```

**Comment by eugenevdm** [comment]
I'm also struggling with the same issue. I found a post on Stack that says look in `~/.valet/Nginx/yoursite.conf` but I don't have that file. Says [post is here](https://serverfault.com/questions/927553/504-timeout-no-matter-how-much-i-increase-timeout-parameters).

**Comment by clarknelson** [comment]
@eugenevdm that file should be on your local machine I believe

**Comment by clarknelson** [comment]
Actually that directory was moved to `~/.config/valet` in a later update
