### ISSUE TITLE
Other php in same folder still shows index.php

### ISSUE THREAD

**Issue by jericopulvera** [cpriego/valet-linux#130]
I have this public directory and the index.php is in there.

../project-name
    ./public
        - index.php
        - api.php

when I access project-name.localhost/ it works
but when I make a post request to project-name.localhost/api.php
the return is still index.php

even if I access project-name.localhost/api.php using get request I still got the index.php

when I use a php server it is working as expected php -S localhost:8888 -t public

**Comment by TheNodi** [comment]
Can you check what driver valet is using with `valet which`?

**Comment by jericopulvera** [comment]
This site is served by [BasicValetDriver]

**Comment by TheNodi** [comment]
When you request for `http://domain.test/api.php` BasicValetDriver looks for the following file (in order of priority, top first):
```
/path/to/site/api.php
/path/to/site/api.php/index.php
/path/to/site/api.php/index.html
/path/to/site/index.php
/path/to/site/public/index.php
/path/to/site/public/index.html
```
while your file is in `/path/to/site/public/api.php`.

In this case, you want to link public's folder and not the root folder of your project. At that point valet's will behave as you want.

You need to do something like:
```bash
cd /path/to/site/public
valet link my-domain
```

**Comment by jericopulvera** [comment]
Thanks that worked.

**Comment by jericopulvera** [comment]
Great!
