### ISSUE TITLE
serving static files from /static/ doesn't work

### ISSUE THREAD

**Issue by superdav42** [cpriego/valet-linux#131]
If the uri starts with /static weird things happen. Like sending a 404 header then the content of the file. This affects magento 2 and probably other sites. Valet linux should cherry-pick this commit from valet
https://github.com/laravel/valet/commit/6727e43288a8b29ce0151de44ca192e1c8592051

On a related note I'm a little confused how this project is maintained, does it sync upstream changes at all or just what we feel like? or is the hope valet will become a cross-platform project?

**Comment by TheNodi** [comment]
You can try #132 and see if it works.

The objective of the project was to make Valet cross-platform and working well for most linux distributions. We wanted to keep it updated with Laravel Valet for Mac and keep it in sync.

Unfortunately we faced two really big walls:
- Supporting most Linux distributions is harder than it looked at the beginning, especially with the latest changes in Ubuntu 17.04 and similar. We have tried 3 different systems to manage DNS entries, and none of them worked well on all distributions.
- Time is a really big concern, we don't have the time to work on the project as it needs. 

These problems left the project in a "limbo" state, where it works on some distributions, with a few workarounds (see the different issues), but in most cases it requires more knowledge than we'd like to. It should be *easy* to install, messing with DNS settings and system configs is not considerable easy.
Trying to fix this, we lost a lot of upstream updates from Laravel Valet for Mac, and now we are at the point a lot of time needs to be invested to port all changes and stabilize the current updates.

In my general TODO list I have:
- Port all upstream changes into Valet Linux
- Refactor part of the code to make it more modular and extendable
- Go back into analyzing why some distributions are having weird issues (See Ubuntu 17.04)

Unfortunately as I said I'm really out of time to address all this issues, at least until my graduation (this summer hopefully). I'm really sorry for that, I would love to offer the community a better "product" than what we have right now.
