### ISSUE TITLE
valet secure (Your connection is not private)

### ISSUE THREAD

**Issue by jukerok** [cpriego/valet-linux#136]
"valet secure site-name" outputs the following: 
![valet-secure-output](https://user-images.githubusercontent.com/23478065/35403259-dad8444c-0207-11e8-8434-f4f1e3399d23.png)

however when trying to access the vm.test on the browser, I get a "Your connection is not private" 

when running the command "valet secure" I checked the following
* Certificates are being generated in ~/.valet/Certificates/
* an Nginx file gets generated in ~/.valet/Nginx/
* nginx-error.log is not showing anything related. 
(what else could be helpful to check?)

would really appreciate helping me debug, as I have been at it for 3 days now.

**Comment by TheNodi** [comment]
Chrome will give you "Your connection is not private" on a self-signed certificate.
Valet tries to insert the certificate into Chrome and Firefox's database, but it requires a browser restart (See [this](https://cpriego.github.io/valet-linux/faq#why-do-i-get-certificate-errors-after-securing-a-site)).

Does it still gives you the error after restarting your browser?

You can list all installed certificates inside Chrome database using the following command:
```
certutil -d sql:$HOME/.pki/nssdb -L
```

**Comment by jukerok** [comment]
Good point.
the result of the command is 
![certutil](https://user-images.githubusercontent.com/23478065/35405944-43e8a3ca-0210-11e8-967b-700a90d5f238.png)

Restarted the browser but still getting that error.

**Comment by TheNodi** [comment]
It looks installed.

Can you give me the specific error message from Chrome? It should be under the first text paragraph in the page.
For example, `NET::ERR_CERT_AUTHORITY_INVALID` should be the error connected with a self-signed certificate.

**Comment by jukerok** [comment]
it's the same one you mentioned, `NET::ERR_CERT_AUTHORITY_INVALID`

**Comment by TheNodi** [comment]
In Chrome:
- Open `Chrome Settings > Advanced settings > Privacy and Security > Manage Certificates`
- Find `vm.test` under `Your Certificates` tab
- Expand it
- Choose the 3 dots, and then `Edit`
- What are the checked boxes?
- Check all boxes
- Save and restart Chrome

**Comment by jukerok** [comment]
I think we are getting real close, under `Your certificates` tab I have nothing.

**Comment by jukerok** [comment]
![cv](https://user-images.githubusercontent.com/23478065/35409589-5a31d7cc-021b-11e8-8446-774106eb65e6.png)
here is a screenshot from the details tab as well

**Comment by TheNodi** [comment]
Can you try to import it manually from the UI? There should be an `Import` button on top of the list. Import `~/.valet/Certificates/vm.test.crt`

**Comment by jukerok** [comment]
I tried that from chrome, but it gives me the following error: 
![error](https://user-images.githubusercontent.com/23478065/35410470-39ece314-021e-11e8-8128-bd4e346ad23e.png)

and when I try doing that on firefox
![error2](https://user-images.githubusercontent.com/23478065/35410538-7072aebe-021e-11e8-8693-999e2573c653.png)

**Comment by TheNodi** [comment]
I think I misunderstood chrome UI tabs and you should try to import it from "Authorities" tab. 
"Your Certificates" is for authentications client certificates.

**Comment by jukerok** [comment]
Perfect that did it. Thank you, also after uninstalling and reinstalling valet-linux, certificates are being added by valet with no problem.  Again thank you for your awesomeness.

**Comment by jankulma** [comment]
I tried to do the same, but unfortunately got an error:

```
The file contained one certificate, which was not imported:
fun.app: Not a Certification Authority
```

**Comment by jukerok** [comment]
could you please specify the error that you get on the browser when trying to access https://fun.app ??
