### ISSUE TITLE
Resolv.conf resets every reboot

### ISSUE THREAD

**Issue by C-Holzer** [cpriego/valet-linux#139]
I am using Ubuntu 17.10.1 server and valet-linux 2.0.23. In this version, /etc/resolv.conf is a sym-link to /opt/valet-linux/resolv.conf.

The file consists of one line where localhost (127.0.0.1) for a nameserver, I cannot resolve domains. If I edit the original file to include a real dns server everything resolves correctly. At least until I reboot the machine. When I do the system restores the resolv.conf file to the original with only 127.0.0.1 in it. Is there a fix I can implement other than constantly editing the file every time I reboot?

**Comment by TheNodi** [comment]
Unfortunately this is known problem of the last version.

There is a rewrite "in queue", you can follow https://github.com/cpriego/valet-linux/issues/133
