### ISSUE TITLE
Domain Exception: Unable to determine service name

### ISSUE THREAD

**Issue by ciliehub** [cpriego/valet-linux#14]
Hi

I got this error ('Unable to determine service name') while running ```valet install```. Almost every ```valet``` command I input yields this error. I tried to reinstall the complete package but the same happened. 

On an other machine, it worked last saturday (after stop, uninstall and reinstall, to be precise). Can't install on this machine...

Any idea?

**Comment by cpriego** [comment]
Hi @ciliehub, what distro are you using?

**Comment by olabogen** [comment]
Hi
I have the same issue on Ubuntu 16.04. Installed all the dependencies using php7.0.

**Comment by cpriego** [comment]
Ok, I was able to reproduce the bug with a fresh install. The try-catch wasn't dropping the exception silently, interrupting the installation instead. I just pushed a new version that fixes this issue as well as a little improvement.

**Comment by olabogen** [comment]
I solved this one by running `composer global update`.
Got me over to the other issue.  Unable to determine PHP-FPM configuration folder.

**Comment by alshstf** [comment]
Got the same issue with latest valet on ubuntu 16.04 @ Windows subsystem for Linux:
```
~$ valet install
sh: 1: /home/alshstf/.composer/vendor/cpriego/valet-linux/cli/scripts/update.sh: Permission denied
Enabling nginx.service ...


  [DomainException]
  Unable to determine service name.


install [--ignore-selinux]
```

**Comment by ashishpatel0720** [comment]
I think the problem is with the apache software installed on your system, you can checkout following link which worked for me.
https://andrefigueira.com/2017/02/08/how-to-fix-domain-exception-with-valet-for-linux

**Comment by defaye** [comment]
I had this issue when I upgraded php from 7.0 to 7.2. I just had to run valet install and it picked up that I was missing php7.2-fpm (I think).

```
$ valet install
Nginx was already enabled
Stopping nginx...
[php7.2-fpm] is not installed, installing it now via Apt... 🍻
Php7.2-fpm was already enabled
Restarting php7.2-fpm...
Dnsmasq was already enabled
Installing Valet DNS service...
Valet-dns was already enabled
Systemd-resolved was already disabled
Stopping systemd-resolved...
Restarting network-manager...
Restarting dnsmasq...
Starting valet-dns...
Restarting nginx...

Valet installed successfully!
```

**Comment by jartaud** [comment]
@defaye thanks!
