### ISSUE TITLE
domains dont work unless I 'secure' them

### ISSUE THREAD

**Issue by Amiiir** [cpriego/valet-linux#140]
I was able to `ping` all domains in terminal and it seemed OK (they were responding). But the browser couldn't open the pages. Finally I used `valet secure <domain>` and it worked. Although I spent a lot of time to finally find it, I know it's not an actual solution... But for now it's good enough.

**Comment by TheNodi** [comment]
Is valet responding on plain http? Do you see `Valet - Not Found` page or is it not capable of connecting?

**Comment by Amiiir** [comment]
Hi @TheNodi,
I have google chrome as my default browser, and when I entered the URL "http://\<domain\>" it **automatically redirected me to "https://\<domain\>"**, and this page loaded:

![chrome-http](https://user-images.githubusercontent.com/8914433/37244314-62f66ff0-249c-11e8-8b29-4b7d3cbf62cf.JPG)

Then I switched to ubuntu default browser and this page loaded:

![internet-http](https://user-images.githubusercontent.com/8914433/37244317-795be090-249c-11e8-87fc-58aca74e5f64.JPG)

And when I used `valet secure <domain>`, it worked:

![chrome-https](https://user-images.githubusercontent.com/8914433/37244324-90b8b7b8-249c-11e8-813f-19f65bba0766.JPG)

**Comment by TheNodi** [comment]
`.dev` TLD is automatically redirect to HTTPS by chrome. 

See https://github.com/cpriego/valet-linux/issues/98 and https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

You should switch to a reserved domain like `.test`:
```
valet domain test
```

**Comment by Amiiir** [comment]
No, I've tested it before and I've just tested it now again. I got the exact same results with `.test` TLD

**Comment by TheNodi** [comment]
Let's stick with `.test` to remove chrome from the causes then.

There might be some stale configuration of ngnix.
Try:
```
sudo apt-get purge ngnix
valet install
```

**Comment by Amiiir** [comment]
I had already uninstalled and reinstalled nginx and valet so many times. But didn't know about the chrome cache. I cleared it and it solved the problem. thank you

**Comment by TheNodi** [comment]
It's a security feature to avoid/reduce man-in-the-middle attacks. Clever, annoying when you are developing, but still quite useful for the end user. 

Happy to hear it's solved! :)
