### ISSUE TITLE
Not working on Ubuntu 17.10

### ISSUE THREAD

**Issue by slakbal** [cpriego/valet-linux#147]
Fresh install of everything....

Pages once got loaded and then stopped. Wish I could help with this great tool, but I just know too little about these things.

**Comment by maiquelleonel** [comment]
I use `valet-linux` on 17.10 and works for me. 

how do you installed? Maybe I help you.

**Comment by antonioribeiro** [comment]
Wasn't working for me too, but it's working now.
Check your log files and fix the errors you might have there.
I had to remove the gzip config which was conflicting nginx.conf.

**Comment by chrysanthos** [comment]
Having the same issue, logs are empty. `valet park` did not detect the subfolders. I tried using `valet link` which linked the subfolder but I am getting a Server Not Found error.

**Comment by jrmypttrsn** [comment]
I've been having the same issue since upgrading to 17.10. I can ping my .dev domain and get positive results but when I open the site in Firefox all I get is an "unable to connect" error message.

**Comment by WMisiedjan** [comment]
Did anyone solve this yet?

**Comment by icarojobs** [comment]
For me doesn't work too. Any solution?

In my browser, I see: 502 Bad Gateway (nginx), and no errror on nginx log file. :-(

Help us, please.
My setup: Ubuntu 16.04, laravel 5.6, nginx 1.14.0.

Thank you.
