### ISSUE TITLE
Unable to determine PHP-FPM configuration folder.

### ISSUE THREAD

**Issue by lucidlemon** [cpriego/valet-linux#15]
While installing I get this weird `Unable to determine PHP-FPM configuration folder.` error message.

Using Ubuntu 16.10, installed php 7.0 fpm and it is running fine according to services. Full Output:

```
 daniel@fuckwindows  ~  valet install                 
Stopping nginx...

                                                     
  [DomainException]                                  
  Unable to determine PHP-FPM configuration folder.  
                                                     

install [--ignore-selinux]
```

**Comment by cpriego** [comment]
Hi @lucidlemon. I'm yet unable to reproduce your issue. Try updating valet to the latest version. See if it solves the problem. If not, maybe purging php, deleting the /etc/php/7.0 folder manually and reinstalling php could help.

By the way, are you using the default php7.0 packages from ubuntu? or are the ppa versions?

**Comment by moraya-re** [comment]
Hi @cpriego, Did what you suggest. But having the same issue :disappointed:. 


```
Stopping nginx...
[php-fpm] is not installed, installing it now via Apt... 🍻

                                                     
  [DomainException]                                  
  Unable to determine PHP-FPM configuration folder.  
                                                     

install [--ignore-selinux]
```
I freshly installed php-fpm.
Also there is no command php-fpm but php-fpm7.0.

php-fpm7.0 --version outputs,
```
PHP 7.0.13-0ubuntu0.16.04.1 (fpm-fcgi)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies

```
Thanks,
Ganesh

**Comment by cpriego** [comment]
Could you please paste de output of `ls /etc/php/7.0/fpm` and `ls /etc/php7.0/fpm`?

**Comment by moraya-re** [comment]
@cpriego 
for `ls /etc/php/7.0/fpm` output is ->
`conf.d  pool.d  php-fpm.conf  php.ini`

for `ls /etc/php7.0/fpm` output is ->
`ls: cannot access '/etc/php7.0/fpm': No such file or directory`

**Comment by nikosson** [comment]
I'm gettings the same error, reinstalled OS and now wanted to install Valet, and faced with this problem

**Comment by cpriego** [comment]
I've tried with various scenarios (clean installs/removing all packages and configuration and reinstalling) and I still can't reproduce this issue. In each scenario I run 
```
sudo apt install php7.0-cli php7.0-mcrypt php7.0-sqlite3 php7.0-curl php7.0-mbstring php7.0-xml php7.0-zip jq xsel libnss3-tools curl
```
then I install composer globally and run
```
composer global require "cpriego/valet-linux"
```
finally (and without adding the vendor/bin folder to my path)
```
~/.config/composer/vendor/bin/valet install
```

**Comment by moraya-re** [comment]
@cpriego Please review pull request.

**Comment by cpriego** [comment]
Valet has been updated with the PR. Thanks a lot @moraya-re could you please confirm it works for you?

**Comment by nikosson** [comment]
It works now, thx @moraya-re & @cpriego !
