### ISSUE TITLE
valet install rewrites resolv.conf

### ISSUE THREAD

**Issue by fantasyobchod** [cpriego/valet-linux#151]
- valet v2.0.24
- archlinux kernel 4.12.13-1-ARCH

After command `valet install`  `/etc/resolv.conf` is rewritten so it looks like this

```
#
# /etc/resolv.conf
#

#search <yourdomain.tld>
#nameserver <ip>

# End of file
```

So internet stops working.

After adding something like `nameserver 8.8.8.8` everything seems to work fine.

**Comment by david-dacruz** [comment]
Same for ubuntu 18.04 I added nameserver in resolv.conf file and internet starts again but valet cannot find any of the domains parked now, anybody got a fix for this ?

**Comment by TheNodi** [comment]
This is unfortunately a problem on a few distros, you can follow issue #112 .
