### ISSUE TITLE
valet install

### ISSUE THREAD

**Issue by chabinot** [cpriego/valet-linux#153]
Hello,
After enterig valet install, i have this message:
"You have missing Valet dependiancies :
- certutil "
I am on Ubuntu 18.04LTS
Thhanks to tell me how to do ?
Regards

**Comment by TheNodi** [comment]
Sorry to be so late. It should be in this package:
```
sudo apt-get update       
sudo apt-get install libnss3-tools
```

**Comment by borealsmith** [comment]
Thank you. this worked for me !

**Comment by condef5** [comment]
Thanks @TheNodi

**Comment by jmarcher** [comment]
Closing this issue as it seems to be resolved.

**Comment by im-fahad** [comment]
Thank you. this worked for me !

**Comment by k-1-e** [comment]
You have missing Valet dependiencies:
 - xsel
 - certutil
 me da estos errores esty en mac catalina ayuda alguien

**Comment by jmarcher** [comment]
> You have missing Valet dependiencies:
> 
>     * xsel
> 
>     * certutil
>       me da estos errores esty en mac catalina ayuda alguien

Fijate en el nombre del repositorio, esta versión de Valet es para Linux y no para Mac, para ello tienes que ir al repositorio oficial de Laravel

**Comment by gfonsecapilarte** [comment]
> You have missing Valet dependiencies:
> 
>     * xsel
> 
>     * certutil

A mi me faltan estos mismos en linux

**Comment by gfonsecapilarte** [comment]
> 
apt install xsel jq 
eso resolvio
