### ISSUE TITLE
php-fpm not starting

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [cpriego/valet-linux#155]
... because "operation not permited" while creating socket file inside user home dir. linux does not allow sockets in home dirs
changing the path to something like /var/tmp/valet.sock works fine.

**Comment by TheNodi** [comment]
Can you add information about OS and package versions?
Do you have SE Linux?

**Comment by Vasiliy-Bondarenko** [comment]
latest release on Ubuntu 18.04
