### ISSUE TITLE
"Welcome to nginx!" for all sites 

### ISSUE THREAD

**Issue by eromanov** [cpriego/valet-linux#156]
Hello,

I installed Valet in Ubuntu 16.04, but after doing valet park all of my sites only show the "Welcome to nginx!" splash page. Is there a way for me to configure the root directory for each domain?

**Comment by TheNodi** [comment]
Nginx might not be loading the correct configurations. Have tried restarting the nginx service? Or running `valet install` again?

**Comment by bytepicker** [comment]
Forced stopping nginx and running `valet install `again worked for me
