### ISSUE TITLE
Network not working after valet install

### ISSUE THREAD

**Issue by Destinais** [cpriego/valet-linux#157]
Hello,
After install valet on my Ubuntu 18.04, I can't reach internet. But if I do echo nameserver 8.8.8.8 > /etc/resol.conf, i can reach internet but my local project don't work.
Have you a solution plz?

Good bye

**Comment by TheNodi** [comment]
There're some problems with some distros, see issue #112 . 

To fix it manually, add google dns servers after valet's, don't replace it.
