### ISSUE TITLE
valet links command not showing list table

### ISSUE THREAD

**Issue by zendzo** [cpriego/valet-linux#158]
everything works prefect expect valet links to show links list table
it's only show empty table list
```
+------+-----+-----+------+
| Site | SSL | URL | Path |
+------+-----+-----+------+
```
valet unlink also not work
after i ran valet unlink the path still in valet path

```
valet unlink Codes/kejaksaa
The [Codes/kejaksaa] symbolic link has been removed.
```

it's still in valet path
```
valet path
[
    "/home/mustofa/.valet/Sites",
    ".",
    "/home/mustofa/Codes/kejaksaan",
    "/home/mustofa/Codes"
]

```

**Comment by TheNodi** [comment]
I think you're mixing commands.

"[Linking](https://laravel.com/docs/5.6/valet#the-link-command)" is connecting a folder to a domain, and you can use the following commands:
- `valet link [domain]`: Link the current folder to given domain
- `valet unlink`: Remove the current folder from domains
- `valet links`: List all linked folders

"[Parking](https://laravel.com/docs/5.6/valet#the-park-command)" is selecting a folder such that all sub-folders gets connected to a domain (matching the sub-folder name), and you can use the following commands:
- `valet park [path?]`: Park the current folder (or the given path)
- `valet forget [path?]`: Forget the current folder (or the given path)
- ِ`valet paths`: Display all parked folders (not linked one)

To answer your question, if you want to remove `Codes/kejaksaan` folder, use: `valet forget /home/mustofa/Codes/kejaksaan`.

I hope this solves your problem!
