### ISSUE TITLE
Valet Park not recoginizing laravel installations

### ISSUE THREAD

**Issue by WordsofDefiance** [cpriego/valet-linux#162]
Just installed a fresh version of valet-linux and everything seems to be working.

However, I'm getting hung up on `valet park`.  I have a ~/code directory, and I run `valet park` inside it. Then I do a `laravel new blog` command and laravel installs a copy of itself in ~/code/blog. However, blog.test doesn't load up the actual `blog` directory. Instead, I get the default apache2 ubuntu screen that loads on every .test domain.

I've uninstalled valet and restarted apache several times -- still get the same result.

Here's my config.json...  everything looks good to me. Any idea what I might be doing wrong?

`{
    "domain": "test",
    "paths": [
        "/home/blah/.valet/Sites",
        "/home/blah/Code"
    ],
    "port": "80"
}`

**Comment by TheNodi** [comment]
Valet is not using Apache2, it uses nginx.

You can either uninstall Apache2 and restart Valet, or change valet's port using `valet port 8080` and access your site at http://blog.test:8080/ .

**Comment by WordsofDefiance** [comment]
Brilliant, thank you!!!
