### ISSUE TITLE
general bad design issue - missing warning in docs

### ISSUE THREAD

**Issue by COLABORATI** [cpriego/valet-linux#165]
From a few issues I have had with valet recently I feel like it is an extremely bad idea to prepend some php script just to avoid a static nginx configuration - this does not make any sense but generates issues. 

I just want my nginx to be configured, but I do NOT want some magic php happening before my own scripts are executed - this is especially true for a development situation where I need total control of every little bit. 

I really like the idea of a quick nginx config, but that prepending of the valet php is bad and should be at least optional. It makes more sense to generate nginx config files for each local dev domain. 

Please rethink that ugly design. At least please put some warnings on the docs, e.g.:

*"Beware: valet will add some variables to global namespace and also change values of DOCUMENT_ROOT and SCRIPT_FILENAME to something you might not expect - remember that, when you see some strange errors happening on your local valet install!"*

I am frustrated with valet as it has stolen my time in very specific debugging sessions and I am going back to a plain nginx config without any php prepended.

**Comment by TheNodi** [comment]
We don't control the official [Valet Documentation](https://laravel.com/docs/5.6/valet#valet-or-homestead) nor made any design decision on how valet works. We just port it from Mac to Linux.
I suggest to discuss those in the official [Valet repository](https://github.com/laravel/valet).

Configuring a custom nginx entry for every host is not easily compatible with the `park` feature. Valet works with most framework, if you need more control over your dev environment I suggest switching to a raw nginx, vagrant (homestead), docker, it's full of options.
