### ISSUE TITLE
Valet opens another project that not i've been created 

### ISSUE THREAD

**Issue by mauudev** [cpriego/valet-linux#167]
Hi! i'm using Arch Linux and this is the first time that i use Valet for serve my new project.
Before at all, i used the traditional process to link my projects on my local server by creating a new virtual hosts conf for my projects like "project1.local",  "project2.local", so when i park my new project folder and opens "newproject.test" Chrome shows me my "project1.local" main window, how can i solve this? is there other configuration that i need to serve my new app? thanks

**Comment by TheNodi** [comment]
Since your're talking about virtual hosts, are you using apache? 
Valet is using nginx, so they might be conflicting on port 80. You either have to stop apache and restart valet, or change valet's port using `valet port 8080`.
