### ISSUE TITLE
Valet Stops Working After Short Periods of Time, Can Only Be Fixed By Uninstalling and Reinstalling

### ISSUE THREAD

**Issue by WordsofDefiance** [cpriego/valet-linux#168]
I have installed Valet onto Ubuntu 18.04. 

In order to get the install to run properly, I first have to stop Apache2. Only then could I install Valet and have nginx install properly. 

However, I do get Valet working properly eventually using a /Sites directory and `valet park`.  Once Valet is running properly I can ping and *.test domain and see localhost responding. All the folders in my sites directory show up as .test urls as desired.

However, after an indeterminate amount of time, valet stops serving those sites on .test domains, and pinging *.test domains fails. `valet status` indicates that valet is still running, but I still get nothing positive in the browser or via ping. The only way I can get valet working again is to run `valet uninstall` and then `valet install` and `valet park` again.

Any idea what might be going on? Another thing I've noticed is that valet doesn't seem to have permission to write to its own log file so I can't seem to diagnose the problem.

**Comment by WordsofDefiance** [comment]
Bumping this.

**Comment by insomnious0x01** [comment]
That's an interesting issue. When valet stops serving the sites on .test domain:

1. what error message do you see in your web browser?
2. what is the status of Apache2? is it running when this happens?
3. Does the issue happen when you restart your computer? Or is the computer on all the time and after some time passes the issue occurs?

**Comment by WordsofDefiance** [comment]
1. The error message is simply a general 404. 
2. `apachectl status` gives me "404 - Not Found"
3. When I restart the computer, valet does not start automatically. It seems to stop working after periods of inactivity -- if I am constantly pinging sites or accessing them through a browser, it usually keeps working.

**Comment by insomnious0x01** [comment]
Could you stop Apache2 service and make sure that Nginx and PHP FPM are running? Is Valet serving the sites after applying this change?

**Comment by ilyes-kechidi** [comment]
i'm facing the same problem after changing my wireless network , on each restart i have to uninstall then install valet again to get the DNS working again

**Comment by agasigp** [comment]
> i'm facing the same problem after changing my wireless network , on each restart i have to uninstall then install valet again to get the DNS working again

I'm facing the same problem here :( Don't know why but suddenly valet is not working anymore like you said.

**Comment by AriieelEsteban** [comment]
same problem here with ubuntu subsystem windows :c
