### ISSUE TITLE
How to uninstall valet in Ubuntu 18.04?

### ISSUE THREAD

**Issue by cjlaborde** [cpriego/valet-linux#170]
I been trying to use my localhost environment yet since I installed valet I can't.
![image](https://user-images.githubusercontent.com/40572114/43592332-51aef12c-9643-11e8-8d55-6c95fbbc6a58.png) 

I get a page that says 404 - Not Found
and the title of page is Valet - Not Found.

So how can I use localhost againt without valet getting in the way?

I used valet uninstall and it killed my internet connection.
Had to Valet install again to get my internet connection.

So now I can't use my localhost and neither uninstall valet. 
It's there a way to remove it without removing ngnix or php? 

I use ngnix for my local environment.

**Comment by pedzed** [comment]
If you see `404 - Not Found` it's good. It means Valet works.

You need to run
```
valet paths
```
To see which paths are registered.

If you want to add the current directory as an application path, run
```
valet link
```

If you want to add the current directory as a path containing multiple applications, run
```
valet park
```

For example, if you have these two applications:
```
/home/ped/www/my-app
/home/ped/www/my-second-app
```
Go to `/home/ped/www` by running `cd /home/ped/www` and enter `valet park`. Then open your browser and go to `http://my-app.test` and it should be working.

**Comment by cjlaborde** [comment]
> If you see `404 - Not Found` it's good. It means Valet works.
> 
> You need to run
> 
> ```
> valet paths
> ```
> To see which paths are registered.
> 
> If you want to add the current directory as an application path, run
> 
> ```
> valet link
> ```
> If you want to add the current directory as a path containing multiple applications, run
> 
> ```
> valet park
> ```
> For example, if you have these two applications:
> 
> ```
> /home/ped/www/my-app
> /home/ped/www/my-second-app
> ```
> Go to `/home/ped/www` by running `cd /home/ped/www` and enter `valet park`. Then open your browser and go to `http://my-app.test` and it should be working.

Thank you but ended up getting rid of it. Took my a while system it would mess up my install.
Thanks to this thread managed to uninstall for good and fix my internet. https://github.com/cpriego/valet-linux/issues/115

**Comment by JohnTheo13** [comment]
I can confirm that the above didn't change anything, not found remains.
I have uninstalled apache2 and everything, but still no access
