### ISSUE TITLE
how to increase upload_max_filesize

### ISSUE THREAD

**Issue by kofyebs** [cpriego/valet-linux#172]
changing the values this file will do the job.
php.ini file : /etc/php.ini

`upload_max_filesize` and `post_max_size` and `memory_limit`

**Comment by MerrySean** [comment]
hey @kofyebs have you solved this problem?

I already had change the max upload file size of nginx by adding this line 

`client_max_body_size 100G;`

And I also modified php.ini to accept larger files by setting `upload_max_filesize` and `post_max_size`

I keep on getting `500 internal server error`

**Comment by kofyebs** [comment]
can you please lemme know which file you edited?

**Comment by MerrySean** [comment]
php.ini file : /etc/php.ini
nginx : /etc/nginx/nginx.conf

**Comment by kofyebs** [comment]
Yes, 
i did made changes to the same file and location and mine is working fine.

please try to make those values in M not G and see. example `client_max_body_size 102 400M`

**Comment by MerrySean** [comment]
may I know what's the purpose of 102?

**Comment by kofyebs** [comment]
sorry my bad `client_max_body_size 102400M` no space.

**Comment by MerrySean** [comment]
tried that already.. no work , I even tried A much larger number..

one thing to know.. I tried to upload a smaller file like 500B image (icon) and I was a success..

and everytime I change the values in php.ini and nginx config I always run valet restart..

**Comment by kofyebs** [comment]
maybe your server cannot handle big files. have tried changing the `memory_limit` if not do so and try and again

**Comment by MerrySean** [comment]
is that config found on nginx? or php?

**Comment by MerrySean** [comment]
boom.. thanks.. I wonder what could be the maximum memory_limit for nginx server

**Comment by kofyebs** [comment]
Nice! you're welcome. 
It all depends on how much memory your system got.

**Comment by vishytk** [comment]
I am getting the same error (500) while trying to upload files more than 5kB size.

Valet = 2.1.8 (2.1.7)
Fedora 30

php.ini settings are fine and works with "php artisan serve"
only issue with valet/nginx

**Comment by jmarcher** [comment]
Please provide more info and do not rebump old issues, just open a new one.
