### ISSUE TITLE
Getting an error when attempting to log into MySQL

### ISSUE THREAD

**Issue by cyberdime** [cpriego/valet-linux#173]
Hi guys,

I installed Valet-Linux and MySQL-Server, but when I try to log into MySQL from the Terminal I receive the following error...

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

How do I resolve this? 

Thank you!

```
OS: Linux Mint 19 Tara x86_64 
Kernel: 4.15.0-29-generic
```

**Comment by insomnious0x01** [comment]
Hi,

Try restarting MySQL service by running `sudo service mysql restart` command. 

Did you go through `mysql_secure_installation`  process after you installed MySQL? If you didn't, and the service restart command doesn't solve your issue, you'll have to run the `mysql_secure_installation` command.

**Comment by jmarcher** [comment]
I'm closing this issue as it is not valet-linux related.
