### ISSUE TITLE
'valet secured' command shows " is not secured"

### ISSUE THREAD

**Issue by pedzed** [cpriego/valet-linux#176]
When you run
```
valet secured
```
it outputs
> is not secured

including the space at the beginning.

Even when you successfully run
```
valet secure
```
with a working setup, it gives the same error.

```bash
$ valet --version
Valet v2.0.24

$ valet status
Php7.2-fpm is running...
Nginx is running...

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
````

**Comment by pedzed** [comment]
@jmarcher It would be good for documentation reasons to mention the reason of closing the issue.

If a certain commit fixed the issue, I suggest using https://help.github.com/en/articles/closing-issues-using-keywords.

**Comment by kraveir0** [comment]
I'm having this issue on the newest version.

Anyone with the same problem?

**Comment by wilmanbarrios** [comment]
I'm having this issue too, with the latest version. 

I was running just fine before upgrade to the latest version.

**Comment by josegus** [comment]
Same here, plus valet secure is not working, it creates the certificate but chrome, opera and firefox says the certificate is invalid. I'm using ubuntu 20.04 and valet 2.2.16
