### ISSUE TITLE
Always get this error. What step do i miss?

### ISSUE THREAD

**Issue by jehan96** [cpriego/valet-linux#178]
![image](https://user-images.githubusercontent.com/38547390/45456201-74b84200-b71c-11e8-8f65-29920a694d48.png)

**Comment by insomnious0x01** [comment]
Navigate to the `blog` folder in your terminal and run `valet open` command. If that doesn't work, could you provide the steps that you followed to get to this point?

**Comment by jkoech** [comment]
If you are using google chrome, please note that all .app and .dev domains have forced SSL. You can cd to your site's directory and run ```valet secure``` command. If you don't want to do that, you can change domain from .app to something else like ``` valet domain local```.

**Comment by jehan96** [comment]
thanks for suggestion..
after i complete reinstall again linux on my machine and also mysql..
i will definitely try your suggestion..
thanks

anyway, i stop for a while learning laravel because i have problem with mysql..
so as for now i can't work with database at all which is not really good.
i try numbers of attempt to remove and then reinstall mysql, i also even try to add password..but always saying that my mysql have no password..lesson i learn, we should always set password for mysql.
