### ISSUE TITLE
Unable to install valet

### ISSUE THREAD

**Issue by emmiejw** [cpriego/valet-linux#179]
![screenshot from 2018-10-10 14-36-25](https://user-images.githubusercontent.com/39866191/46740534-fd35ee00-cc9a-11e8-8e65-8823a788f150.png)
Good afternoon,
I previously used valet on windows and loved it! I've now got ubuntu 18.04 desktop and I've been trying to get valet installed and struggling! 

I have made sure the $PATH is correct too.   

Any help will be greatly appreciated as I've hunted thtrough google and youtube for solutions and none have worked :-(

**Comment by emmiejw** [comment]
Anyone??

**Comment by chdzma** [comment]
I have a similar problem 

![image](https://user-images.githubusercontent.com/24399312/47271563-c7d2af80-d57a-11e8-89be-3b1243747316.png)

**Comment by emmiejw** [comment]
this is what worked for me 
![screenshot from 2018-10-22 19-29-12](https://user-images.githubusercontent.com/39866191/47311115-d085bd00-d630-11e8-8c11-da1fced4ac02.png)
