### ISSUE TITLE
502 bad gateway time out

### ISSUE THREAD

**Issue by ramsaiphp** [cpriego/valet-linux#18]
Hi,

When using valet open in my projects folder it is redirecting to firefox with some errors in console and opening the browser. After opening the browser getting message 502 Bad Gateway.

**Comment by vmunich** [comment]
Did you run `valet install`? I had this problem and the install command fixed the problem.

**Comment by ramsaiphp** [comment]
after running valet install i am getting below message:
[DomainException]                      
  Apt was unable to install [php5-fpm].

My Operating System is Ubuntu 14.04 and my php version is 7.0

**Comment by cpriego** [comment]
@ramsaiphp Upgrade to the latest Valet and uninstall the php5-cli package as it is no longer supported (that's the ubuntu php 5.5.9 version)

To remove only php5-cli do a
```
sudo apt-get purge php5-cli
```

And to remove all unsupported php5 (5.5.9) packages
```
sudo apt-get purge php5-*
```

**Comment by ramsaiphp** [comment]
I have already updated my php to 7.0

**Comment by cpriego** [comment]
@ramsaiphp Sorry for the delay. Please update to the latest version and report back any changes. I discovered `valet open` was being run with sudo and it was causing a lot of issues.

**Comment by cpriego** [comment]
Hi @ramsaiphp, has the issue been solved? I'll wait 7 more days for an answer, if there is none I'll assume it is and close it.
