### ISSUE TITLE
System error.Program terminated  Eopkg was unable to install [php-fpm].  

### ISSUE THREAD

**Issue by abrhambas01** [cpriego/valet-linux#184]
![image](https://user-images.githubusercontent.com/12043306/48311441-f4f30a80-e5da-11e8-96d7-f44585fdfbaf.png)

I get that bug/error when I'm trying to install valet it says something like 

In Eopkg.php line 67:
                                          
  Eopkg was unable to install [php-fpm].  
                                          @ivanlogiudice

**Comment by JamesBernacer97** [comment]
chelraiul@gmail.com:Hi7be7of2 | Level: 77 | Name: A4B4 | Rank: Mythic (3 stars) | UID: 23228970 (5202) | Registered: 2016-12-26T04:35:04.000Z
tolentino.annierose@gmail.com:Tolentino123 | Level: 76 | Name: ê§âœ§à¼ºAJà¼»âœ§ê§‚ | Rank: Mythic Honor (31 stars) | UID: 1025640403 (11037) | Registered: 2021-07-26T08:06:18.000Z
jack44042@gmail.com:DevilJack123 | Level: 88 | Name: â˜…SjRâ˜… Begal | Rank: Mythic Glory (52 stars) | UID: 113624596 (2575) | Registered: 2017-10-24T03:49:57.000Z
robertsw96@icloud.com:Robertsw289 | Level: 61 | Name: ÎšÏ€Î’â€¢Robin | Rank: Legend IV | UID: 28184352 (5203) | Registered: 2017-01-11T04:53:37.000Z
oamoam001@hotmail.com:OAMoam32295 | Level: 62 | Name: MaxxMa | Rank: Epic IV | UID: 109666703 (2229) | Registered: 2017-10-14T01:29:41.000Z
torcuatoivandemeter@gmail.com:Swordartonline2 | Level: 63 | Name: Demeterminator | Rank: Mythic (20 stars) | UID: 802452338 (10543) | Registered: 2020-09-20T15:58:25.000Z
luthfi.wira27@gmail.com:Sd123456 | Level: 89 | Name: ä¸Žky_Å¡Ï…ÏÎµÑâ„¢ | Rank: Mythic Honor (29 stars) | UID: 62268160 (2108) | Registered: 2017-06-01T06:34:08.000Z
jiasonmontallana@gmail.com:Jiason123 | Level: 51 | Name: Onion Ring | Rank: Mythic Honor (29 stars) | UID: 9521450 (3201) | Registered: 2016-11-13T02:03:07.000Z
toshirogarfiaz@gmail.com:Lisandro100 | Level: 80 | Name: âœï¸Jackâœï¸ | Rank: Legend I | UID: 464779134 (5209) | Registered: 2019-06-11T15:12:17.000Z
shanengrelon1999@gmail.com:Lesclaudes2 | Level: 60 | Name: Nekocid | Rank: Epic IV | UID: 591966303 (6084) | Registered: 2019-12-15T19:33:44.000Z
vince_basilio04@yahoo.com:se2121Na | Level: 85 | Name: S1mple. | Rank: Mythic Glory (75 stars) | UID: 10023781 (3201) | Registered: 2016-11-14T11:43:35.000Z
michael.lu97@gmail.com:Lu120897 | Level: 75 | Name: Miccc | Rank: Mythic Honor (25 stars) | UID: 23210043 (2031) | Registered: 2016-12-26T03:00:33.000Z
ilhmbdlmlk@yahoo.com:Belany10 | Level: 87 | Name: De Bruyne | Rank: Mythic Honor (35 stars) | UID: 67008859 (2117) | Registered: 2017-06-15T16:49:08.000Z
simply.emo16@yahoo.com:Khaykhay16 | Level: 83 | Name: KhayXD | Rank: Mythic Honor (29 stars) | UID: 14723848 (3022) | Registered: 2016-11-30T06:05:51.000Z
leymakara123@yahoo.com:Mith1234 | Level: 58 | Name: à½ŒRe:Bornà½‘ | Rank: Mythic (10 stars) | UID: 347134218 (3693) | Registered: 2018-12-22T12:50:06.000Z
puswood14@gmail.com:Brianpuspos14 | Level: 64 | Name: Fvck BÃ®tch WÃ«ak | Rank: Mythic (9 stars) | UID: 35777389 (3209) | Registered: 2017-02-14T12:43:49.000Z
Fabianbaas7@gmail.Com:Fabian123 | Level: 57 | Name: MadDoG | Rank: Grandmaster IV | UID: 4257486 (6006) | Registered: 2016-10-20T22:42:44.000Z
brayanreyesXD@yahoo.com:ZEXYZEXs1 | Level: 83 | Name: Vexery | Rank: Mythic (13 stars) | UID: 226395407 (5217) | Registered: 2018-05-22T02:25:52.000Z
farhan.yanot90@gmail.com:Herman90 | Level: 69 | Name: Mystry. | Rank: Mythic Glory (52 stars) | UID: 43760143 (2070) | Registered: 2017-03-23T19:50:52.000Z
komapor96@freemail.hu:Hve10521 | Level: 79 | Name: Mckur | Rank: Legend III | UID: 69303155 (6209) | Registered: 2017-06-22T20:10:41.000Z
pushoktecto@gmail.com:PUshok777 | Level: 68 | Name: Ð·Ð¸Ð½ÐºÐ°666 | Rank: Legend III | UID: 7287525 (6010) | Registered: 2016-11-04T08:00:13.000Z
earlcgvelasquez@gmail.com:Earl0604 | Level: 63 | Name: Xevra | Rank: Legend IV | UID: 105853498 (3222) | Registered: 2017-10-03T23:12:06.000Z
raiswolf13@gmail.com:T05w3373 | Level: 71 | Name: TJtheOne | Rank: Mythic Honor (32 stars) | UID: 399911908 (5031) | Registered: 2019-03-10T16:54:55.000Z
kyle.corpus202001@gmail.com:Jahleel20 | Level: 84 | Name: Fugazi | Rank: Mythic (23 stars) | UID: 121515588 (3125) | Registered: 2017-11-13T06:35:56.000Z
khanhthailai@gmail.com:738738Khanhthai | Level: 52 | Name: ~ashikara~ | Rank: Epic V | UID: 80732578 (5209) | Registered: 2017-07-25T18:30:51.000Z
dickykurniawan63@gmail.com:Vikingmania123 | Level: 66 | Name: Dicky808 | Rank: Mythic (9 stars) | UID: 376290676 (9745) | Registered: 2019-02-03T10:31:01.000Z
rd_nuclear@yahoo.com:Jamiroquai1 | Level: 56 | Name: Nukie | Rank: Grandmaster II | UID: 120016858 (6216) | Registered: 2017-11-09T20:20:45.000Z
willchuasy@gmail.com:Jpw54321 | Level: 84 | Name: èŒ¶å¶eggs | Rank: Mythic Immortal (128 stars) | UID: 28208392 (2038) | Registered: 2017-01-11T07:56:17.000Z
naurice.kaye@gmail.com:Onedirection23 | Level: 65 | Name: nkaye | Rank: Mythic (22 stars) | UID: 658129442 (10226) | Registered: 2020-03-18T17:49:23.000Z
OfficialBlitzzy@outlook.com:JAMESisCOOL1 | Level: 67 | Name: ã€Žá | Rank: Mythic (14 stars) | UID: 469167330 (5212) | Registered: 2019-06-17T14:58:33.000Z
giggsong@gmail.com:G300603g | Level: 55 | Name: Juno | Rank: Legend II | UID: 22874796 (2028) | Registered: 2016-12-25T06:24:07.000Z
cidtokeezen@yahoo.com.sg:Pokker123 | Level: 52 | Name: aong | Rank: Legend I | UID: 99654863 (2225) | Registered: 2017-09-17T02:06:31.000Z
crazy.lee.700@gmail.com:GS1905gs | Level: 67 | Name: Niiixxx | Rank: Legend I | UID: 456341666 (6247) | Registered: 2019-05-31T15:48:11.000Z
chloerelucio1@gmail.com:Chloefrancine04 | Level: 65 | Name: cripplinganxiety | Rank: Legend V | UID: 446425342 (3960) | Registered: 2019-05-18T03:32:29.000Z
sumiranjohnrod@gmail.com:Planets12 | Level: 62 | Name: JRODPOGI | Rank: Mythic (4 stars) | UID: 399992861 (3824) | Registered: 2019-03-10T23:12:37.000Z
mad_jun@hotmail.com:Athrun88 | Level: 55 | Name: Lee Monn... | Rank: Legend IV | UID: 46636040 (2210) | Registered: 2017-04-05T09:37:52.000Z
troybalmores@gmail.com:Troygwapo08 | Level: 87 | Name: KuysTroy | Rank: Mythic (16 stars) | UID: 76467646 (3218) | Registered: 2017-07-13T04:39:46.000Z
irtizamazidrhythm@gmail.com:Ab123456789cD | Level: 55 | Name: Irtiza Mazid Rhythm | Rank: Legend V | UID: 708928568 (8828) | Registered: 2020-05-22T13:14:45.000Z
twent_cds@hotmail.com:Helena1605 | Level: 57 | Name: Twent.O.Hakaishin | Rank: Epic II | UID: 379771646 (1037) | Registered: 2019-02-08T12:21:46.000Z
danishazraei86@gmail.com:Danish2910 | Level: 56 | Name: Danthekiller | Rank: Legend I | UID: 42417860 (2069) | Registered: 2017-03-17T15:01:09.000Z
darklez.962@gmail.com:Cristhian147 | Level: 53 | Name: Darklez | Rank: Legend IV | UID: 1197093419 (1533) | Registered: 2022-04-04T15:34:58.000Z
italootricolor@gmail.com:YoriYamazaki97 | Level: 52 | Name: SKT Italo Lh | Rank: Epic V | UID: 769272 (1005) | Registered: 2016-09-22T16:12:03.000Z
allan.mangayo@gmail.com:Dejoya8996 | Level: 85 | Name: EntityMe | Rank: Legend II | UID: 533105707 (3413) | Registered: 2019-09-18T14:18:05.000Z
drakensangextasy@seznam.cz:Jan82011 | Level: 80 | Name: BlazeDelphine | Rank: Legend I | UID: 30341526 (6205) | Registered: 2017-01-20T19:45:20.000Z
alexphoon115@gmail.com:Alexphoon007 | Level: 61 | Name: â—†Shxck_5Hz | Rank: Legend IV | UID: 413724305 (9913) | Registered: 2019-03-31T09:02:54.000Z
dhaxrkv@gmail.com:Pikacraft21 | Level: 79 | Name: pale | Rank: Mythic Glory (52 stars) | UID: 21354164 (2026) | Registered: 2016-12-20T23:20:47.000Z
outlawswan99@gmail.com:Bayusekta77 | Level: 70 | Name: Pauu | Rank: Mythic Honor (33 stars) | UID: 1530505345 (16417) | Registered: 2023-12-06T08:48:42.000Z
davidsiwi98@gmail.com:Davidsiwi199 | Level: 64 | Name: Schmidths | Rank: Mythic (6 stars) | UID: 111817690 (2567) | Registered: 2017-10-19T12:22:49.000Z
boohamdanoo@gmail.com:Moh66530880 | Level: 51 | Name: No0bie | Rank: Legend IV | UID: 540134084 (8150) | Registered: 2019-09-29T09:43:34.000Z
theo.bayle03@gmail.com:Theobayleyoan03 | Level: 87 | Name: TehO | Rank: Mythic Glory (59 stars) | UID: 210306595 (9077) | Registered: 2018-04-23T16:57:53.000Z
