### ISSUE TITLE
secured domains with Firefox 64

### ISSUE THREAD

**Issue by Corben78** [cpriego/valet-linux#187]
When I secure a domain/directory with `valet secure <name>`, Firefox complains about an untrusted certificate. Firefox changed adding self signed certificates, so it's not easy to just add this to the exceptions on the first occurrence which shows MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT as error.

I've read https://github.com/laravel/valet/issues/296 where on the one hand manual exceptions are mentioned for each single project, which works, but also to import the Laravel Valet CA, which I can't find in my folder structure. That topic also seems only mac related. 
I'd prefer to not add an exception manually for each project.

The [faq](https://cpriego.github.io/valet-linux/faq#why-do-i-get-certificate-errors-after-securing-a-site) states a Firefox restart should help, but for me it doesn't. The above error still occurs. Maybe it's not working with newer versions of Firefox anymore?

Is it possible to enable projects for https with Valet on Linux working in Firefox without having to add each exception manually via several steps in settings? Am I missing something?

Sorry if this might be a duplicate, so far I could find mostly Chrome related topics about this issue.

I'm using .test as tld and I'm running Ubuntu 18.04.1 LTS with php 7.2 and valet-linux v2.0.24.

**Comment by techieshark** [comment]
Agree that it'd be nice if the Valet certificate were installed in Firefox (or at least that option given); the solution from https://github.com/laravel/valet/issues/296#issuecomment-447604765 seems to be a workaround which as described is specific to OS X.

This software aims to be an easy to use cert management system for local development - perhaps there's a way to incorporate it, or at least use the same techniques as it: https://github.com/FiloSottile/mkcert

**Comment by jmarcher** [comment]
Will check that out when find a little bit of time.

**Comment by Corben78** [comment]
Could you solve this issue, as it's closed now?

**Comment by jmarcher** [comment]
Valet Certificates are self signed, you should do what this comment describes:  https://github.com/laravel/valet/issues/296#issuecomment-447604765

If you need another certificate you could use `valet share` and use ngrok's certificate.

**Comment by Corben78** [comment]
Well, as written in the initial post and confirmed by @techieshark, that's OSX specific and does not apply for Linux. At least I can't find the CA that valet-linux would be using to create the self-signed certs, so I could import it. Or am I missing the location?
Atm I still have to manually import every single cert for every domain I secure with valet-linux.
My question aimed to have a as convenient solution as Mac users have with valet, and just configure it once to have it available for all future local development domains.
I don't want to expose the local site with `valet share` as I want to keep it completely local.
Maybe I'm misunderstanding something though...

**Comment by 6h4n3m** [comment]
This issue is still there, no idea why it was closed... Valet Linux doesn't include a certificate authority chain .PEM file and as such there's nothing we can import into Firefox to sort this issue out.
