### ISSUE TITLE
valet conflicts wireless

### ISSUE THREAD

**Issue by alaa-elmekkawy** [cpriego/valet-linux#189]
Hi,
I'm working in archlinux and valet was working perfectly and after some updates valet is not working while the wireless is connected and its working good when I turn the wireless off.

there is no any errors coming but the pages take a while to load and finally didn't open.

**Comment by alaa-elmekkawy** [comment]
the problem solved after removing network manager and reinstall it again and re install valet

**Comment by alaa-elmekkawy** [comment]
after some time the issue started again and I have to turn wireless off if I want to use valet any help?

**Comment by aeonagency** [comment]
I've quite a similar issue due to my VPN.

**Comment by besrabasant** [comment]
I had a similar issue due to entries in `resolv.conf`. Try following  the instructions in [https://askubuntu.com/questions/130452/how-do-i-add-a-dns-server-via-resolv-conf](https://askubuntu.com/questions/130452/how-do-i-add-a-dns-server-via-resolv-conf)

**Comment by antoninobonumore** [comment]
Similar problem, valet in startup overwrite my resolv.conf and everytime I have to restore it.
The problem seems to be related to the DNS resolution (connection is active, you can ping IP addresses).
