### ISSUE TITLE
Not working on ubuntu 18.04

### ISSUE THREAD

**Issue by dev-roshan** [cpriego/valet-linux#190]
I have done everything like in documentation. And I have create a new laravel project inside valet/Sites folder. When I run `valet path` , 
![3434](https://user-images.githubusercontent.com/24985932/51798077-bca3b580-2234-11e9-8d0f-4085369cb56c.png)
But when I open in browser
![44444](https://user-images.githubusercontent.com/24985932/51798084-e957cd00-2234-11e9-810e-fb18434d076e.png)

**Comment by indykoning** [comment]
I am running 18.04 as well without any problems. the problem seems to be nginx or php-fpm not running (properly). When i stop valet i get the exact same message. Maybe the log files can help point you in the right direction `~/.valet/Log/`

**Comment by CitizenBeta** [comment]
I'm having the same problem .valet/Log is empty.

**Comment by benjamenhogben** [comment]
what does `valet links` say?
what does `valet domain` say?

try placing a simple index.html into ~/.valet/sites/yoga

try placing `index.php` > with the contents `<?php echo 'hello world';` into ~/.valet/sites/yoga

**Comment by jmarcher** [comment]
What does `ping yoga.test` returns?

**Comment by yemilgr** [comment]
Hey happened the same to me. I changed the domain to localhost. Then i changed again to test and it works.
I dont know why ?
