### ISSUE TITLE
VPN and Valet

### ISSUE THREAD

**Issue by aeonagency** [cpriego/valet-linux#195]
So I just installed Valet and it works perfectly well I love it, however, whenever I turn my VPN on the DNS's get screwed up somehow and I can no longer access the local websites Valet serves without it. I'm getting the usual error: "Hmm. We’re having trouble finding that site.".

Whenever I'm not connected to my VPN in the resolv.conf file I have the nameserver 127.0.0.1

As soon as I connect to my VPN that gets deleted and replaced with the VPN's nameservers and the valet sites stop working.

Is there a way to make sure that both nameservers are there together and both work without killing each other?

Is there a way to make sure that I have both my VPN and Valet working properly?

The issue may only be the ports as well what ports are used by Valet, dnsmasq etc..? I can whitelist them in my VPN.

**Comment by aeonagency** [comment]
After a system restart I connected to my VPN and now the sites work even while I'm connected but whenever I make a new site it doesn't recognize that and I can't connect.

**Comment by aeonagency** [comment]
Closing this issue since this repo is no longer maintained.

**Comment by mushonnip** [comment]
I solved it by adding nameserver used by your VPNs provider in /opt/valet-linux/custom-nameservers
