### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by CitizenBeta** [cpriego/valet-linux#197]
It's been almost a year since the last commit, it doesn't look like this works on the latest version of Ubuntu. Is there a different fork that we should be using or is it advisable that we go back to using Homestead?

**Comment by the94air** [comment]
I don't think so. It has been dead for a long time. Most issues are handled by watcher participants.

**Comment by TheNodi** [comment]
I stopped using Valet (and working with PHP most of the time) and I don't have time to maintain this. 
I'm afraid this project isn't maintain anymore, I'm sorry.

@cpriego you should probably mark the repository as archived.

**Comment by the94air** [comment]
That's sad :crying_cat_face:. Maybe he can check if some else is willing to maintain the project by putting something in the `README.md`.

**Comment by stefano-b** [comment]
The creators of the original Laravel Valet seem to be open to add Linux support, if they find someone that takes the responsibility to manage this task and maintain this version: https://github.com/laravel/valet/issues/724

I see that there are some unattended PR here, if this fork is really abandoned and we cannot expect to receive more updates, maybe if someone is interested to contribute to a Linux version, it would be better to propose directly to the main project?

**Comment by dikiaap** [comment]
In the readme it is stated that the repo will be archived at the end of April 2019. @cpriego It is good to not archive the project as someone will not be able to comment to provide information to README or issues page about the fork or ask to maintain the repo.

**Comment by jmarcher** [comment]
I'm going to maintain this repo from now on, I hope I can solve all the issues valet-linux has with the help of you all! :smiley:
