### ISSUE TITLE
composer install valet succeed, but valet is command is unkown

### ISSUE THREAD

**Issue by D19cannon** [cpriego/valet-linux#198]
Hi guys,

I have seen quite a few solution to this issue that mainly had to do with adding the path to the bash profile. However, this didn't work for me.

Composer is literally able to any thing (problems what so ever). I installed valet successfully, but when I try to use it like> valet install. It returns that valet command is unknown.

Any idea why it is only with the valet command?

I am running a linux system: Deepin. I am fairly new to linux, used to work only on a macbook (where it is working fine btw) and now I am trying something new.

![DeepinScreenshot_select-area_20190323112820](https://user-images.githubusercontent.com/14916043/54864357-cf32fa80-4d5e-11e9-9d22-494525aeb1cf.png)

**Comment by benjamenhogben** [comment]
you probably need to add valet to your path

see https://github.com/cpriego/valet-linux/issues/35

**Comment by jmarcher** [comment]
Closing this issue as it seems to be resolved.
