### ISSUE TITLE
I would continue the development

### ISSUE THREAD

**Issue by jmarcher** [cpriego/valet-linux#199]
Hi @cpriego a while ago I forked your original repo (https://github.com/jmarcher/valet-linux) that worked only with Ubuntu and ported it to different distros. 

I use Valet on a daily basis, therefore I would hapily take control over this repo and will continue developing on it.

I believe we should not let this repo die!

**Comment by the94air** [comment]
Even better from supporting ubuntu only. That's great news.
cc @cpriego

**Comment by jmarcher** [comment]
I would not support Ubuntu only, I would add support keep support for all
distros possible.

Abdalla Arbab <notifications@github.com> schrieb am Sa., 13. Apr. 2019,
19:21:

**Comment by cca-bheath** [comment]
Hello @jmarcher,

I used to use your fork a bunch, before coming back to @cpriego.

I [branched](https://github.com/cca-bheath/valet-linux) and am working on building a release.  We could team up if you are interested?

**Comment by jmarcher** [comment]
@cca-bheath Yes that would be nice, but I want to wait and see if @cpriego could give us ownership over this repo. This way we do not lose all the actual installations.

**Comment by cpriego** [comment]
Thanks a lot for the answer. It's good to know the project will go on. I'm transfering the ownwership to @jmarcher hoping he will also receive help from @cca-bheath and any other users, specially on the testing side that can be quite time consuming given that many distros must be supported.

@jmarcher, the last approach I was exploring involved discarding the installation classes in PHP and replace them with a number of distro-specific scripts (considering also, service installation). Making it easier for anyone to contribute.

On the DNS side of things I was exploring using a separate instance of dnsmasq with a different local address (something like 127.0.10.10) and prepend that address on the resolv.conf, monitoring that file for changes (the real final path being obtained with `readlink -f`) and re-appending if needed. That would be the safest way (I could think of) to ensure tld resolution without breaking name resolution from the users with the advantage of being distro-agnostic.

**Comment by jmarcher** [comment]
Thanks @cpriego !
