### ISSUE TITLE
valet install: PHP Fatal error:  Uncaught ReflectionException: Class 0 does not exist in /root/.composer/vendor/illuminate/container/Container.php:741

### ISSUE THREAD

**Issue by waiylgeek** [cpriego/valet-linux#20]
```
root@waiylgeek:~# valet install
PHP Fatal error:  Uncaught ReflectionException: Class 0 does not exist in /root/.composer/vendor/illuminate/container/Container.php:741
Stack trace:
#0 /root/.composer/vendor/illuminate/container/Container.php(741): ReflectionClass->__construct('0')
#1 /root/.composer/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(0, Array)
#2 /root/.composer/vendor/cpriego/valet-ubuntu/cli/includes/helpers.php(58): Illuminate\Container\Container->make(0)
#3 /root/.composer/vendor/cpriego/valet-ubuntu/cli/Valet/Valet.php(141): resolve(0)
#4 [internal function]: Valet\Valet->Valet\{closure}(0, 'Valet\\PackageMa...')
#5 /root/.composer/vendor/illuminate/support/Arr.php(153): call_user_func(Object(Closure), 0, 'Valet\\PackageMa...')
#6 /root/.composer/vendor/illuminate/support/Collection.php(233): Illuminate\Support\Arr::first(Array, Object(Closure), Object(Closure))
#7 /root/.composer/vendor/cpriego/valet-ubuntu/cli/Valet/Valet.php(144): Illuminate\Support\Collection->first(Object(Closure), Object(Closure)) in /root/.composer/vendor/illuminate/container/Container.php on line 741

```

**Comment by TheNodi** [comment]
Why are you running valet as root user?

The package has been renamed from valet-ubuntu to valet-linux, you can try removing the old version and installing the new one:
```
composer global remove cpriego/valet-ubuntu
composer global require cpriego/valet-linux
```

**Comment by waiylgeek** [comment]
I've just run your code but still having the same exception thrown! Any idea?
Thanks.

**Comment by TheNodi** [comment]
Can you write your OS and php version?

Valet should not be run as root user, it uses sudo to escalate privileges, but it needs sudo-related information (original user, home directory, etc).

**Comment by waiylgeek** [comment]
Yes sure, here you go:

```
~# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

~# php -v
PHP 7.0.15-1+deb.sury.org~xenial+1
```

PS: I'm gonna try to install it as a regular user and see what happens

**Comment by TheNodi** [comment]
I've not been able to reproduce the issue using same OS and PHP versions, installing composer and valet as root user. Do you have others global composer packages that might have dependencies conflicts?

Did it work as a regular user?

**Comment by waiylgeek** [comment]
It did not work as a regular user and no I have no packages that might have any dependency conflict.

I'm going to use another OS and see what happens and get back to you to close the issue if the problem is on my end.

**Comment by TheNodi** [comment]
Yes, the error comes from this function:
```php
    function getAvailablePackageManager()
    {
        return collect([
            Apt::class,
            Dnf::class,
        ])->first(function ($pm) {
            return resolve($pm)->isAvailable();
        }, function () {
            throw new DomainException("No compatible package manager found.");
        });
    }
```
`$pm` in the `first` method callback is being set to 0, and results in a reflection exception trying to instantiate it.
I don't get why this is happening, I though it could have been an error while downloading the library, but it doesn't seems to be the case since you re-installed it. 
My second Idea was a dependences mismatch, since older versions of Laravel's Collections library used to set the key as first parameter instead of the value (this resulting in $pm set to the index of the code), but you said dependences where fine.

To be extra sure, can you give me the output of `composer global show`?

I think that Laravel's Collection change happened on version 5.3, I'm going to double check and probably bump a composer dependence up a version (from 5.2 to 5.3).

**Comment by waiylgeek** [comment]
Yes sure, here's the output of `composer global show`:

```
container-interop/container-interop 1.2.0   Promoting the interoperability of container objects (DIC, SL, etc.)
cpriego/valet-linux                 v2.0.6  A more enjoyable local development experience for Linux.
danielstjules/stringy               1.10.0  A string manipulation library with multibyte support
doctrine/inflector                  v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
guzzlehttp/guzzle                   5.3.0   Guzzle is a PHP HTTP client library and framework for building RESTful web service clients
guzzlehttp/ringphp                  1.1.0   Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                  3.0.0   Provides a simple abstraction over streams of data
illuminate/container                v5.1.41 The Illuminate Container package.
illuminate/contracts                v5.1.41 The Illuminate Contracts package.
illuminate/support                  v5.1.22 The Illuminate Support package.
laravel/envoy                       v1.0.25 Elegant SSH tasks for PHP.
laravel/homestead                   v2.1.8  A virtual machine for web artisans.
laravel/installer                   v1.3.4  Laravel application installer.
mnapoli/silly                       1.5.1   Silly CLI micro-framework based on Symfony Console
nategood/httpful                    0.2.20  A Readable, Chainable, REST friendly, PHP HTTP Client
php-di/invoker                      1.3.3   Generic and extensible callable invoker
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/log                             1.0.2   Common interface for logging libraries
react/promise                       v2.2.1  A lightweight implementation of CommonJS Promises/A for PHP
symfony/console                     v2.8.17 Symfony Console Component
symfony/debug                       v3.0.9  Symfony Debug Component
symfony/polyfill-mbstring           v1.3.0  Symfony polyfill for the Mbstring extension
symfony/process                     v2.8.17 Symfony Process Component
tightenco/collect                   v5.4.12 Collect - Illuminate Collections as a separate package.

```

Thank you

**Comment by TheNodi** [comment]
You have the correct version of `tightenco/collect` but there's also a lower version of `illuminate/support` (5.1) that might be overriding it. You can try to update the support package to at least version 5.3 or remove it and see if it helps.

You can check why `illuminate/support` is installed by running:
```
composer global why illuminate/support
```

I've updated composer.json to fix some dependencies requirements in PR #21, it's been merged but not released yet. You can try it out with the command:
```
composer global require cpriego/valet-linux:dev-master
```
I don't know if it'll help because you actually have the right version of `tightenco/collect`.

**Comment by waiylgeek** [comment]
That fixed the problem, now I can run `valet` with no problem, it displays all the various options I have. But when I run `valet install` it throws the following exception: 

```
  [RuntimeException]                    
  Valet home directory is inside /root  
                                       
```
Any ideas?

Thanks.

**Comment by TheNodi** [comment]
It happens when you're running valet as the root user instead of your regular user. 

Or if sudo is not passing the home environment variable correctly (it shouldn't be the case for Ubuntu).

**Comment by cpriego** [comment]
Please update to the latest version. Also please install Valet as a regular user is not meant to be run as root.

**Comment by waiylgeek** [comment]
Fixed, thanks.
