### ISSUE TITLE
php-fpm path in openSUSE

### ISSUE THREAD

**Issue by stefano-b** [cpriego/valet-linux#200]
The path for `php-fpm` in openSUSE is as follows (for php 7+ versions):

`/etc/php7/fpm/php-fpm.d/`

This should be added in `/valet-linux/cli/Valet/PhpFpm.php`, where other distros paths are listed.

Please note that while other distros use a specific version directory (ex. `/php7.2/`), openSUSE uses only the major version number, so the correct path has `/php7/`.

**Comment by jmarcher** [comment]
@stefano-b Can you make a PR for this change?

**Comment by stefano-b** [comment]
Yes, I can add this, but please note that I've not reviewed all the code for this project, and I'm not sure if it should added or udpated somewhere else, or if there should be other considerations to make.

**Comment by lifeofdan** [comment]
I made a PR for this issue and it has been accepted. So this issue should be closed.
