### ISSUE TITLE
Update releases in packagist

### ISSUE THREAD

**Issue by rodrigopedra** [cpriego/valet-linux#209]
Hi @jmarcher ,

Great to see this repo getting updates again, I tried updating using valet update and noticed the version keeps at 2.0.24.

I went to packagist and saw that the versions there are not updated. I imagine @cpriego must update the github hook there or give you permission to do so.

I noticed also you have a fork, what are the plans? Should I migrate to use your fork, or will you be the new maintaner over here?

Thanks, if there is anything I can help, let me know, I do not have many knowledge on the low-level stuff valet requires but I will be glad to help with any other stuff you need.

**Comment by jmarcher** [comment]
Yes I'm still trying to communicate with him per email.

I need him to add me as a maintainer as the actual repo in packsgist is
using an old authentication and won't update automatically.

Rodrigo Pedra Brum <notifications@github.com> schrieb am Fr., 3. Mai 2019,
18:22:
