### ISSUE TITLE
valet sites not resolving in Chrome OS

### ISSUE THREAD

**Issue by nbolink** [cpriego/valet-linux#215]
I''m trying to get Valet to work on Chrome OS with Linux Apps enabled (Cloudready v74). Valet installs fine and everything seems to work except that the site's aren't resolving. I'll get the error 'The site can't be reached' and a ping to the URL will fail.

**Comment by jmarcher** [comment]
Can you confirm that dnsmasq is installed and running? Did you got any
error message from the install routine?

nbolink <notifications@github.com> schrieb am Do., 20. Juni 2019, 02:14:

**Comment by nbolink** [comment]
See my running services:
_nbolink@penguin:~$ sudo service --status-all
 [ - ]  cgroupfs-mount
 [ + ]  dbus
 [ + ]  dnsmasq
 [ + ]  docker
 [ - ]  hwclock.sh
 [ - ]  kmod
 [ + ]  networking
 [ + ]  nginx
 [ + ]  php7.2-fpm
 [ + ]  procps
 [ - ]  rsync
 [ - ]  ssh
 [ - ]  sudo
 [ - ]  x11-common_

The install routine went without any error messages.
_nbolink@penguin:~$ valet status
Php7.2-fpm is running...
Nginx is running..._

**Comment by jmarcher** [comment]
You said that a ping to the URL will fail but what does this means? What error are you seeing?
`Name or service not known` ?

**Comment by nbolink** [comment]
correction it looks like that a PING resolves:
_blog.test (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.028 ms_

but a browser request fails:
_This site can’t be reached blog.test’s server IP address could not be found.
Try running Connectivity Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN_

**Comment by jmarcher** [comment]
A quick google search gave me hints that this error may be related with Chrome's DNS cache

**Comment by nbolink** [comment]
You're right, the chrome cache is the problem. I've tried to flush it but without success. 
So I installed Firefox and the valet sites are resolving and can be reached on Chrome OS.
