### ISSUE TITLE
Nginx: Fix to “405 Not Allowed”

### ISSUE THREAD

**Issue by luisfmelo** [cpriego/valet-linux#22]
Hi! 

All my API endpoints which are **Post** result in a 
`MethodNotAllowedHttpException in RouteCollection.php line 233:`

So, after my research, I think the error is due to nginx. 

Anyone knows how to solve this issue?

**Comment by cpriego** [comment]
It looks like a problem in either your routes file or client side not using the right method.
Could you post a sample of the client request and route file section?

Are you using the api.php or web.php file?

**Comment by luisfmelo** [comment]
in routes/api.php

```
Route::post('/test', function(){
    return "everything seems fine";
});
```

trying to access integrations.dev/api/test

and I receive: 
``MethodNotAllowedHttpException in RouteCollection.php line 233:``

**Comment by cpriego** [comment]
How are you testing the endpoint? I just tried your example with postman but could not reproduce it. I can only see that exact error when using the wrong HTTP verb.

![selection_005](https://cloud.githubusercontent.com/assets/6462826/23144266/0235b4de-f78c-11e6-8152-658a2fe81871.png)


![selection_003](https://cloud.githubusercontent.com/assets/6462826/23144232/c5094026-f78b-11e6-9145-0f8688096ad9.png)

![selection_004](https://cloud.githubusercontent.com/assets/6462826/23144235/c8ec8112-f78b-11e6-91c6-feab9c9e0d84.png)

**Comment by cpriego** [comment]
Please update to the latest version.

**Comment by luisfmelo** [comment]
I updated but now, when I make `valet install`, this appear:
`PHP Fatal error:  Cannot redeclare info() (previously declared in /home/luisfmelo/.composer/vendor/mpociot/documentarian/includes/helpers.php:10) in /home/luisfmelo/.composer/vendor/cpriego/valet-linux/cli/includes/helpers.php on line 23`

**Comment by luisfmelo** [comment]
I updated but now nginx is not starting:

`$ valet status `
Php7.0-fpm is running...
Nginx is stopped...

**Comment by luisfmelo** [comment]
Ok, it appears that /etc/nginx/nginx.conf had one semi colon thet it should not be there.

But, POST requests are still not working.

**Comment by cpriego** [comment]
Thanks for pointing out the double semicolon, it is now fixed. Does the problem show up in Laravel Homestead.

**Comment by luisfmelo** [comment]
I don't use homestead... 

But the issue with POST, it is something in valet or within my application?

**Comment by cpriego** [comment]
I'm almost sure it is with the application, that's the reason I asked you to test it in Homestead. I don't know the tool you used to test the API but as you can see in my screenshots it works just fine in my Valet installation.

**Comment by cristianofromagio** [comment]
`MethodNotAllowedHttpException` indicates that a route doesn't exist for the HTTP method you are requesting. If you have a `POST` route set up, you can't access it directly from the browser, since it performs a `GET` request. If you can't reproduce the test as shown by @cpriego, you can simply set up a form on a `GET` route forwarding to the `POST` route using the action method (remember to include `{{ csrf_field() }}` inside form tag, [more info here](https://laravel.com/docs/5.4/csrf#csrf-introduction)).

**Comment by cpriego** [comment]
Closed by inactivity
