### ISSUE TITLE
Problem with static files

### ISSUE THREAD

**Issue by tpharaoh** [cpriego/valet-linux#220]
I am serving a site, with js and css compiled into public/build

They get returned with a http 500, and the following error:
2019/07/14 01:38:29 [error] 2694#2694: *152 rewrite or internal redirection cycle while processing "/home/username/.config/composer/vendor/cpriego/valet-linux/server.php", client: 127.0.0.1, server: , request: "GET /build/js/app.js HTTP/1.1", upstream: "fastcgi://unix:/home/username/.valet/valet.sock", host: "time.test:8888", referrer: "http://time.test:8888/"

**Comment by jmarcher** [comment]
It looks like a misconfiguration on your side
