### ISSUE TITLE
Unable to upload files with size more than 5kB

### ISSUE THREAD

**Issue by vishytk** [cpriego/valet-linux#222]
I am getting the same error (500) while trying to upload files more than 5kB size.

Valet = 2.1.8 (2.1.7)
Fedora 30

php.ini settings are fine and works with "php artisan serve"
only issue with valet/nginx

valet.conf has client_max_body_size 128M;

**Comment by jmarcher** [comment]
Where are you locating your config, please post a full description of the errors you get.

What is the output of: `/usr/bin/nginx -t` (or where your ngnix is located)

**Comment by vishytk** [comment]
Have a user update page and in that page when someone uploads and image to update profile picture which is more than 5kB, this error is thrown "**500 Internal Server Error**"

Environment:
Fedora 30, 64-bit
Valet: 2.1.8

Initially, thought it was some code issue, but later realised that it was an issue with nginx. 

When I run "php artisan serve" everything works fine according to php.ini settings (related to file upload size)

output of "nginx -t"
nginx: [warn] could not build optimal types_hash, you should increase either types_hash_max_size: 2048 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by jmarcher** [comment]
Can you confirm that `/etc/ngnix/ngnix.conf` is including `~/.valet/Ngnix/*` ?

php artisan server does not use ngnix, therefore is not a point of comparison

**Comment by vishytk** [comment]
I mentioned about "php artisan server" to suggest and rule out php.ini settings.

cat /etc/nginx/nginx.conf
user 'vishy' 'vishy';
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
    # multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    # server_tokens off;

    gzip on;
    gzip_disable "msie6";
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;

    gzip_types
    application/atom+xml
    application/javascript
    application/json
    application/rss+xml
    application/vnd.ms-fontobject
    application/x-font-ttf
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/opentype
    image/svg+xml
    image/x-icon
    text/css
    text/plain
    text/x-component;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
    include /home/vishy/.valet/Nginx/*;
}

**Comment by jmarcher** [comment]
can you also show me the output of `cat /home/vishy/.valet/Ngnix/valet.conf`?

**Comment by vishytk** [comment]
cat .valet/Nginx/cmsapp.test 
server {
    listen 80;
    server_name cmsapp.test www.cmsapp.test *.cmsapp.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name cmsapp.test www.cmsapp.test *.cmsapp.test;
    root /;
    charset utf-8;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    ssl_certificate /home/vishy/.valet/Certificates/cmsapp.test.crt;
    ssl_certificate_key /home/vishy/.valet/Certificates/cmsapp.test.key;

    location / {
        rewrite ^ /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log /home/vishy/.valet/Log/nginx-error.log;

    error_page 404 /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/home/vishy/.valet/valet.sock;
        fastcgi_index /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php;
    }

    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 88;
    server_name cmsapp.test www.cmsapp.test *.cmsapp.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php last;
    }

    access_log off;
    error_log /home/vishy/.valet/Log/nginx-error.log;

    error_page 404 /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/home/vishy/.valet/valet.sock;
        fastcgi_index /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /home/vishy/.config/composer/vendor/cpriego/valet-linux/server.php;
    }

    location ~ /\.ht {
        deny all;
    }
}

**Comment by jmarcher** [comment]
The format is a little weird here on GitHub but I can not see any problems.

What I do not get is why do you have that much config for valet, are you parking a folder with your projects? or are you adding them manually?

**Comment by vishytk** [comment]
I have a few projects added manually and a parked folder.

**Comment by jmarcher** [comment]
If they live all under the same folder there is no need to add them manually you could just park the folder. For example if you have something like

```
~/Projects
   - blog
   - website
   - thing
```

and do a `valet park` on `~/Projects` you should have out of the box the following domains available:  `blog.test`, `website.test` and `thing.test`

**Comment by vishytk** [comment]
I have one folder like Projects and few other individual project folders from different locations on the disk.

**Comment by jmarcher** [comment]
Can you please just test this:
Replace your cmsapp.conf with this:
```
server{
    client_max_body_size 50M;
}
```

Park your projects folder with `valet park` and each individual projects (those outside the project's folder) `valet link`

**Comment by vishytk** [comment]
removed all links, and the parked folder and add link for just one project folder and tried with client_max_body_size 50M; 
still getting error.

**Comment by jmarcher** [comment]
Can you post what you get on your logs?

**Comment by vishytk** [comment]
unfortunately nothing coming to logs. will record and share the link

**Comment by vishytk** [comment]
https://www.youtube.com/watch?v=0xQGVXj_XtQ

**Comment by jmarcher** [comment]
Can you test this again without any config on your valet.conf?

**Comment by vishytk** [comment]
The issue has been resolved. The problem was with permissions on "/var/lib/nginx" and "/var/lib/nginx/tmp/" folders. Both these folders were having following permissions:

# ls -ld /var/lib/nginx
drwxrwx---. 7 nginx root 4096 Aug 14 01:17 /var/lib/nginx

# ls -ld /var/lib/nginx/tmp
drwxrwx---. 7 nginx root 4096 Aug 14 01:17 /var/lib/nginx/tmp

So, my user (vishy) could not write to the tmp folder at all.

Changed the permissions to 
drwxrwxr-x. 7 nginx root 4096 Aug 14 02:32 /var/lib/nginx
drwxrwxr-x. 7 nginx root 4096 Aug 14 02:32 /var/lib/nginx/tmp

**Comment by jmarcher** [comment]
Nice!
