### ISSUE TITLE
resolv.conf linked to script

### ISSUE THREAD

**Issue by nielspeen** [cpriego/valet-linux#223]
My initial install of valet worked flawlessly, but subsequent runs of _valet install_ appear to link  /etc/resolv.conf to the /opt/valet-linux/valet-dns script and kill my connection as a result.

Looking for a cause, I found this function which does indeed link the script to the resolv.conf.

```php
private function _mergeDns()
    {
        $optDir  = '/opt/valet-linux';
        $script  = $optDir.'/valet-dns';

        $this->pm->ensureInstalled('inotify-tools');
        $this->files->remove($optDir);
        $this->files->ensureDirExists($optDir);
        $this->files->put($script, $this->files->get(__DIR__.'/../stubs/valet-dns'));
        $this->cli->run("chmod +x $script");
        $this->sm->installValetDns($this->files);
        
        if ($this->files->exists($this->rclocal)) {
            $this->files->restore($this->rclocal);
        }
        
        $this->files->backup($this->resolvconf);
        $this->files->unlink($this->resolvconf);
        $this->files->symlink($script, $this->resolvconf);

        return true;
    }
```

If I then manually execute /opt/valet-linux/valet-dns (or /etc/resolv.conf) it fixes the situation.

This approach of temporarily overwriting the resolv.conf with a script seems somewhat unusual to me, but more importantly I can't figure out why it's failing for me on subsequent _valet install_ runs.

I've tried running _valet uninstall_ before re-running _valet install_ but that did not help.

**Comment by jmarcher** [comment]
You should run `valet install` only one time.

**Comment by marvinosswald** [comment]
For me `/etc/resolv.conf` gets linked to `/opt/valet-linux/resolv.conf` periodically, which kills the stub interface of systemd-resolved (since systemd-231) which i need for my vpn.
