### ISSUE TITLE
Doesn't configure other php-fpm versions correctly?

### ISSUE THREAD

**Issue by riher** [cpriego/valet-linux#226]
Hey, first of all thanks for this amazing project!

One issue: When I use the default PHP version, everything works fine. But then I wanted to switch to another version (7.2) and I found that valet uses it correctly, but failed to update the php-fpm configuration as it did with the default version.

When I copied valet.conf from php/php-fpm.d to php72/php-fpm.d it works.

Is this a bug or just something that can't be done automatically? (As I installed php72-fpm AFTER valet-linux)

Cheers

**Comment by jmarcher** [comment]
What do you mean by switch php versions? Valet does not support php version switching

**Comment by riher** [comment]
My version of valet (2.1.8) offers the `valet use` command which *almost* works perfectly.

**Comment by jmarcher** [comment]
Oh yeah, I never used it, maybe we could ping @indykoning 

He is the one that originally made the PR

**Comment by indykoning** [comment]
It should do this automatically if your distro is in a list of config paths. And reading [that list](https://github.com/cpriego/valet-linux/blob/master/cli/Valet/PhpFpm.php#L204) i cannot determine your distro so automatically doing this will not work until the correct path is added to it.

what linux distribution do you have and where should the file be placed?

**Comment by riher** [comment]
@indykoning Thanks for the quick response. This sounds very plausible (I'm indeed on Arch) and I'll try it out later. :+1:

**Comment by jmarcher** [comment]
@riher is your issue solved?

**Comment by riher** [comment]
Ah, sorry, forgot to check this again.
Unfortunately, it doesn't quite work because of permissions:
```
PHP Warning:  file_put_contents(/etc/php72/php-fpm.d/valet.conf): failed to open stream: Permission denied in /home/ricardo/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Filesystem.php on line 176
PHP Warning:  chown(): No such file or directory in /home/ricardo/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Filesystem.php on line 373
```

**Comment by riher** [comment]
So, the **install** function in `valet-linux/cli/Valet/PhpFpm.php` tries to ensure /var/log exists and tries to create several files in the php-fpm directory (which are probably all owned by root) as the current user. No wonder this doesn't work. My suggestions would be to modify this function to use **sudo** by default.

As do the systemd calls, so it's not like valet didn't use sudo anyway. Half the codebase actually seems to assume that everything's run as a superuser, which is a bit strange. Compare https://github.com/cpriego/valet-linux/issues/229

I'll write a pull request for this matter if you agree that's the right course.

**Comment by indykoning** [comment]
If that does fix it for you you can always try creating a pull request for it.

**Comment by jmarcher** [comment]
Send a PR so we can review it.
