### ISSUE TITLE
Magento Driver doesn't work correctly

### ISSUE THREAD

**Issue by AboElnoor** [cpriego/valet-linux#227]
After updating valet to the latest version my Magento website doesn't work fine.
**What happened?**
![FireShot Capture 025 - Dashboard _ Magento Admin - nobaj test](https://user-images.githubusercontent.com/16509141/63227001-f5f83e80-c1e1-11e9-9d74-510291698c35.png)

**Chrome Console screen capture:**
![Screenshot-20190818175411-1354x230](https://user-images.githubusercontent.com/16509141/63227012-17592a80-c1e2-11e9-8b83-b5fecf2a0df7.png)
I've searched about the differences between my previous valet version and the updated version and successfully found that everything works fine after reverting this commit
https://github.com/cpriego/valet-linux/commit/680b7e13e4b098e56b66bd0614b86bcffc6ea911

Notes:

1. My website Magento version is 2.3.2.
2. This issue doesn't appear in a fresh Magento installation (Version 2.3.1) maybe version changes!
3. The problem totally solved after removing this commit changes.

**Comment by jmarcher** [comment]
Can you do a PR with a Fix?
Can you confirm that this problem is not a problem with your specific version of magento

**Comment by AboElnoor** [comment]
> Can you do a PR with a Fix?

I'll do it ASAP

> Can you confirm that this problem is not a problem with your specific version of magento
I've checked and yes, this problem is related to the latest version of Magento (2.3.2) It didn't exist on the previous version (2.3.1)
