### ISSUE TITLE
Add support for the Void Linux package manager - xbps 

### ISSUE THREAD

**Issue by zeddyblue** [cpriego/valet-linux#228]
I'd like to help add support for the Void Linux package manager. 

[Void Linux Homepage](https://voidlinux.org/)
[XBPS Documentation ](https://voidlinux.org/usage/xbps/)

Just not sure where to start. Can you point me in the right direction? What needs to be done?

**Comment by jmarcher** [comment]
I'm not familiar with Void Linux but what you need to keep in mind is:

ServiceManagers: Which service manager does Void uses? systemctl? 
PackageManagers: Just implement the Valet\Contracts\PackageManager contract and take a look how the other package managers implement each method to get an idea.

**Comment by zeddyblue** [comment]
I've had a look through what needs to be done. Void uses runit. Beyond my capabilities at the moment, so I will close this for now.
