### ISSUE TITLE
Apt was unable to install preferedversion

### ISSUE THREAD

**Issue by codepuncher** [cpriego/valet-linux#229]
Linux Mint 18.2 Sonya (Ubuntu 16.04.1)
Valet v2.1.8
PHP 7.3

When trying to change PHP version (e.g. `valet use 7.2`), I get the following output:

```bash
➜ valet use 7.2  
Changing php-fpm version...
This does not affect php -v.
Stopping php7.3-fpm...
Disabling php7.3-fpm...
Php7.3-fpm has been disabled
Php7.3-fpm was already disabled
[php7.2-fpm] is not installed, installing it now via Apt... 🍻
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

Enabling php7.3-fpm...
Php7.3-fpm has been enabled
Changing version failed

In Apt.php line 74:
                                           
  Apt was unable to install [php7.2-fpm].  
                                           

use [<preferedversion>]
```

As you can see, I don't have that PHP version installed.
Although it attempts to install it, it can't.
Given that part of the error is 
```
[php7.2-fpm] is not installed, installing it now via Apt... 🍻
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```
I can only assume that the command needs to escalate the permissions.
Or is it possible that it's trying to install the wrong package name? (e.g. It's doing `php7.2-fpm` instead of `php7.2`?

I've also tried installing `php7.2` (using `sudo apt-get install php7.2 php7.2-cli php7.2-curl php7.2-mbstring php7.2-xml php7.2-zip`) prior to running `valet use 7.2`, but it still can't switch and I get the same error.

With `php7.2` already being installed and I still get the error `[php7.2-fpm] is not installed, installing it now via Apt... 🍻` I suspect it's looking for incorrect package names.

Anything I can do to help fix/test this?

Cheers

**Comment by jmarcher** [comment]
@codepuncher Can you try something for me? please on your valet installation folder look for `cli/Valet/PackageManagers/Apt.php` line 71 change `$this->cli->run` to `$this->cli->runAsUser`

And give it a try, and let me know what you get for an output

**Comment by codepuncher** [comment]
`➜ vim ~/.composer/vendor/cpriego/valet-linux/cli/Valet/PackageManagers/Apt.php`
```diff
    public function installOrFail($package)
    {
        output('<info>['.$package.'] is not installed, installing it now via Apt...</info> 🍻');

-          $this->cli->run(trim('apt-get install -y '.$package), function ($exitCode, $errorOutput) use ($package) {
+          $this->cli->runAsUser(trim('apt-get install -y '.$package), function ($exitCode, $errorOutput) use ($package) {
            output($errorOutput);
            throw new DomainException('Apt was unable to install ['.$package.'].');
        });
    }
```
```
➜ valet use 7.2                                                               
Changing php-fpm version...
This does not affect php -v.
Stopping php7.3-fpm...
Disabling php7.3-fpm...
Php7.3-fpm has been disabled
Php7.3-fpm was already disabled
[php7.2-fpm] is not installed, installing it now via Apt... 🍻
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

Enabling php7.3-fpm...
Php7.3-fpm has been enabled
Changing version failed

In Apt.php line 74:
                                           
  Apt was unable to install [php7.2-fpm].  
                                           

use [<preferedversion>]
```
This is just to show I do have it installed:
```
➜ /usr/bin/php7.2 --version
PHP 7.2.22-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.22-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

Hope that helps!

**Comment by indykoning** [comment]
php7.2 is the command line php, however php7.2-fpm is ran as a service for websites.
If you install php7.2-fpm manually it should see that it is already installed and switch php versions.

If the apt install isn't running as user it shouldn't get a "permission denied"
Have you had this before while running `valet install`?

**Comment by codepuncher** [comment]
I just installed 7.2-fpm `sudo apt-get install php7.2-fpm` and I still have the same issue. I have reverted the code change above, though.

Haven't had any issues with `valet install`. Any ideas what else is going on?

**Comment by indykoning** [comment]
If `php7.2-fpm` is installed already it should not try to install it, but instead enable it.
When you run `service --status-all | grep "php.*-fpm"` does `php7.2-fpm` show up?
Does php7.2-fpm get returned when you run `dpkg -l php7.2-fpm | grep '^ii' | sed 's/\s\+/ /g' | cut -d' ' -f2`?
The above is how it checks if the package is installed if your system uses apt as package manager.

**Comment by mepsd** [comment]
In case if someone tries with php 8 or 7 make sure to give 8.0/ 7.0 
`valet use 8.0
valet use 7.0`

**Comment by pintu2581** [comment]
> 

It working fine.

**Comment by parvez-git** [comment]
I found the solution on ubuntu 22.04 using the command:
`valet use 7.0 --update-cli`

**Comment by a-di-ez** [comment]
> I found the solution on ubuntu 22.04 using the command: `valet use 7.0 --update-cli`

The "--update-cli" option does not exist.
