### ISSUE TITLE
[Sticked] DNS issue after upgrading Ubuntu 19.04 to 19.10

### ISSUE THREAD

**Issue by egdavid** [cpriego/valet-linux#236]
I've recently upgraded my workstation to Ubuntu 19.10 and since then I had no internet connection after (re)installing valet.
I found out that dnsmasq was the problem and there is a workaround for those who have encountered the same issue.

Edit **/etc/dnsmasq.conf**:
```
resolv-file=/etc/dnsmasq.resolv.conf
listen-address=127.0.0.1
```

Add DNS servers of your choice in **/etc/dnsmasq.resolv.conf**
```
nameserver 208.67.222.222
nameserver 208.67.220.220
```

Restart dnsmasq
`sudo service dnsmasq restart`

This allows me to use my ***.test** domains while having a fully functional internet access.

**Comment by jmarcher** [comment]
I've pinned this issue as it may help any user that updated Ubuntu.

**Comment by willvincent** [comment]
Not having any issues getting out to the internet, but I am unable to navigate to other machines on my local network by name -- oddly just in the browser, it complains of being unable to find an IP address, but from the cli I have no issue. No issues whatsoever _before_ installing valet-linux, so it's definitley related... and seems akin to this somewhat
