### ISSUE TITLE
Valet Points to Apache2 Web Directory | Laravel not showing.

### ISSUE THREAD

**Issue by anburocky3** [cpriego/valet-linux#238]
I have followed every instruction mentioned on the [documentation](https://cpriego.github.io/valet-linux/).

Looks like the installation went good. But it doesn't works.

**Here is my example:**
1. Created an laravel fresh project by: `laravel new laravel6`
2. Entered into that directory by: `cd laravel6` and entering `php artisan serve` works as expected. but when i visit laravel6.test it points to my apache2 web directory.

When entering `laravel6.test` it should point to my laravel6 project right?

Have i done anything wrong?

**Comment by anburocky3** [comment]
**Update:** I look at the status of the valet and it showed, `nginx stopped.`

So i stopped `apache2` and started `nginx` server. But `laravel6.test` points to 404 error.?

**Comment by jmarcher** [comment]
First you need to disable the apache service, it will conflict with ngnix at the 80 port.

Secondly do you linked the path to laravel6 or did you park the parent folder of laravel6?

**Comment by anburocky3** [comment]
I stopped apache2 service and tried it. But it says `404 not found` Do i need to configure separately for nginx sites?

**Comment by jmarcher** [comment]
How are you linking the site?

Are you linking the path to your project or are you parking the whole root folder of your projects?

**Comment by jmarcher** [comment]
@anburocky3 Can you give me more input on this? I do not like to have open issues for longer than one week.

**Comment by anburocky3** [comment]
I will uninstall apache2 and retry it once again. Will come up with details.

**Comment by jmarcher** [comment]
You do not need to uninstall apache (well if you do not need it just do it), you could just make apache use another port.
