### ISSUE TITLE
Valet use command with PHP-FPM and Manjaro Linux

### ISSUE THREAD

**Issue by thomaslawton91** [cpriego/valet-linux#239]
Hi I'm currently using this tool on my dev machine which is running Manjaro Linux, an Arch based distro. So far everything is working although I have had to make some slight manual updates to my system to get it going.

As discussed in issue #226 the command `valet use` is not looking for the right folders for Arch based distros. It is suggested to use `'/etc/php'.str_replace('.', '', $this->version).'/php-fpm.d', // Arch` to fix this and, as the author of the issue stated, though it does correctly point to the folder, there are ownership issues from that point. 

I've looked further into this and it looks like something I'd be able to fix but wanted to first make sure that it's not something that's currently being worked on and also say that this would be a newer experience for me (contributing) and would appreciate a little guidance on how to do so. 

Currently I have copied the `.../php-fpm.d/valet.conf` manually into my `/etc/php71/php-fpm.d` folder and have confirmed that it works just fine but I'd assume there are other users who would find this a great tool to be able to use.

Thanks so much for the project and to the new maintainer for keeping it going, it's very appreciated as I started with a fully self-configured env then docker and this is currently running very nicely and feels much better. 

Please let me know how I can proceed!

**Comment by jmarcher** [comment]
I'll see further into this when I have the time.

**Comment by thomaslawton91** [comment]
Sounds good. I did find a very simple solution to this while picking through the files of my local installation. It looks like the `use` command was not in the array of sudo commands in the valet executable. I just added `use` as one of those commands and it's working very nicely.

**Comment by jmarcher** [comment]
v2.2.3 released
