### ISSUE TITLE
valet app keeps giving 404 not found

### ISSUE THREAD

**Issue by umersurkhailas** [cpriego/valet-linux#240]
I have reinstalled and restarted everything but it still keep displaying 404, now pulling my hair out. a help will be really appreciated. screenshots are attached, 

p.s 
used both park the parent directory or link the project directory, tried both,

![Screenshot from 2019-11-28 19-08-43](https://user-images.githubusercontent.com/56860234/69812906-ed68c880-1212-11ea-83fb-ca2524aec5eb.png)
![Screenshot from 2019-11-28 19-08-52](https://user-images.githubusercontent.com/56860234/69812907-ed68c880-1212-11ea-8828-665733df6093.png)

**Comment by jmarcher** [comment]
I need more information. What kind of project are you trying to use with valet? Can you show the folder/file structure of your testapp?

In case you are using a valid project, do the following
`
cd /home/shaibiii/code
valet park
cd testapp
valet unsecure
`
Try to use valet without https and tell me what happens.

**Comment by umersurkhailas** [comment]
@jmarcher .. I am running laravel app on Ubuntu 18, 
code is my parent directory which has folder named as 'testapp' and has laravel app in it
I have 'valet park' code folder(parent folder), used 'valet unsecure' after 'cd testapp' used 'valet unsecure'. following is the command sequence
1. valet park 
2. cd testapp
3. valet unsecure

But still no luck, having the same issue.

Also tried 
1. cd testapp
2. valet link
3 valet unsecure

Still no luck

**Comment by umersurkhailas** [comment]
My bad, I figured it out. problem is fixed
I used "composer global require cpriego/valet-linux" with sudo and it was causing the issue, removed everything and then used composer require without sudo, and then ran "valet install" 
after using park, got it working

Guys, please don't use sudo command while installing or kittens could die.

You can close the issue
