### ISSUE TITLE
Valet install throws PHP warning message.

### ISSUE THREAD

**Issue by webtamizhan** [cpriego/valet-linux#247]
<pre>PHP Warning:  Cannot bind an instance to a static closure in /home/user/.composer/vendor/mnapoli/silly/src/Application.php on line 92

<font color="#F4BF75">In Application.php line 98:</font>
<span style="background-color:#F92672"><font color="#F8F8F2">                                                                    </font></span>
<span style="background-color:#F92672"><font color="#F8F8F2">  Impossible to call the &apos;install&apos; command: NULL is not a callable  </font></span>
<span style="background-color:#F92672"><font color="#F8F8F2">                                                                    </font></span>

<font color="#F4BF75">In Invoker.php line 57:</font>
<span style="background-color:#F92672"><font color="#F8F8F2">                          </font></span>
<span style="background-color:#F92672"><font color="#F8F8F2">  NULL is not a callable  </font></span>
<span style="background-color:#F92672"><font color="#F8F8F2">                          </font></span>

</pre>

OS: Ubuntu 18.04.3 LTS

**Comment by muhammetsait** [comment]
I had this after upgrading to PHP 7.4. I worked around it by removing `static` in `valet.php` :confused: 

Valet v2.2.3
Silly 1.7.2
symfony/console v4.4.1

**Comment by jmarcher** [comment]
Solved in v2.2.4
