### ISSUE TITLE
How do you handle multi-store in Magento?

### ISSUE THREAD

**Issue by kieran85james** [cpriego/valet-linux#250]
I am struggling to set up multi-store site in Magento 2 (currently 2.3.3).

How would I go about getting this set up with valet-linux?

**Comment by jmarcher** [comment]
What do you mean by multi-store? Sorry I'm not familiar with Magento

**Comment by kieran85james** [comment]
Similar to multi-site you can see the differences here: https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_over.html

With Magento the multi-store is all set up but I'm struggling for valet-linux to apply the correct theme.

With apache in the .htaccess you would do something like:
```
    SetEnvIf Host example.* MAGE_RUN_CODE=store_code
    SetEnvIf Host example.* MAGE_RUN_TYPE=store
```
Regarding valet-linux I have no idea how to go about it. And can't find much on it either. I have found https://github.com/weprovide/valet-plus/issues/77 for valet-plus but not sure if that is valid for valet-linux. I have tried some of the suggestions but none have worked for me.

**Comment by jmarcher** [comment]
You could create new links with `valet link` after that you can use the custom nginx config file, does this work for you?
