### ISSUE TITLE
valet secure sitename/ adds the / to the test url

### ISSUE THREAD

**Issue by rgb-one** [cpriego/valet-linux#252]
`valet secure` adds the leading `/` of a directory name to the test url.

```
Restarting nginx...
The [sitename/.test] site has been secured with a fresh TLS certificate.
```

Is this a feature?

**Comment by jmarcher** [comment]
Can not reproduce on my machine

**Comment by rgb-one** [comment]
When a directory name gets auto-completed it has a trailing /. When I run `valet secure directoryname/` the resulting url has the directoryname and the / in it eg. `directoryname/.test`.

Did you try something like `valet secure example/`?

**Comment by jmarcher** [comment]
It depends on which terminal you are using, mine does not add a trailing /, I also always fire the `valet secure` command on the folder.

Anyway I'll fix this on the next version.

**Comment by rgb-one** [comment]
Cool.

**Comment by jmarcher** [comment]
v2.2.7 Released
