### ISSUE TITLE
Valet linux/command:valet secure

### ISSUE THREAD

**Issue by korterud** [cpriego/valet-linux#254]
I write valet secure.
and i get this message.

➜  Sites valet secure      
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: Cannot set a default value when using InputOption::VALUE_NONE mode. in /home/robert/.config/composer/vendor/symfony/console/Input/InputOption.php:159
Stack trace:
#0 /home/robert/.config/composer/vendor/mnapoli/silly/src/Command/Command.php(63): Symfony\Component\Console\Input\InputOption->setDefault(false)
#1 /home/robert/.config/composer/vendor/mnapoli/silly/src/Application.php(108): Silly\Command\Command->defaults(Array)
#2 /home/robert/.config/composer/vendor/cpriego/valet-linux/cli/valet.php(85): Silly\Application->command('port [port] [--...', Object(Closure))
#3 {main}
  thrown in /home/robert/.config/composer/vendor/symfony/console/Input/InputOption.php on line 159
➜  Sites 

Thanks :)

**Comment by jmarcher** [comment]
Which PHP version are you using?

**Comment by korterud** [comment]
php --version                  
PHP 7.3.11-0ubuntu0.19.10.1 (cli) (built: Oct 24 2019 11:38:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by jmarcher** [comment]
This PR should have solved that: https://github.com/cpriego/valet-linux/pull/246

Which version are you using? >=2.2.4 should work

**Comment by korterud** [comment]
Thanks. Forgot to change line 67.
Now it working:)
