### ISSUE TITLE
How to share valet site on local network?

### ISSUE THREAD

**Issue by pushpak1300** [cpriego/valet-linux#257]
| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Ubuntu 18.04          | 7.3.1       | 2.2.8        |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-Linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I'm developing a site locally on my Linux and I want to view it on my mobile device which is connected to the same LAN. I could run valet share from my site's local directory, but because ngrok is painfully slow where I live & work, I want to run valet fallback instead.

is there any way i can use this feature in valet-linux?

**Sources**

https://github.com/laravel/valet/pull/439

**Comment by jmarcher** [comment]
I do not see why, can you make a cherry pick of those 3 commits and create a PR here? https://github.com/laravel/valet/pull/439/commits

**Comment by pushpak1300** [comment]
I am not sure how to use cherry-pick . can you share some reference?

**Comment by pushpak1300** [comment]
I am not sure how to do that?

**Comment by jmarcher** [comment]
You can do the following:

```
git clone https://github.com/cpriego/valet-linux`
cd valet-linux
git checkout -b local-network-feature 
git remote add laravel-valet https://github.com/laravel/valet
git fetch laravel-valet
git cherrypick <commit hash>
git cherrypick <commit hash>
...
stage commits and push and do a PR
```
Thanks

**Comment by pushpak1300** [comment]
Can you take look @ #259? 
Thanks!

**Comment by Zzombiee2361** [comment]
I'm sorry for reviving this issue, but I can't understand how to do this. There is no documentation for this repo, and I can't understand the official laravel valet documentation because the config and directory is different

**Comment by pushpak1300** [comment]
run valet share command.

**Comment by Zzombiee2361** [comment]
That's not local network though. It shares using ngrok, which shares publicly on the internet and has rate limit (for free use). I want something [like this](https://laravel.com/docs/8.x/valet#sharing-sites-on-your-local-network), but I can't figure out how to do it with this package

**Comment by jmarcher** [comment]
You can do the exact same thing as in the link you provided.

**Comment by Zzombiee2361** [comment]
It's different though, I can't find `/usr/local/etc/nginx/valet/valet.conf` on my system, is `/etc/nginx/sites-available/valet.conf` the same thing? I also have no idea how to configure nginx so I'm not really sure what to do with the file.

**Comment by Zzombiee2361** [comment]
ping! @jmarcher I still can't figure this out
