### ISSUE TITLE
question: valet share

### ISSUE THREAD

**Issue by tpharaoh** [cpriego/valet-linux#26]
I haven't tried it yet, but I am a bit curious about valet share. I love that feature in my mac, and my wonderful Ubuntu has gotten much less use since Valet came out.

**Comment by tomicakorac** [comment]
@tpharaoh what is your question?

**Comment by tpharaoh** [comment]
If you support valet share

As I said I didn't try it yet but have been watching your project

**Comment by tomicakorac** [comment]
valet-linux is not my project. But yes, it does support all the functionalities that Laravel Valet does, including `valet share`.

**Comment by cpriego** [comment]
@tpharaoh Indeed it does work. The very same way Laravel Valet works in Mac. It uses ngrok to create a tunnel to your computer. Also it will not work with TLS because of the Ngrok "basic" limitations.
