### ISSUE TITLE
Problem when try to run valet install on fedora kde 31 

### ISSUE THREAD

**Issue by islamMagdy2** [cpriego/valet-linux#262]
I got a problem </usr/bin/env: ‘bash’: Not a directory> when I try to run command valet install 
I tried add the .config/composer/vendor/bin to the path and even try the general command 
<test -d ~/.composer && bash ~/.composer/vendor/bin/valet install || bash ~/.config/composer/vendor/bin/valet install>
and still get the same error any idea ?!!!

**Comment by jmarcher** [comment]
Take a look at this: https://unix.stackexchange.com/questions/257969/why-is-usr-bin-env-bash-not-working-on-my-system
