### ISSUE TITLE
Valet Site crashed with error "Cannot redeclare valet_default_site_path() "

### ISSUE THREAD

**Issue by tsaiyihua** [cpriego/valet-linux#263]
I had used valet site for a while, It had worked fine in the past.  thanks a lot.

But it crash today, so I update to the latest version, but it still not work.
I look at the error log. It shows

> 2020/01/02 17:04:58 [error] 11663#11663: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare valet_default_site_path() (previously declared in /[mypath]/.composer/vendor/cpriego/valet-linux/server.php:117) in /[mypath]/.composer/vendor/cpriego/valet-linux/server.php on line 117" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /test.html HTTP/1.1", upstream: "fastcgi://unix:/[mypath]/.valet/valet.sock:", host: "[myhost]"

How can I fix this error ><

OS:  ubuntu 18.04
PHP: php-fpm 7.3

**Comment by jmarcher** [comment]
This is weird, can you please do `valet restart` and give it a try?

How did you updated valet?

**Comment by tsaiyihua** [comment]
When I do `valet restart` it will be ok for only 2 request, the 3rd request will be crashed with 500 error.

My update method is

```
composer global remove cpriego/valet-ubuntu
composer global remove cpriego/valet-linux
composer clear-cache
composer global require cpriego/valet-linux
```

**Comment by tsaiyihua** [comment]
I got the problem.

The problem cause by the php extension "[swoole](https://www.php.net/manual/en/book.swoole.php)"

When I remove this php extension, and exec `valet restart`, it works fine like before.

Is there any way to solve this problem?

**Comment by jmarcher** [comment]
I'll upload a fix in just a few minutes, it is an edge case and it will not break other installations.
