### ISSUE TITLE
Cannot find zipfile directory during composer install

### ISSUE THREAD

**Issue by theianrey** [cpriego/valet-linux#264]
I'm having this issue when I install valet during `composer global require`.
By the way, I'm using an alternative to `composer global require` package named `consolidation/cgr`. Although, using the native `composer global require` still persists the issue.

System specification:

- Manjaro v18.*
- PHP 7.4 with required dependencies for valet linux

Can someone shed me a light on this issue?
=========================================
>`Invalid zip file, retrying...`
>`- Installing cpriego/valet-linux (v2.2.10): Downloading (100%)`         
>`Failed to execute unzip -qq  '/home/<user>/.config/composer/global/cpriego/valet-linux/vendor/cpriego/valet-linux/4397c0f1d85d2f96e4de3195df0684ae' -d '/home/<user>/.config/composer/global/cpriego/valet-linux/vendor/composer/cd22f726'`
>`[/home/<user>/.config/composer/global/cpriego/valet-linux/vendor/cpriego/valet-linux/4397c0f1d85d2f96e4de3195df0684ae]`
>
>`End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.`
>
>`unzip:  cannot find zipfile directory in one of /home/<user>/.config/composer/global/cpriego/valet-linux/vendor/cpriego/valet-linux/4397c0f1d85d2f96e4de3195df0684ae or /home/<user>/.config/composer/global/cpriego/valet-linux/vendor/cpriego/valet-linux/4397c0f1d85d2f96e4de3195df0684ae.zip, and cannot find /home/<user>/.config/composer/global/cpriego/valet-linux/vendor/cpriego/valet-linux/4397c0f1d85d2f96e4de3195df0684ae.ZIP, period.`
>
>`The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)`
>`Unzip with unzip command failed, falling back to ZipArchive class`
>`Failed to download cpriego/valet-linux from dist: '/home/<user>/.config/composer/global/cpriego/valet-linux/vendor/cpriego/valet-linux/4397c0f1d85d2f96e4de3195df0684ae' is not a zip archive.`

--------------------------------------

For the mean time, I'm gonna try to install valet-linux on a lower version of php and check if the issue still exists.

**Comment by jmarcher** [comment]
I tagged a new version (v2.2.11) can you try again?

**Comment by theianrey** [comment]
> I tagged a new version (v2.2.11) can you try again?

@jmarcher this is due to some connection issues and not with the repository itself. Sorry for the late response. Will close the issue now.
Thanks

**Comment by jmarcher** [comment]
I tagged v2.2.10 on my machine on CLI. I usually tag the versions on GitHub, packagist may have had a problem with the CLI tag... I really do not know :confused:
