### ISSUE TITLE
When running valet install: In Container.php line 805Target class [log] does not exist.

### ISSUE THREAD

**Issue by greevesh** [cpriego/valet-linux#266]
I've already installed Valet to Composer with 'composer global require cpriego/valet-linux'. Now I'm trying to install Valet onto my machine. However, when I run 'valet install' I get the following error: In Container.php line 805 805Target class [log] does not exist.

I understand that this isn't an error exclusive to valet-linux but every time I run any kind of valet command, I get this error.

I've tried hunting down Container.php with 'find . Container.php' but it apparently doesn't exist. 

This is on Ubuntu 18.04

Why and how can this be fixed? 

Thanks

**Comment by jmarcher** [comment]
Can you paste a full error log? This error does not seem to be related to valet.

**Comment by greevesh** [comment]
No, it doesn't seem related to valet. However, I can run every other laravel-related command and not get this error. Only when I run a valet command other than 'valet'. In this case, I need to run 'valet install'. 

The full error log: 
In Container.php line 805:
                                      
  Target class [log] does not exist.  
                                      

In Container.php line 803:
                            
  Class log does not exist  
                            

install [--ignore-selinux]

**Comment by jmarcher** [comment]
What do you mean with "Every other laravel-related command"? There are no laravel related commands on Valet. The weird thing is that we do not even have a Log binding.

Can you post an output of: `composer global info` ?

**Comment by greevesh** [comment]
Sorry, I meant to say Laravel-related commands not 'every other' Laravel-related commands. My point is that although it seems like it's a Laravel issue, I can work with Laravel fine right now. However, I can't install or run any other command with Valet other than 'valet'. Please see attached for the global info:
![composer_global_info](https://user-images.githubusercontent.com/37548569/74727655-79234b80-527c-11ea-835c-6ee2a3d3ac26.png)
![composer_global_info2](https://user-images.githubusercontent.com/37548569/74727665-7aed0f00-527c-11ea-89d2-439c1fd149fa.png)

**Comment by jmarcher** [comment]
It seems weird that you have laravel/framwork included globally, this could be the cause of the problem.

**Comment by greevesh** [comment]
I'll take a look. Thanks.
