### ISSUE TITLE
Valet returns 404 when opening page

### ISSUE THREAD

**Issue by EricHier** [cpriego/valet-linux#269]
I'm runnning Valet linux on Essential OS 5.1.2 Hera. 

- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-linux (`valet --version`): `v2.2.10`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I've got the problem that nginx respons with an 404 - Not Found when visiting the page. So far I've already tried everything from the other issue page (https://github.com/cpriego/valet-linux/issues/64) as well as reinstalling. I will give you the output of some commands:

![](https://user-images.githubusercontent.com/17355638/75688751-580d2280-5ca0-11ea-9d5b-2e6dace447cd.png)

**Comment by jmarcher** [comment]
Did you parked the path `/home/erichier/Programmieren/`or `/home/erichier/Programmieren/page`

Please try to do the following:
```
cd /home/erichier/Programieren
valet park
xdg-open http://page.app #Or just open the URL on your browser.
```

**Comment by EricHier** [comment]
Thanks, that helped out! :)
