### ISSUE TITLE
Documentation uninstalling steps are incomplete

### ISSUE THREAD

**Issue by cjlaborde** [cpriego/valet-linux#270]
ended up without the internet again after uninstalling valet

https://cpriego.github.io/valet-linux/#uninstalling
### Current Steps
~~rm /opt/valet~~ Not needed valet uninstall does it for you.
check the folders /etc/NetworkManager/{conf.d,dnsmasq.d} for valet-specific settings and remove them
remove the files /etc/dnsmasq.d/{valet,options}
Make sure systemd-resolved is running, if not, enable and start it (systemctl status systemd-resolved).
remove the dnsmasq package (leaving dnsmasq-base!)
make sure /etc/resolv.conf is a symlink to /run/systemd/resolve/resolv.conf
restart NetworkManager systemctl restart NetworkManager
### Should be changed to
1) check the folders /etc/NetworkManager/{conf.d,dnsmasq.d} for valet-specific settings and remove them
2) remove the files /etc/dnsmasq.d/{valet,options}
3) remove the dnsmasq package `sudo apt-get remove dnsmasq`  
"This should not be done manually or you may screw up system use the sudo command I wrote instead."
4) ~~make sure /etc/resolv.conf is a symlink to /run/systemd/resolve/resolv.conf~~ This is not clear at all instead follow these steps bellow instead.
4) `rm /etc/resolv.conf` 
5) Create the link `ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf`
6) `sudo systemctl restart NetworkManager.service`
7) `sudo systemctl enable systemd-resolved.service`

**Comment by jmarcher** [comment]
Can you make a PR?

**Comment by cjlaborde** [comment]
@jmarcher commit to the documentation? where is the docs repo at?

**Comment by jmarcher** [comment]
@cjlaborde There is another branch `gh-pages`

**Comment by cjlaborde** [comment]
@jmarcher will make a PR this week.

**Comment by atty31** [comment]
I had the same issue or similar one. After I uninstall it, my wifi connection was lost
My valet version is v2.2.16 my ubuntu version is:  20.04.1
