### ISSUE TITLE
Uncaught DomainException: No compatible package manager found

### ISSUE THREAD

**Issue by ramonpego** [cpriego/valet-linux#271]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------------------| ----------------- | ------------- |
| Ubuntu 19.10                      | 7.4                | 2.2.13      |

- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I can't run any valet commands, in fact I can only run ```valet install```  
And I get the message that it was successfully installed
```
Nginx was already enabled
Stopping nginx...
Restarting php7.4-fpm...
Dnsmasq was already enabled
Installing Valet DNS service...
Valet-dns was already enabled
Systemd-resolved was already disabled
Stopping systemd-resolved...
Restarting network-manager...
Restarting dnsmasq...
Starting valet-dns...
Restarting nginx...

Valet installed successfully!
```

**What was supposed to happen?**
I can't run ```valet link```  and ```valet secure``` commands

**What actually happened?**
When i run ```valet link``` or secure I get this error
```
PHP Fatal error:  Uncaught DomainException: No compatible package manager found. in /home/ramon/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Valet.php:134
Stack trace:
#0 /home/ramon/.config/composer/vendor/tightenco/collect/src/Collect/Support/helpers.php(43): Valet\Valet::Valet\{closure}()
#1 /home/ramon/.config/composer/vendor/tightenco/collect/src/Collect/Support/Arr.php(180): value()
#2 /home/ramon/.config/composer/vendor/tightenco/collect/src/Collect/Support/Collection.php(367): Tightenco\Collect\Support\Arr::first()
#3 /home/ramon/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Valet.php(135): Tightenco\Collect\Support\Collection->first()
#4 /home/ramon/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Valet.php(114): Valet\Valet->getAvailablePackageManager()
#5 /home/ramon/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Valet.php(103): Valet\Valet->packageManagerSetup()
#6 /home/ramon/.config/composer/vendor/cpriego/valet-linux/cli/includes/facades.php(28): Valet\Valet->environmentSetup()
#7 /h in /home/ramon/.config/composer/vendor/cpriego/valet-linux/cli/Valet/Valet.php on line 134
```

**Sources**
i tried to follow #182 and #38 but i still have the problem

**Comment by jmarcher** [comment]
That is weird, what is the output of: `which apt-get` ?

**Comment by ramonpego** [comment]
```script
ramon@ramonpego:~$ which apt-get
/usr/bin/apt-get
```
I had this package working on my last OS (Linux Mint 19.03 based on ubuntu 18.10)

**Comment by jmarcher** [comment]
I have no clues how this can be possible

**Comment by ramonpego** [comment]
I had recently change my os, cause i acquired a new computer and this has not happen on new OS, i put mint 19.03 on it,
So it can be something wrong on my previous machine or OS
I'll close this, thanks for trying bro
