### ISSUE TITLE
New Firefox profile suffixes

### ISSUE THREAD

**Issue by nielspeen** [cpriego/valet-linux#276]
Valet manipulates the certificate database it finds in **~/.mozilla/firefox/*.default**:

```
$this->cli->run(sprintf('certutil -d $HOME/.mozilla/firefox/*.default -D -n "%s"', $url));
```

More recent versions of Firefox may use a different suffix: **.default-release** or **.default-nightly** instead of the **.default**. 

Valet should probably update folders with all 3 suffixes.

**Comment by jmarcher** [comment]
Can you make a PR?
