### ISSUE TITLE
.valet-env.php not loaded

### ISSUE THREAD

**Issue by peter-loqbox** [cpriego/valet-linux#277]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ----------------------------------- | ----------------- | ----------------- |
| Ubuntu 18.04.4 LTS           | 7.3.15           | 2.2.3             |

- [✔️] I've checked the issue queue and could not find anything similar to my bug.
- [✔️] I'm on the latest version of valet-linux (`valet --version`): `Valet v2.2.14`
- [N/A] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Adding a `.valet-env.php` file to the root of a project does not add the specified variables to `$_SERVER`.

**What was supposed to happen?**
Load some custom env vars as explained [here](https://laravel.com/docs/7.x/valet#site-specific-environment-variables).

**What actually happened?**
Nothing.

**How to reproduce this?**
Add a .valet-env.php file to the root of a project with some custom env vars, for example:
```php
<?php

return [
    '*' => [
        'MY_ENV' => 'dev',
    ],
];
```

**What is the solution?**
Scanning through the valet-linux codebase, I noticed that there is a function `loadServerEnvironmentVariables` in `ValetDriver.php`, but that function doesn't seem to be called anywhere. Perhaps the fix to this issue is to just call it somewhere?

For now, I've managed to overcome this issue by using a local driver. In the root of the project (alongside `.valet-env.php`), I've created a file `LocalValetDriver.php` with the following content:

```php
<?php

class LocalValetDriver extends BasicValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        $this->loadServerEnvironmentVariables($sitePath, $siteName);

        return true;
    }
}
```

This seems to solve the issue, but it would be better if each driver (or the base driver I guess) calls the `loadServerEnvironmentVariables` directly.

**Sources**
[Site Specific Environment Variables docs from Laravel Valet](https://laravel.com/docs/7.x/valet#site-specific-environment-variables)

**Comment by jmarcher** [comment]
We do not support that, note that we are a fork of the original Laravel Valet.

Here is our documentation: https://cpriego.github.io/valet-linux

**Comment by peter-loqbox** [comment]
Thanks for your response @jmarcher. Perhaps this should be a feature request then?

**Comment by jmarcher** [comment]
> Wait so this projects doesn't intend to keep up to date with Laravel Valet? Isn't that what a fork is for.

No that is not what a Fork is for, I develop Valet-Linux on my free time, I do not have much free time lately, so development is kind of frozen at the moment.
