### ISSUE TITLE
404 - Not Found

### ISSUE THREAD

**Issue by on3dd** [cpriego/valet-linux#278]
Hi, I'm trying to run valet-linux on my Ubuntu 18.04 laptop, but it gives me `"404 - Not Found"` every time I open my website on `http://mfti.test`. I've tried to fix it following #64 and #269 issues but it didn't help me.

Here is some debug info:
![Screenshot from 2020-04-23 12-04-33](https://user-images.githubusercontent.com/45851782/80051114-bd6fe800-855a-11ea-82b7-5163affae833.png)
![Screenshot from 2020-04-23 12-07-29](https://user-images.githubusercontent.com/45851782/80051230-0758ce00-855b-11ea-9b7f-c6fc4c79d31c.png)

I'm not from a PHP-world and cannot solve this problem myself, so I hope that you guys can help me with this. Thanks!

**Comment by jmarcher** [comment]
the only path you need is `/home/on3dd/projects` maybe the others are causing problems.

**Comment by on3dd** [comment]
No, later I deleted them, but the problem remained. Anyway, the problem was resolved after the third reinstallation. Still wondering what went wrong..
