### ISSUE TITLE
How to replace ConnMan to NetworkManager? 

### ISSUE THREAD

**Issue by kevariable** [cpriego/valet-linux#279]
I use arch Linux and I get error Unable to determine service name. Because I'm not installed network manager

**Comment by jmarcher** [comment]
Give more info please, what are you using instead of NetworkManager?

**Comment by kevariable** [comment]
@jmarcher 
Sorry, https://wiki.archlinux.org/index.php/ConnMan

**Comment by jmarcher** [comment]
Your title does not make the issue any clear, do you want to install NetworkManager? Here is not the place to get this kind of support.

Valet is highly tightened with NetworkManager, you could send a PR if you want.

I have zero experience with ConnMan. Here is a starting point: https://github.com/cpriego/valet-linux/blob/master/cli/Valet/DnsMasq.php
