### ISSUE TITLE
Connection refused problem when using valet secure.

### ISSUE THREAD

**Issue by MoinGandhi** [cpriego/valet-linux#281]
I have installed valet in ubuntu 19.10 and park the valet in /var/www folder. It works OK in HTTP connection but when I secure using  `valet secure domain name` then run project it gives connection refused error in HTTPs connection in chrome browser also I tried in Firefox but still gives same error.

![Screenshot from 2020-04-29 13-59-03](https://user-images.githubusercontent.com/34887731/80575727-a4b37680-8a21-11ea-9412-5971aedd4ebe.png)

**Comment by jmarcher** [comment]
Try this: 

```
cd /var/www/<name of your project>
valet secure
```

**Comment by MoinGandhi** [comment]
I have also tried it secure the connection and make new certificate but still getting same connection refused error.

**Comment by jmarcher** [comment]
Have you tried the commands from above? Which version of Firefox do you have?

**Comment by josegus** [comment]
Same here, using ubuntu 20.04 and valet 2.2.6 with latest chrome and firefox
