### ISSUE TITLE
Question:How change PHP version on the fly?

### ISSUE THREAD

**Issue by carlossantoswd** [cpriego/valet-linux#284]
Hello!
I have a question and not a issue.

I'm successfully in change the PHP version used by valet-linux (php 5.6 and php 7.2) using the valet use command.

But, I wanna know if it is possible, change the PHP Version on demand.

Example:
PROJETC A, parked in valet use PHP 5.6
PROJETC B, parked in valet use PHP 7.2

whe open the project in the browser, valet or nginx determine the correct php version to the projet, and use this version.

I've searched at valet driver, valet server.php, /etc/nginx/sites-enabled and /etc/nginx/sites-available but without sucess to change the PHP version according the projetc open in browser.

**Comment by jmarcher** [comment]
This is not possible by default with valet, but we provide the option to publish the ngnix conf from a linked site, this way you could pluck a different php-fpm listener within the location. This listener should be configured previously.

I never needed something like this thus never tried something like this before.

**Comment by rizkysyazuli** [comment]
@carlossantoswd @jmarcher Wait.. so does the `valet use` command actually works in this Linux version? On #142 it says it's not supported.

**Comment by carlossantoswd** [comment]
> @carlossantoswd @jmarcher Wait.. so does the `valet use` command actually works in this Linux version? On #142 it says it's not supported.

here it's working (Ubuntu 20.04, tested too 18.04)

![screenshot-2020-06-30_14-23-11](https://user-images.githubusercontent.com/41978568/86157322-9810d480-badd-11ea-9561-3f6ea1a774e4.png)

**Comment by rizkysyazuli** [comment]
sweet! will give it a try. thx @carlossantoswd
