### ISSUE TITLE
Pacman was unable to install [phpphp73-fpm].

### ISSUE THREAD

**Issue by ronald2wing** [cpriego/valet-linux#286]
When running valet use php73 on Arch linux distro. It gives me `Pacman was unable to install [phpphp73-fpm].` but I am able install php73-fpm on Arch linux with pacman -S php73-fpm.

**Comment by jmarcher** [comment]
What happens if you type `valet use 73`

**Comment by ronald2wing** [comment]
Changing php-fpm version...
This does not affect php -v.
Stopping php-fpm...
Disabling php-fpm...
Php-fpm has been disabled
[phpphp73-fpm] is not installed, installing it now via Pacman... 🍻
error: target not found: phpphp73-fpm

Enabling php-fpm...
Php-fpm has been enabled
Changing version failed

In Pacman.php line 74:
                                                
  Pacman was unable to install [phpphp73-fpm].  
                                                

use [<preferedversion>]

**Comment by jmarcher** [comment]
It seems that you typed `php73` but what happens when you type `valet use 73`?

**Comment by ronald2wing** [comment]
Yes. It works that way!
