### ISSUE TITLE
Homebrew php not found

### ISSUE THREAD

**Issue by 65** [cpriego/valet-linux#287]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Debian 9 Stretch         | 7.4.6       | 2.2.14         |

- [ x] I've checked the issue queue and could not find anything similar to my bug.
- [x ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Running `valet install` and it cant find php even though php is in the path and can be run

**What happened?**
/home/user/.config/composer/vendor/bin/valet: line 36: php: command not found

Is there a solution I am missing here?

**Comment by jmarcher** [comment]
Hi @65 Homebrew is not supported, but `apt` should work in your case.

**Comment by 65** [comment]
ok thanks - are there any plans to support homebrew?

**Comment by jmarcher** [comment]
Yes, I started adding support for brew on the `beta` branch: https://github.com/cpriego/valet-linux/tree/beta but due to lack of time I did not continued the development.

**Comment by zbandhan** [comment]
Does homebrew support in valet linux now? Yet I have found the same issue in homebrew. Valet linux is working just fine in Apt but still not in Brew.
