### ISSUE TITLE
When use other php version, it display 502 Bad Gateway

### ISSUE THREAD

**Issue by ronald2wing** [cpriego/valet-linux#288]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: 5.4.44-1-MANJARO          | 7.3.18       | 2.2.14         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
If I use valet use 73, it will give me 502 Bad Gateway.

**What was supposed to happen?**
Should at least show errors on the page. But should give me a working site.

**What actually happened?**
502 Bad Gateway.

**How to reproduce this?**
Just run valet use 73

**What is the solution?**
I don't know.

**Sources**
I have enabled necessary PHP extensions.

**Comment by jmarcher** [comment]
Can you post the output of `~/.valet/Log/nginx-error.log` ?

**Comment by ronald2wing** [comment]
Thanks for your help but I am using something else now.
