### ISSUE TITLE
error in nginx conf

### ISSUE THREAD

**Issue by coolpraz** [cpriego/valet-linux#29]
```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
nginx: [emerg] unexpected ";" in /etc/nginx/nginx.conf:3
```
after removing extra semi colon on code this error occur

```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /etc/nginx/nginx.conf:11
```

**Comment by cpriego** [comment]
Did you run `nginx -t` as a normal user? Because I only get those "errors" then. But nginx is started by root. 

If you run `sudo nginx -t` the errors disappear.

**Comment by coolpraz** [comment]
error is the same using `nginx -t` 

```
nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /etc/nginx/nginx.conf:11
nginx: configuration file /etc/nginx/nginx.conf test failed
```

i checked the directory there isn't /etc/nginx/mime.types

i m using ubuntu 16.04

**Comment by cpriego** [comment]
/etc/nginx/mime.types is part of the nginx installation package. Run a clean reinstall to fix the missing file. 
```
sudo apt clean
sudo apt install --reinstall nginx-full
valet install
```

**Comment by coolpraz** [comment]
yea that's work for me the problem was with nginx-full

thank you @cpriego
