### ISSUE TITLE
Bug: Valet does not run on openSuse Leap 15.1

### ISSUE THREAD

**Issue by euneuber** [cpriego/valet-linux#290]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| openSuse Leap 15.1         | 7.4.8       | 2.8.1

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Valet display on almost all commands "Valet only supports the Mac operating system."

**What was supposed to happen?**
Valet should perform the action of the command called -- what ever that is, or display an error about the command.

**What actually happened?**
Only "Valet only supports the Mac operating system." is displayed, then valet aborts,

**How to reproduce this?**
Setup a VM with openSuse Leap 15.1, install php, jq, xsel, composer and install valet via composer.
Run `valet install`

**What is the solution?**
Can you explain to me what is missing? Maybe I should install anything additionally?

**Sources**
none.

**Comment by jmarcher** [comment]
It looks you installed the wrong package `laravel/valet`, please read the docs and install `cpriego/valet-linux`
