### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by akashkaintura** [cpriego/valet-linux#292]
Hi , I have tried every method to install valet in ubuntu focal fossa but its not working (always same return -> valet install
Valet only supports the Mac operating system.)
nano ~/.profile -> PATH="$HOME ~/.composer/vendor/bin:$PATH"
source ~/.profile and then
valet install command not working

![Screenshot from 2020-07-14 20-58-45](https://user-images.githubusercontent.com/19641486/87444799-dd242300-c614-11ea-9480-0174ddb9f1ab.png)

**Comment by jmarcher** [comment]
You installed the wrong package you need to require `cpriego/valet-linux`
AKASH KAINTURA <notifications@github.com> schrieb am Di., 14. Juli 2020,
17:30:

**Comment by akashkaintura** [comment]
No, I have installed the same package you mention. 
Thanks

**Comment by jmarcher** [comment]
You may have but I'm sure you also have `laravel/valet` installed check it
on your global installed packages

AKASH KAINTURA <notifications@github.com> schrieb am Mi., 15. Juli 2020,
05:50:

**Comment by akashkaintura** [comment]
yes I need to uninstall this package first?
and then reinstall the laravel/valet for linux.?

**Comment by jmarcher** [comment]
You need to *remove *laravel/valet and *require *cpriego/valet-linux then
you will be able to *install* valet-linux

**Comment by akashkaintura** [comment]
How to configure the SSL in Ubuntu linux as I am unable to open the project now.
![Screenshot from 2020-07-15 21-01-38](https://user-images.githubusercontent.com/19641486/87565419-3d7f9700-c6df-11ea-99fd-b9b3f3b45843.png)
![Screenshot from 2020-07-15 21-08-10](https://user-images.githubusercontent.com/19641486/87565470-4e300d00-c6df-11ea-943c-b9fcec0aa511.png)

**Comment by jmarcher** [comment]
Which version are you using? should be fixed on v2.2.15 (Having Firefox installed) or you could just add the certificate as an exception

**Comment by akashkaintura** [comment]
the same version v2.2.15. How to add certificate because whenever i am trying to secure the link it shows tld is secure but not ssl one ?

**Comment by 6h4n3m** [comment]
> 
> 
> the same version v2.2.15. How to add certificate because whenever i am trying to secure the link it shows tld is secure but not ssl one ?
> 
> What is the reason??

If you are using Chrome, you need to import the CA certificate in ~/.valet/CA into Ubuntu's certificate store.

Run these commands in your terminal
```
> sudo mv ~/.valet/CA/LaravelValetCASelfSigned.pem /usr/local/share/ca-certificates/LaravelValetCASelfSigned.crt
> sudo update-ca-certificates
```
Afterwards, everything should work for Chromium based browsers. For Firefox, you'll need to import the same file into the Firefox store from the FF settings page, no terminal commands necessary.

**Comment by jmarcher** [comment]
@6h4n3m That would be awesome if you could send a PR for that!

**Comment by 6h4n3m** [comment]
> 
> 
> @6h4n3m That would be awesome if you could send a PR for that!

@jmarcher I think @cpriego still maintains https://github.com/cpriego/valet-linux-docs, do you have an idea if he's still fine with PRs or do you intend to fork the docs and we can point to the new docs on the readme?

**Comment by jmarcher** [comment]
@6h4n3m That's an old repo, you will find the documentation here: https://github.com/cpriego/valet-linux/tree/gh-pages it is a different branch.

**Comment by 6h4n3m** [comment]
@jmarcher Alright, thanks.. I'll get on it asap.

**Comment by josegus** [comment]
> > the same version v2.2.15. How to add certificate because whenever i am trying to secure the link it shows tld is secure but not ssl one ?
> > What is the reason??
> 
> If you are using Chrome, you need to import the CA certificate in ~/.valet/CA into Ubuntu's certificate store.
> 
> Run these commands in your terminal
> 
> ```
> > cp ~/.valet/CA/LaravelValetCASelfSigned.pem /usr/local/share/ca-certificates/LaravelValetCASelfSigned.crt
> > sudo update-ca-certificates
> ```
> 
> Afterwards, everything should work for Chromium based browsers. For Firefox, you'll need to import the same file into the Firefox store from the FF settings page, no terminal commands necessary.
> 
> @jmarcher Maybe we can update the docs to include these instructions? at least for major distros? let me know if that's something you'd want done, I can send a PR.

I did what you suggest but still doesn't work, I still getting "invalid certificate" in chrome using ubuntu 20.04 and valet 2.2.16

**Comment by 6h4n3m** [comment]
@josegus Can you provide the output when you ls the /usr/local/share/ca-certificates/ directory?

Also, when you tried to update the certificates using the 2nd command, did you get any errors?

Did you try importing the CA into Firefox and check to see if it's working?

**Comment by josegus** [comment]
> @josegus Can you provide the output when you ls the /usr/local/share/ca-certificates/ directory?
> 
> Also, when you tried to update the certificates using the 2nd command, did you get any errors?
> 
> Did you try importing the CA into Firefox and check to see if it's working?

Sure, here it is:

![image](https://user-images.githubusercontent.com/13947849/97201082-69072880-1788-11eb-9e90-b4fe34885db6.png)

I needed to use sudo to copy the .pem file because of permissions

I will try firefox later, would like to make it work on chome first.

**Comment by 6h4n3m** [comment]
> > @josegus Can you provide the output when you ls the /usr/local/share/ca-certificates/ directory?
> > Also, when you tried to update the certificates using the 2nd command, did you get any errors?
> > Did you try importing the CA into Firefox and check to see if it's working?
> 
> Sure, here it is:
> 
> ![image](https://user-images.githubusercontent.com/13947849/97201082-69072880-1788-11eb-9e90-b4fe34885db6.png)
> 
> I needed to use sudo to copy the .pem file because of permissions
> 
> I will try firefox later, would like to make it work on chome first.

Okay, can you try converting the .pem file to a .crt file first then carrying out all the same steps again (copying then adding).

You can convert a .pem cert to a .crt using the following command:

`openssl x509 -outform der -in CERTIFICATE.pem -out CERTIFICATE.crt`

**Comment by 6h4n3m** [comment]
> > @josegus Can you provide the output when you ls the /usr/local/share/ca-certificates/ directory?
> > Also, when you tried to update the certificates using the 2nd command, did you get any errors?
> > Did you try importing the CA into Firefox and check to see if it's working?
> 
> Sure, here it is:
> 
> ![image](https://user-images.githubusercontent.com/13947849/97201082-69072880-1788-11eb-9e90-b4fe34885db6.png)
> 
> I needed to use sudo to copy the .pem file because of permissions
> 
> I will try firefox later, would like to make it work on chome first.

Can you try `sudo update-ca-certificates --fresh` and let me know.

**Comment by josegus** [comment]
> > > @josegus Can you provide the output when you ls the /usr/local/share/ca-certificates/ directory?
> > > Also, when you tried to update the certificates using the 2nd command, did you get any errors?
> > > Did you try importing the CA into Firefox and check to see if it's working?
> > 
> > 
> > Sure, here it is:
> > ![image](https://user-images.githubusercontent.com/13947849/97201082-69072880-1788-11eb-9e90-b4fe34885db6.png)
> > I needed to use sudo to copy the .pem file because of permissions
> > I will try firefox later, would like to make it work on chome first.
> 
> Can you try `sudo update-ca-certificates --fresh` and let me know.

Ok, I followed all steps: convert to crt, then copy and later run ```sudo update-ca-certificates --fresh``` (no errors throwed), then I unlink and link again my valet site.. but still not working

**Comment by stickeerehan** [comment]
Issue is not limited to Ubuntu 20.20. 

On Ubuntu 20.04.1 LTS, upgraded valet to 2.2.17 and my previously secured sites now display the same NET::ERR_CERT_AUTHORITY_INVALID error on Chrome.

Followed the instructions:
```
sudo cp ~/.valet/CA/LaravelValetCASelfSigned.pem /usr/local/share/ca-certificates/LaravelValetCASelfSigned.crt
sudo update-ca-certificates --fresh
```

No errors, and can see `Replacing debian:LaravelValetCASelfSigned.pem` in the log, however site is still showing error.

Also tried `valet secure` to create a fresh certificate. Logs show it was successful:

```
Restarting php7.4-fpm...
Restarting nginx...
The [site.test] site has been secured with a fresh TLS certificate
```
 However, that did not fix it, and running `valet secured` returns 'is not secured.'
