### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gev88** [cpriego/valet-linux#293]
| Ubuntu 20.04 | PHP 7.4 | Valet v2.2.15 |
valet fresh install , ssl problem 
NET::ERR_CERT_AUTHORITY_INVALID Chrome Version 84.0.4147.89

**Comment by jmarcher** [comment]
This issue is a bit cryptic, can you elaborate a little more? Maybe this could help: https://github.com/cpriego/valet-linux/issues/292#issuecomment-660082687

**Comment by sgsdev** [comment]
hello , still not working , i have installed valet many many times before
and had no issues with ssl , it's not important for me, your project is
must have , and i'm trying to inform
on Ubuntu 20.04 and PopOs 20.04 i have this problem
[image: Screenshot from 2020-07-28 22-26-00.png]
[image: Screenshot from 2020-07-28 22-14-58.png]
