### ISSUE TITLE
valet secure all parked domain

### ISSUE THREAD

**Issue by bhushan** [cpriego/valet-linux#296]
Suppose i have parked all my code to `~/Code` directory ...

It has two folders `laravel-one` and `laravel-two`

now sure enough i can goto `http://laravel-one.test` and `http://laravel-two.test` by default.

but to secure domains i have to manually go into folder and serve that domain as https using `valet secure`

but i could not find any way to by default serve all parked domains as `https`

there should be way to if i create new project in `Code` directory lets say `laravel-three` so i can directly access it using `https://laravel-three.test`

**Comment by jmarcher** [comment]
This can not be made automatically with simple methods. If you have a suggestion feel free to do a PR
