### ISSUE TITLE
How to configure nginx for WordPress Multisite

### ISSUE THREAD

**Issue by wowthemes** [cpriego/valet-linux#297]
Wondering how to configure nginx for WordPress multisite. WordPress suggests some changes https://wordpress.org/support/article/nginx/ .

**Comment by jmarcher** [comment]
Can you explain what exactly WordPress multisite needs? Do you need subdomain or what is it about?

**Comment by wowthemes** [comment]
I need the nginx configuration for sub-directories like [mentioned here](https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/#rewrite-rules-for-multisite-using-subdirectories)

**Comment by jmarcher** [comment]
As I said i was hoping you can explain me what it needs to be done, I can
not read the docs at the moment. Regarding nginx config, you could just
link your site that way you will have a nginx config file you can edit as
you please.

Shahbaz ahmed <notifications@github.com> schrieb am Di., 18. Aug. 2020,
17:50:
