### ISSUE TITLE
Error when execute project

### ISSUE THREAD

**Issue by damianlluch** [cpriego/valet-linux#298]
Hi guys, thanks for sharing this space.

I have this error when running my project with Valet on Ubuntu 18.

Message: "Could not find the driver (SQL: select the top 1 * of [users] where [api_token] = XbJPLD0by8JkxXGHwOkQClALUccAAPpJAzUejAcZF7SOVdT1Lqajn9xu1Gt8gbr41k2dcRq4OVd5uKUP)"

I follow these steps:

I have installed the composer, valet, I have cloned the projects and installed the dependencies, I have executed the command "valet park" inside the folder of each project (3 projects).
I see the home page of the Laravel project in the midominio.test browser for example.
And when I execute from my backend and I get this error.

Any suggestion?

Thanks

**Comment by jmarcher** [comment]
@damianlluch That is not a Valet related error, either is you have a missconfiguration on your Laravel project, or you may have to install either MySQL, PostgreSQL or SQLite PDO extensions
