### ISSUE TITLE
Error: Valet only supports the Mac operating system.

### ISSUE THREAD

**Issue by ruslanashaari** [cpriego/valet-linux#30]
This message appear when I do valet install. Please help

**Comment by TheNodi** [comment]
Which commands are you running to install valet?

Do you have the laravel/valet package installed?

**Comment by ruslanashaari** [comment]
I use composer global require cpriego/valet-linux then I use valet install. But I just realised I also try composer global require laravel/valet previously. This must be why. How to uninstall it?

**Comment by cpriego** [comment]
```
composer global remove laravel/valet
```

**Comment by ruslanashaari** [comment]
Thanks! Already remove it, now when I do valet install, i encountered this:

PHP Fatal error:  Cannot declare class Nginx, because the name is already in use in /home/lanesra/.config/composer/vendor/cpriego/valet-linux/cli/includes/facades.php on line 32

Any idea?

**Comment by ruslanashaari** [comment]
Looks like it conflict with valet-ubuntu i installed earlier. This issue helps me: https://github.com/cpriego/valet-linux/issues/25

`composer global remove cpriego/valet-ubuntu
composer global remove cpriego/valet-linux
composer clear-cache
composer global require cpriego/valet-linux`

I do this and it solved! Thank you very much

**Comment by VictorPinoc** [comment]
I used:
composer global update
composer global remove laravel/valet
valet install 

and work!

**Comment by saldisucipto** [comment]
its work for me too,
thanks i used ubuntu 19.04

**Comment by acatzk** [comment]
i just read the comment and solve my problem too.

**Comment by Pratama89** [comment]
I used:
composer global update
composer global remove laravel/valet
valet install

its work for me too!

**Comment by abdellahramadan** [comment]
I have followed every step and it does not work. I use Linux Mint Una

**Comment by jmarcher** [comment]
This error means you installed the wrong version of Valet, namely the official version which does not support Linux, you need to follow the instructions on our website or this repo's readme file.
