### ISSUE TITLE
Bug: Valet Linux causes DNS loopback on OpenSuse

### ISSUE THREAD

**Issue by ajoy39** [cpriego/valet-linux#300]
Running Valet Linux on OpenSuse Leap 15.2 kills all other DNS requests. After running valet install all internet requests return DNS errors. Running valet uninstall fixes the issue, but obviously this also means valet isn't running anymore. 

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| OpenSuse Leap 15.2          | 7.4.6      | 2.2.16        |

- [X ] I've checked the issue queue and could not find anything similar to my bug.
- [X ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [X ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.
(valet fix isn't a command?)

**What is the problem?**
Something about the default OpenSuse configuration isn't passing DNS requests through valet to a normal DNS resolver for non-valet address.

**What was supposed to happen?**
I should still be able to access the internet with valet installed and running

**What actually happened?**
I can't

**How to reproduce this?**
install valet-linux on OpenSuse and run valet install, try to access the web

**Comment by ajoy39** [comment]
This is happening to me again, this time on Ubuntu studio 20.10. With valet running I can't access any websites other than the .test domains or ones I already have my DNS cached for. This includes things on the command line, phpunit tests are failing because they can't access stripes API.

**Comment by chrisdicarlo** [comment]
Did you ever resolve this issue?  I'm seeing the same thing the last couple of days.
