### ISSUE TITLE
Bug: Valet shows php7.4-fpm but throws error on arrow function introduced in php 7.4

### ISSUE THREAD

**Issue by CharlieTheProgrammer** [cpriego/valet-linux#302]
I have installed and am using php@7.4. When I run ```valet restart``` I get the following 

```
Restarting php7.4-fpm...
Restarting nginx...
Valet services have been restarted.
```
However, I am not able to use the brand new arrow function in PHP7.4. When I use ```php -v```, I get 7.4.10, but from what I now understand, this is not the same version of php as valet linux. When running ```php artisan serve```, arrow functions works as expected, confirming the app is using php 7.4.10. It appears that valet's version of php is either not actually 7.4 as stated by the ```valet restart``` output.

 Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 18.04  WSL2       | 7.4?       | 2.2.16         |

- [ X] I've checked the issue queue and could not find anything similar to my bug.
- [X ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Valet Linux is somehow not using PHP 7.4.

**What was supposed to happen?**
I should be able to use the latest functionality provided by PHP 7.4 when accessing site using Valet.

**How to reproduce this?**
Install latest version of PHP on Ubuntu 18.04 WSL2.

**Comment by jmarcher** [comment]
Can you paste the contents of your nginx logs? How are you testing the arrow functions? Can you isolate your thesis, and create a new folder with an index.php file containing the following:

```php
<?php

$f = fn($a) => $a;

print_r($f('Hello world!')); die();
```

**Comment by CharlieTheProgrammer** [comment]
Sure thing. Below is the log for the scenario you mentioned.
```
2020/10/05 08:40:54 [error] 1041#1041: *18 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home/charlieo/Sites/val-test/index.php on line 3" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico $
```

**Comment by jmarcher** [comment]
change that to `phpinfo();` and can you check which version is your valet using and the paths.

**Comment by CharlieTheProgrammer** [comment]
```
*** Topmost table ***

Server API | FPM/FastCGI
Virtual Directory Support | disabled

Configuration File (php.ini) Path | /etc/php/7.2/fpm

Loaded Configuration File | /etc/php/7.2/fpm/php.ini

Scan this dir for additional .ini files | /etc/php/7.2/fpm/conf.d

Additional .ini files parsed | /etc/php/7.2/fpm/conf.d/10-mysqlnd.ini, /etc/php/7.2/fpm/conf.d/10-opcache.ini, /etc/php/7.2/fpm/conf.d/10-pdo.ini, /etc/php/7.2/fpm/conf.d/15-xml.ini, /etc/php/7.2/fpm/conf.d/20-calendar.ini, /etc/php/7.2/fpm/conf.d/20-ctype.ini, /etc/php/7.2/fpm/conf.d/20-curl.ini, /etc/php/7.2/fpm/conf.d/20-dom.ini, /etc/php/7.2/fpm/conf.d/20-exif.ini, /etc/php/7.2/fpm/conf.d/20-fileinfo.ini, /etc/php/7.2/fpm/conf.d/20-ftp.ini, /etc/php/7.2/fpm/conf.d/20-gettext.ini, /etc/php/7.2/fpm/conf.d/20-iconv.ini, /etc/php/7.2/fpm/conf.d/20-intl.ini, /etc/php/7.2/fpm/conf.d/20-json.ini, /etc/php/7.2/fpm/conf.d/20-mbstring.ini, /etc/php/7.2/fpm/conf.d/20-mysqli.ini, /etc/php/7.2/fpm/conf.d/20-pdo_mysql.ini, /etc/php/7.2/fpm/conf.d/20-phar.ini, /etc/php/7.2/fpm/conf.d/20-posix.ini, /etc/php/7.2/fpm/conf.d/20-readline.ini, /etc/php/7.2/fpm/conf.d/20-shmop.ini, /etc/php/7.2/fpm/conf.d/20-simplexml.ini, /etc/php/7.2/fpm/conf.d/20-sockets.ini, /etc/php/7.2/fpm/conf.d/20-sysvmsg.ini, /etc/php/7.2/fpm/conf.d/20-sysvsem.ini, /etc/php/7.2/fpm/conf.d/20-sysvshm.ini, /etc/php/7.2/fpm/conf.d/20-tokenizer.ini, /etc/php/7.2/fpm/conf.d/20-wddx.ini, /etc/php/7.2/fpm/conf.d/20-xmlreader.ini, /etc/php/7.2/fpm/conf.d/20-xmlwriter.ini, /etc/php/7.2/fpm/conf.d/20-xsl.ini, /etc/php/7.2/fpm/conf.d/20-zip.ini



*** PHP Variables section ***
$_SERVER['DOCUMENT_ROOT'] | /home/charlieo/.valet/Sites/val-test
$_SERVER['DOCUMENT_URI'] | /home/charlieo/.composer/vendor/cpriego/valet-linux/server.php
$_SERVER['REQUEST_URI'] | /
$_SERVER['SCRIPT_NAME'] | /index.php
$_SERVER['SCRIPT_FILENAME'] | /home/charlieo/.valet/Sites/val-test/index.php

```

**Comment by jmarcher** [comment]
Do you still need 7.2? If not you may uninstall it, if you still need it, maybe try: `valet use 7.4` or `valet use 74` depending on how your package manager names the PHP versions.

**Comment by CharlieTheProgrammer** [comment]
Ok, I was able to resolve the issue by uninstalling all php versions and re-installing it using apt. I've actually created a brand new Ubuntu WSL2 instance and reinstalled some things. It appears that php installs done via brew are not detected by Valet. In my new instance, when I run php -v, I see the latest version of php 7.4.11. 

However, when I run ```valet install```, I get this issue ```/home/charlieo/.config/composer/vendor/bin/valet: line 36: php: command not found```.

Below is my php --ini output.
```
Configuration File (php.ini) Path: /home/linuxbrew/.linuxbrew/etc/php/7.4
Loaded Configuration File:         /home/linuxbrew/.linuxbrew/etc/php/7.4/php.ini
Scan for additional .ini files in: /home/linuxbrew/.linuxbrew/etc/php/7.4/conf.d
Additional .ini files parsed:      /home/linuxbrew/.linuxbrew/etc/php/7.4/conf.d/ext-opcache.ini
```
Valet is not picking up php when installed by brew.
