### ISSUE TITLE
Bug: Valet does not work for multiple users

### ISSUE THREAD

**Issue by dakira** [cpriego/valet-linux#303]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 20.04          | 7.4.10       | 2.2.16         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
The files `/etc/nginx/nginx.conf` and `/etc/nginx/sites-available/valet.conf` are user specific which prohibits two users on the same system from both using valet.

The files are also not overwritten when running `valet install` (which would be a nice workaround).

**What is the solution?**
As a workaround I propose overwriting the existing nginx.conf and valet.conf when running `valet install`.

**Comment by dakira** [comment]
@jmarcher maybe you can [activate hacktober](https://hacktoberfest.digitalocean.com/hacktoberfest-update) for this repo?

**Comment by jmarcher** [comment]
I will take a look at it.

I can not enable hacktober on this repo as I do not have full access to the repo, just a maintainer :)

**Comment by dakira** [comment]
Sorry, it looks like valet already (correctly) overwrites nginx.conf **and** valet.conf (it didn't work in my machine because some user linked an old version of valet to /usr/local/bin/valet).

So while it would be a nice new feature to write user-independend configuration files, there is no bug here.
