### ISSUE TITLE
How can i change doas instead of sudo?

### ISSUE THREAD

**Issue by kevariable** [cpriego/valet-linux#307]

**Comment by jmarcher** [comment]
Care to explain? Write a proper description not just a title without content.

**Comment by kevariable** [comment]
sorry sir, I prefer to use doas instead of sudo because it's lighter, sudo is too bloated than doas, i've tried doas but an error occurs because by default valet source uses sudo

**Comment by jmarcher** [comment]
`sudo` is installed on literally every Linux distribution, if you wish to use `doas` you will need to fork this repo and build it yourself. I do not believe it is hard to implement but I do not see it necessary for this repository's scope
