### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by ashokbaruaakas** [cpriego/valet-linux#311]
Valet Linux Work PHP 8???

**Comment by jmarcher** [comment]
Did not had the time to test it yet, PHP 8 was released 4 days ago

**Comment by ashokbaruaakas** [comment]
> Did not had the time to test it yet, PHP 8 was released 4 days ago

Thank you for answering me. It's working.. 😍️😍️😍️

![image](https://user-images.githubusercontent.com/55571706/100755314-41098580-3416-11eb-8f8a-909f9c466aed.png)

**Comment by ashokbaruaakas** [comment]
> Did not had the time to test it yet, PHP 8 was released 4 days ago

Thank you for answering me. It's working.. 😍️😍️😍️

![image](https://user-images.githubusercontent.com/55571706/100755314-41098580-3416-11eb-8f8a-909f9c466aed.png)
