### ISSUE TITLE
Bug: Weird MySQL sock issue

### ISSUE THREAD

**Issue by ctsstc** [cpriego/valet-linux#313]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Pop! OS 20.20          | 7.4.11       | 2.2.19         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
This may be more of a Laravel & MySQL issue, and not even related at all, but I figured I would submit it in case anyone else runs across this, or maybe there's some type of documentation that could be added or some sock problem that could be fixed.

```
SQLSTATE[HY000] [2002] No such file or directory
```

> https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

I can access the DB with `./artisan tinker` but the live app doesn't work.

**What was supposed to happen?**
Should connect to the DB and function properly.

**What actually happened?**
Seems to be a socket issue, cannot connect to DB to execute calls.

**How to reproduce this?**
Opening up a site and causing a DB query to occur causes this error.

**What is the solution?**
Changing the `DB_HOST` from `localhost` to `127.0.0.1` seems to fix this issue.

**Sources**
- Laravel
- MySQL
- https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

**Comment by jmarcher** [comment]
Do you have localhost as a host in your dns resolver file? (note that localhost is just an alias of 127.0.0.1)

**Comment by ctsstc** [comment]
Just checked `/etc/hosts` and confirmed `localhost` was in there.

Feel free to close this out, maybe it will document the fix for someone down the road.
Didn't know if anyone had a clue about it though off hand, seemed weird.
Apparently if the db is set to localhost it will try to use a sock, which may not exist on my system?
