### ISSUE TITLE
Bug: `valet secure` secures all projects as root.test

### ISSUE THREAD

**Issue by njenga55** [cpriego/valet-linux#314]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: ubuntu 20.04          | 8.0       | 2.2.19         |

When I run **valet link** , it picks the current working directory(folders) name correctly, but when i run **valet secure**, all projects are secured as **root.test** , but opening this on the browser doesn't work. running **valet secure domain.test** doesn't throw an error on the terminal, but opening the browser the certificate generated is invalid. 

the expected behavior is **valet secure** should secure the current folder,

**Comment by rnscode** [comment]
run 
`valet secure [diretory]`
example
`valet secure domain`
