### ISSUE TITLE
Bug: 'valet install' command returning 'line 36: php: command not found'

### ISSUE THREAD

**Issue by fabian-murillo** [cpriego/valet-linux#317]
**Basic info**

| Pop!_OS 20.10 | PHP Version 8.0.1 | Valet version v2.2.19 | 

- [ yes ] I've checked the issue queue and could not find anything similar to my bug.
- [ I think so? ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ I can't run "valet fix"] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
The "valet install" command is not working.

**What was supposed to happen?**
A successful installation of the Valet Linux package.

**What actually happened?**
Attempting to run the command "valet install" returned:
`$HOME/.config/composer/vendor/bin/valet: line 36: php: command not found`

**How to reproduce this?**
- Install Homebrew package manager for Linux
- Install PHP using Homebrew
- Install Composer using Homebrew
- Install required packages  using: `sudo apt-get install network-manager libnss3-tools jq xsel`
- Install Valet Linux using: `composer global require cpriego/valet-linux`

**What is the solution?**
I have no idea. I've only ever installed and used Valet on Mac OS. Only recently have I switched over to Linux and I still have so much to learn.

**Sources**
People from the following thread commented and said to open a new issue:
[https://github.com/cpriego/valet-linux/issues/35](url)

So, I did...

**Additional Information**

Admittedly I did not install the "PHP extensions" nor the "Optional Packages" referenced in the 
valet linux requirements, see [https://cpriego.github.io/valet-linux/requirements](url)

This is my first time opening an issue, I tried my best, hope it's decent.

**Comment by jmarcher** [comment]
Homebrew is not supported. You need to install PHP with the package manager that your distro provides.
