### ISSUE TITLE
Bug: No *.[domain] URL will load?

### ISSUE THREAD

**Issue by ketchums** [cpriego/valet-linux#318]
**Basic info**

Arch Linux 2021.01.01 | 8.0 | 2.2.19

I've checked the issue queue and could not find anything similar to my bug. I'm on the latest version of valet-linux. I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
No site is loading that is registered under valet links. I have tried to ping *.domain but always get "Name or service not known", IE no reply.

**What was supposed to happen?**
It should route the URL properly and display the site.

**What actually happened?**
Server not found in Firefox. Isn't able to route the domain properly.

**How to reproduce this?**
God knows, it seems specific with Arch?

**What is the solution?**
I'm not familiar enough with this project.

**Comment by drewwalton19216801** [comment]
Running fully updated Manjaro testing branch, works fine for me. What is the output of `valet status`?

**Comment by ketchums** [comment]
Both PHP-FPM and NGINX are running when running `valet status`.

**Comment by drewwalton19216801** [comment]
In case this helps anyone else with a similar issue, I noticed valet having major troubles with AppArmor, so I had to add the following to /etc/apparmor.d/local/usr.sbin.dnsmasq:

`/opt/valet-linux/dns-servers r,
/proc/sys/kernel/osrelease r,
/proc/1/environ r,
/proc/cmdline r,`

**NOTE:** this is on a Gentoo box that uses systemd and AppArmor (for snapd) and using my own [Gentoo-specific valet-linux fork](https://packagist.org/packages/drewwaltonstech/valet-gentoo).

**Comment by ahangarha** [comment]
I sometimes face with this issue. I see this issue is closed but I don't find solution to it.

Valet shows everything in place. links are there, ssl is active, everything looks set in place but nothing gets open.

**Comment by ahangarha** [comment]
I am running Ubuntu 20.04 and face with this issue. I have noticed while everything looks fine and all required services are running as expected but after restarting the machine, no domain gets properly linked to the respected propject.

So far, I fix the issue by running `valet install` again. So far haven't seen any side effect by running this command again. But it might be a good hint towards finding and fixing this issue.
