### ISSUE TITLE
Bug: Valet share doesn't use the specified port

### ISSUE THREAD

**Issue by FaycalBorsali** [cpriego/valet-linux#319]
**I changed the default port to 8888, when I share my site, it maps it to my local machin but on port 80**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 20.04.1 LTS (Focal Fossa)          | 8.0.1       | 2.2.19         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `Valet v2.2.19`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.
-- doesn't apply --

**What is the problem?**
The share command doesn't take into consideration the changed port, it always maps to port 80

**What was supposed to happen?**
When I run `valet port 8888` and later do a `valet share` I should get
`Forwarding                    http://xxxxxxx.ngrok.io -> http://fay.test:8888`

**What actually happened?**
The port was changed successfully but when I share, I get
`Forwarding                    http://xxxxxxx.ngrok.io -> http://fay.test:80 `

**How to reproduce this?**
fresh install of laravel valet
> `valet port 8888`
> `cd path/to/sites/` and `valet park`
> `cd path/to/sites/my-awesome-website` and `valet share`

**What is the solution?**
When sharing, valet should check for the specified port in configuration and use it

**Sources**
-- None --

**Comment by jmarcher** [comment]
What are the contents of ~/.valet/config.json?

**Comment by jmarcher** [comment]
I reproduced the problem on my machine, v2.2.23 should fix this

**Comment by FaycalBorsali** [comment]
I just tried it, it works and just wanted to say thank you
