### ISSUE TITLE
CA PEM file not created

### ISSUE THREAD

**Issue by suraj-at-skryptech** [cpriego/valet-linux#320]
CA PEM file is not created. I'm using valet secure the individual certificates are there but the CA file is missing.

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 20.04         | 8.0.2       | 2.2.13         |

- [ x ] I've checked the issue queue and could not find anything similar to my bug.
- [ x ] I'm on the latest version of valet-linux (`valet --version`): `2.2.13`
- [ x ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**Comment by chiptu** [comment]
Did the issue have been fixed in recent release?

**Comment by anotherfrontendguy** [comment]
The exact same thing is happening for me.

| Distro        | PHP Version | Valet Version|
| :-------------- | :----------------- | :------------------- |
| Pop!_OS 20.10   | 7.4.9  | 2.2.25 |

The `~/.valet` folder exists and has the individual certificates inside the `Certificates` folder. The `CA` folder is missing completely.

Also sorry for commenting on a closed issue but I couldn't find a solution to this.

(This happens to me on a clean/fresh install of Valet 2.2.25)
