### ISSUE TITLE
Bug: Jetstream-based app not working

### ISSUE THREAD

**Issue by sinnrrr** [cpriego/valet-linux#322]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ----------------------------------- | ----------------- | ----------------- |
| Pop Os 20.04                     | 8.0.2             | 2.2.23            |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`)
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Serving laravel application with Jetstream is failing

**What was supposed to happen?**
Correct serve

**What actually happened?**
Created fresh application using `laravel new test --jet`. After linking it to the valet (`valet link`) went to http://test.test. Here is the screenshot of the error:

![image](https://user-images.githubusercontent.com/25615887/108519905-c6445e00-72d2-11eb-94f3-7842229c1297.png)

After taking some considerations, decided to make a fresh laravel app without jetstream and all works fine.

NOTE: database connection is established, migrations are run successfully.
Tried full reinstall of valet, but that didn't fix this.

**How to reproduce this?**
`laravel new test --jet`

**Comment by jmarcher** [comment]
Which Database connection are you using? It seems that your PHP-FPM does not have the same drivers as your PHP-CLI

**Comment by sinnrrr** [comment]
Latest 2 tracebacks are:

1) public/index.php:52
`
...
$response = tap($kernel->handle(

    **$request = Request::capture()** // this line

))->send();
`

2) .../composer/vendor/cpriego/valet-linux/server.php:232
`
...
chdir(dirname($frontControllerPath));

**require $frontControllerPath;** // this line
`

**Comment by sinnrrr** [comment]
> Which Database connection are you using? It seems that your PHP-FPM does not have the same drivers as your PHP-CLI

mysql

**Comment by jmarcher** [comment]
I just did that and it works for me. Can you do the following, create a new project with an index.php and 
```
<?php
phpinfo();
```

And paste the result here.

**Comment by sinnrrr** [comment]
```

PHP Version 7.4.15
--



```

**Comment by jmarcher** [comment]
I meant the whole result, so I may see which extensions are being loaded or not.

**Comment by sinnrrr** [comment]
all, that is allowed to paste here is: 
```
PHP Version 7.4.15
--

attaching the full screenshot of the output:
![test1 test_](https://user-images.githubusercontent.com/25615887/108524468-b8450c00-72d7-11eb-9530-7d4f82c8f4f5.png)

**Comment by sinnrrr** [comment]
https://ibb.co/F6JxdhW

**Comment by sinnrrr** [comment]
I tried installing php7.4-mysql, and that error now has gone, but here is another one, that I don't think is related to this issue

**Comment by jmarcher** [comment]
As suspected, you need to enable the pdo_mysql extension.

Edit your php.ini file (most cases in /etc/php/php.ini) and search for `;extension=pdo_mysql.so` and remove the ;

**Comment by jmarcher** [comment]
Oh glad to see you solved this, then open a new issue please :)

**Comment by sinnrrr** [comment]
there is just that:
```
Illuminate\Database\QueryException
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `sessions` where `id` = j918IDIJNhBtG8LgsOvJFuZgfrGZLXrP2aIqOJPh limit 1)
```

I don't think that this is related to valet :)

**Comment by jmarcher** [comment]
No but if your mysql-server is installed locally try with DB_HOST=127.0.01 (or add `127.0.0.1 localhost` into your /etc/hosts file) this is a common problem.
