### ISSUE TITLE
Bug: Arch doens't have which installed for default and valet throw error "Compatible package manager wans't found"

### ISSUE THREAD

**Issue by facundopanizza** [cpriego/valet-linux#323]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ---------------- | ------------- |
| Arch                 | 2021.02.01  | 8.0.2         | 2.2.5

- [x]  I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Arch doens't have which installed by default anymore so when you try to use the command valet it says that no package manager was found, it should say that which is not installed or other solution could be add which as a dependency in the requirements list for arch

**What was supposed to happen?**
valet command should tell that which is nos installed

**What actually happened?**
valet throw exception telling that it doesn't found a package manager compatible

**How to reproduce this?**
Just install any new version of arch or remove which from your system

**What is the solution?**
Just add which in the requirements and make a better error message.

**Comment by jmarcher** [comment]
Te escribo en español porque no entendí que es lo que quisiste decir. Primero la versión de Valet no puede ser esa, recién estamos por la version 2.

Dime que pasos estás siguendo porque no entiendo bien que comando es que estás ejecutando que te da ese error. Y lo mejor es poner aqui o unos screenshots o el output de los comandos para tener más ideas.

**Comment by facundopanizza** [comment]
Perdon se me movieron los datos en la table la version de valet es la v2.2.25. PHP es 8.0.2 y version de Arch es 2021.02.01

Respecto al error:

Esto se repite en varios archivos pero este seria un ejemplo:
https://github.com/cpriego/valet-linux/blob/master/cli/Valet/PackageManagers/Pacman.php

En el metodo isAvailable que se utiliza para ver si existe el package manager y tambien se utiliza en otros lados para ver si esta instalado systemd.

Bueno en ese metodo se utiliza un programa que se llama which que te dice donde esta instalado el programa, y valet utiliza a which para saber si un programa esta instalado.

Ahora el problema es que Arch Linux dejo de venir con which instalado por defecto y por lo tanto valet nunca puede reconocer si el programa esta instalado y siempre falla diciendo que no encontro un package manager disponible.

Yo creo que con agregar al programa "which" entre los requisitos de instalacion en Arch Linux alcanza.

O tambien podrian checkear si esta instalado which y de no estarlo tirar un error como "which no esta instalado"

**Comment by jmarcher** [comment]
Ah genial, muchas gracias en la próxima versión arreglaré esa precondicón, también tendré que alcarar en la documentación para que quede claro.

**Comment by facundopanizza** [comment]
Gracias a vos, suerte
