### ISSUE TITLE
Bug: valet/linux stopped working after installing pgAdmin4 web interface

### ISSUE THREAD

**Issue by jamessingizi** [cpriego/valet-linux#324]
**Basic info**

| Distro (Ubuntu 20.04) | PHP 8.0| 2.2.5|
| ------------------------- | ----------- | ------------- |

**What is the problem?**
Valet was running on my machine and when I installed pgAdmin4 web interface valet stopped working. I thought its because of apache taking port 80 and i stopped apache to clear port 80 but that did not help. I tried removing valet and reinstalling but that did not help either

**How to reproduce this?**
install valet linux and then install pgAdmin4. vale linux will stop working

**Comment by jmarcher** [comment]
Hi James, I wouldn't recommend installing pgAdmin with Ubuntu's package manager, the dependencies are not the same as Valet, you will need to download it and put it in your parked directory.

Make 100% sure that apache is not running (maybe even uninstall it or change the default port) and try running: `valet restart` this should work
