### ISSUE TITLE
PHP Deprecated:  Required parameter $https follows optional parameter $port

### ISSUE THREAD

**Issue by curtsheller** [cpriego/valet-linux#326]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Pop{_!OS 20.04     |    7.4       | 2.2.25         |

- [x ] I've checked the issue queue and could not find anything similar to my bug.
- [x ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

`valet fix` command returns 'Command "fix" valet not defined. There is no "fix" common in version 2.2.25.

```
❯ valet status
PHP Deprecated:  Required parameter $https follows optional parameter $port in /home/curtsheller/.config/composer/vendor/cpriego/valet-linux/cli/valet.php on line 82

Deprecated: Required parameter $https follows optional parameter $port in /home/curtsheller/.config/composer/vendor/cpriego/valet-linux/cli/valet.php on line 82
Php7.4-fpm is running...
Nginx is running...
```

*Here is line 82:*
```
$app->command('port [port] [--https]', function ($port = null, $https) {
    if ($port === null) {
        info('Current Nginx port (HTTP): ' . Configuration::get('port', 80));
        info('Current Nginx port (HTTPS): ' . Configuration::get('https_port', 443));

        return;
    }
```
This is beyond my "pay grade". Just thought you might like to know.

Sites are running OK on my local Pop!_OS 20.04 computer.

And, thanks for maintaining "valet-linux'. Allowed me to move development from a "constantly throttling new iMac"
Curt Sheller

**Comment by curtsheller** [comment]
This is triggered in PHP 8 as deprecated notice.

#### PHP 8.0: Deprecate required parameters after optional parameters in function/method signatures

I found info here: https://php.watch/versions/8.0/deprecate-required-param-after-optional for options to fix. I don't know enough to know if a change would break something, I did the following my local copy.

```
line 82: $app->command('port [port] [--https]', function (string $port = null, $https) {
```
There were other options.

**Comment by jmarcher** [comment]
This should be fixed on the next version
