### ISSUE TITLE
Bug: valet status shows php7.4-fpm is stopped Nginx is stopped

### ISSUE THREAD

**Issue by daross888** [cpriego/valet-linux#328]
Hi all,

I've installed linux-valet it was all good, added my project and linked it but the site is unreachable, when I do valet status I get:

daross@DESKTOP-5FV4JGH:~$ valet status
Php7.4-fpm is stopped...
Nginx is stopped...

however when I do service php7.4-fpm I get this:

daross@DESKTOP-5FV4JGH:~$ service php7.4-fpm status
 * php-fpm7.4 is running

Have anyone had this issue before?

**Comment by jmarcher** [comment]
Can you give more information about which distro are you using? And what kind of error comes up when visiting you linked sites?
