### ISSUE TITLE
Feature: Support "proxy" Command

### ISSUE THREAD

**Issue by benjamindoe** [cpriego/valet-linux#330]
| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Manjaro 18.3          | 8.0.7       | 2.2.26         |

Valet Linux doesn't appear to support the `proxy` command. Upstream Valet has a feature that allows you to proxy other local services such as elasticsearch or mailhog. Are there any plans to introduce this command to Valet Linux?

**Comment by jmarcher** [comment]
I do not have the time right now but may be introduced in the future. Will leave the issue open in order to remind me.

**Comment by kodmanyagha** [comment]
It seems the problem still exist. I'm using ubuntu 22. It is creating `/home/user/.valet/Nginx/site.host` correctly but when list the proxies (`valet proxies`) it shows nothing.
