### ISSUE TITLE
Bug: Php-fpm is stopped

### ISSUE THREAD

**Issue by syofyanzuhad** [cpriego/valet-linux#331]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Ubuntu 20        | 8.0.0 & 7.4.21       | 2.2.26         |

- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [ ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
A description of what you think the problem is.
![Screenshot from 2021-07-09 07-17-22](https://user-images.githubusercontent.com/52684582/125005840-f4121f80-e086-11eb-98ff-fc85a76dea9a.png)

**What was supposed to happen?**
A description of what you think was supposed to happen.

**What actually happened?**
A description of what actually happened.

**How to reproduce this?**
A step by step guide on how to reproduce this issue.

**What is the solution?**
A description of the proposed solution.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by jmarcher** [comment]
I need more info. Why are you running valet use without a version identifier?

Are you using native Ubuntu or WSL?

**Comment by josegus** [comment]
Same problem here, I'm using native Ubuntu 20.04

**Comment by KasparRosin** [comment]
Had the same issue.
Deleted valet.sock and called `valet start` again. After that it worked again.

**Comment by LogicSatinn** [comment]
_Deleted valet.sock and called valet start again. After that it worked again_

@jmarcher  Tried this. It's still not working. I'm using wsl with ubuntu.
