### ISSUE TITLE
Error: Call to undefined method ValetDriver::assign() when using PHP 7.4

### ISSUE THREAD

**Issue by immercegmbh** [cpriego/valet-linux#333]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Pop!_OS 21.04                   | 7.4.21          | 2.2.26            |
 
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `Valet v2.2.26`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature: `Command "fix" is not defined.`

I have installed PHP 7.0, 7.1, 7.2, 7.4, and 8.0 form the `ppa:ondrej/php` repository.

I've created a "Sites" directory and registered it using the `valet park` command.
Inside the sites directory, I've added a test site called "phpinfo", in which I've added an index.php file which calls `phpinfo()`.

**What is the problem?**
Going to phpinfo.test in the browser shows the phpinfo output on the first page load. Loading the page again shows an error.
It always works on the first page load after every restart of Valet (`valet restart`), but on consecutive page loads, the error occurs.

This only happens with PHP 7.4, with all other versions it's working fine.

**What was supposed to happen?**
index.php should load normally.

**What actually happened?**
An error occurs on consecutive page loads :
```
( ! ) Fatal error: Uncaught Error: Call to undefined method ValetDriver::assign() in /home/johndoe/.config/composer/vendor/cpriego/valet-linux/server.php on line 190
( ! ) Error: Call to undefined method ValetDriver::assign() in /home/johndoe/.config/composer/vendor/cpriego/valet-linux/server.php on line 190
Call Stack
#	Time	Memory	Function	Location
1	0.0000	356832	{main}( )	.../server.php:0
```

**Comment by jmarcher** [comment]
That error tells me that your PHP-CLI version is 8.

I do not believe that Valet works properly on PHP 8, did not had the time to test it.

**Comment by immercegmbh** [comment]
Thanks for you quick reply. Unfortunately I'm getting this error with PHP CLI 7.4 and 7.3 as well.
`/usr/bin/php => /etc/alternatives/php => /usr/bin/php7.4`

```
php -v
PHP 7.4.21 (cli) (built: Jul  1 2021 16:10:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

Changed symlink and also rebooted the OS.

**Comment by jmarcher** [comment]
Can you try disabling OPcache? It does not make a lot of sense for local development anyways

**Comment by immercegmbh** [comment]
Perfect, disabling OPcache fixed it.
Thank you.

**Comment by jmarcher** [comment]
Bitte 😃
