### ISSUE TITLE
Symfony 5.3+ support

### ISSUE THREAD

**Issue by kbond** [cpriego/valet-linux#334]
Symfony 5.3 introduced a Runtime component that extracts most the boilerplate from `public/index.php` into an auto-generated `vendor/autoload_runtime.php`.

`public/index.php` now looks like this:

```php
use App\Kernel;

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```

The runtime component expects the `$_SERVER['SCRIPT_FILENAME']` to be `public/index.php` but when using valet it's `~/.config/composer/vendor/cpriego/valet-linux/server.php`. This causes an error preventing you from loading your site in the browser.

I was able to get it to work by updating my `public/index.php` to the following:

```php
use App\Kernel;

if (defined('VALET_HOME_PATH')) {
    // using valet, hack to change the script filename for symfony/runtime
    $_SERVER['SCRIPT_FILENAME'] = __FILE__;
}

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```

I'm not sure if there is anything that can be done in valet to resolve this but wanted to report my workaround.

**Comment by jmarcher** [comment]
Can you tell me if the following works for you:
Look for the following file: `~/.config/composer/vendor/cpriego/valet-linux/cli/drivers/SymfonyValetDriver.php`
And go to the line 54 and replace it with this:

```php
$_SERVER['SCRIPT_FILENAME'] = $frontControllerPath;
return $frontControllerPath;
```

If you confirm this works for you I can update the Symfony driver on the next release.

**Comment by kbond** [comment]
Yes, that did work! I created a PR (#335).
