### ISSUE TITLE
Bug: upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by RianAsmara** [cpriego/valet-linux#339]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Ubuntu 20.04          | 7.4.3       | 2.2.23         |

- [v] I've checked the issue queue and could not find anything similar to my bug.
- [v] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [v] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Whenever i do POST. It's always return ```502 Bad Request```. Several days ago it's never happen.

**What was supposed to happen?**
i must return ```dd``` from controller

**What actually happened?**
```502 Bad Request```

**How to reproduce this?**
A step by step guide on how to reproduce this issue.

**What is the solution?**
A description of the proposed solution.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by RianAsmara** [comment]
here some log from ```~/.valet/log/nginx-error.log```

thank you

```
2021/08/12 13:47:35 [error] 6537#6537: *166 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin/pendaftar/pindah-prodi/009afb7f-2b88-4c71-9b84-30b1c7ece990 HTTP/1.1", upstream: "fastcgi://unix:/home/rap/.valet/valet.sock:", host: "pmb.unizar.test", referrer: "http://pmb.unizar.test/admin/pendaftar"
2021/08/12 13:50:39 [error] 6537#6537: *166 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin/pendaftar/pindah-prodi/009afb7f-2b88-4c71-9b84-30b1c7ece990 HTTP/1.1", upstream: "fastcgi://unix:/home/rap/.valet/valet.sock:", host: "pmb.unizar.test", referrer: "http://pmb.unizar.test/admin/pendaftar"
2021/08/12 13:50:42 [error] 6537#6537: *166 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin/pendaftar/pindah-prodi/009afb7f-2b88-4c71-9b84-30b1c7ece990 HTTP/1.1", upstream: "fastcgi://unix:/home/rap/.valet/valet.sock:", host: "pmb.unizar.test", referrer: "http://pmb.unizar.test/admin/pendaftar"
2021/08/12 13:54:17 [error] 6537#6537: *190 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin/pendaftar/pindah-prodi/009afb7f-2b88-4c71-9b84-30b1c7ece990 HTTP/1.1", upstream: "fastcgi://unix:/home/rap/.valet/valet.sock:", host: "pmb.unizar.test", referrer: "http://pmb.unizar.test/admin/pendaftar"
2021/08/12 13:54:31 [error] 6537#6537: *190 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin/pendaftar/pindah-prodi/009afb7f-2b88-4c71-9b84-30b1c7ece990 HTTP/1.1", upstream: "fastcgi://unix:/home/rap/.valet/valet.sock:", host: "pmb.unizar.test", referrer: "http://pmb.unizar.test/admin/pendaftar"
```

**Comment by jmarcher** [comment]
Can you add this to your nginx config inside your location / {}

```
    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;
```

Restart valet and try again
