### ISSUE TITLE
PHP Fatal error: Cannot declare class CommandLine

### ISSUE THREAD

**Issue by markocic** [cpriego/valet-linux#34]
`PHP Fatal error:  Cannot declare class CommandLine, because the name is already in use in /home/marko/.config/composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 43`
this is the error message that i get after typing valet install into the terminal

**Comment by cpriego** [comment]
You have installed the jmarcher/valet-linux, as it started as a fork of this very project there are conflicts with namespaces. The only option is to remove the other other valet-linux installation

**Comment by markocic** [comment]
You were right, that fixed it. Thanks
