### ISSUE TITLE
Bug: Pacman was unable to install

### ISSUE THREAD

**Issue by xvladqt** [cpriego/valet-linux#340]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Manjaro 21.1.2          | 7.3.1       | 2.2.29         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When `valet install`
```
Nginx was already enabled
Stopping nginx...
[php7.4-fpm] is not installed, installing it now via Pacman... 🍻
ошибка: не найдена цель: php7.4-fpm


In Pacman.php line 74:
                                              
  Pacman was unable to install [php7.4-fpm].  
                                              

install [--ignore-selinux]
```
**What was supposed to happen?**
Clear install manjaro, php, valet-linux. 

In manjaro repos, all php7.4- packages as php7-
php7.4-fpm, in repo as php7-fpm

**Comment by xvladqt** [comment]
@jmarcher yeap, but valet try install php7.4-fpm, was not exist in repo

**Comment by thatONEjustin** [comment]
happening on arch for php 8.2 fpm

**Comment by richbowen** [comment]
> happening on arch for php 8.2 fpm

Can confirm. It's trying to use pacman to install the Ubuntu php-fpm package name.

**Comment by ashdevelops** [comment]
Still an issue

**Comment by arcanna** [comment]
Still an issue for php8.2-fpm on Manjaro/Arch

**Comment by Kr0ks** [comment]
Go to the Valet folder composer/vendor/cpriego/valet-linux/cli and comment line 38: `PhpFpm::install();`

install php-fm manually instead, by running `pacman -S php-fm`
