### ISSUE TITLE
Fedora ethernet connected ,but no internet !!

### ISSUE THREAD

**Issue by Ok9xNirab** [cpriego/valet-linux#341]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Fedora - 34          | 7.4       | latest         |

**What is the problem?**
After install this package, My pc has no internet . But still ethernet connected.
Uninstall `valet-linux` is solved internet issue !!

This issue happen for this package .

**Comment by songlineboy** [comment]
Same for me. WiFi connects but no internet.

Ubuntu 20.04.03 lts / Valet Linux 2.2.29

Does anyone have a solution?

**Comment by jmarcher** [comment]
Can you paste the output of `cat /etc/resolv.conf` ?

**Comment by scpaklunltd** [comment]
Generated by NetworkManager
nameserver 127.0.0.53


But I have now uninstalled valet and have setup my sites manually :(

**Comment by zreyleo** [comment]
Maybe you are skiping a very important step that is setting selinux in permissive mode
Open `/etc/selinux/config`
Change `SELINUX=enforcing` to `SELINUX=permissive`
Reboot
