### ISSUE TITLE
Bug: Cannot run valet install - using asdf for php installation

### ISSUE THREAD

**Issue by dev-rroslan** [cpriego/valet-linux#342]
**Basic info**

ubuntu 20.04 using zsh
- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [ ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
php command to install not found on line 36 in /home/user/.asdf/install/php/8.0.12/,composer/vendor/bin/valet

**Comment by jmarcher** [comment]
Can you elaborate more? Is asdf a new Package Manager? if so it is not yet supported.
