### ISSUE TITLE
Bug: <Your-Title>

### ISSUE THREAD

**Issue by martintern** [cpriego/valet-linux#343]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 21.04          | 7.4       | 2.2.29         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `2.2.29`
- [x] I've run ~~`valet fix` and~~ `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
`valet use php@8.0` doesn't work.

**What was supposed to happen?**
It should make Valet use php8.0

**What actually happened?**
Error returned:

> Changing version failed
> 
> In Apt.php line 74:
>                                                
>   Apt was unable to install [phpphp@8.0-fpm].

**How to reproduce this?**
Try `valet use php@8.0` 

**What is the solution?**
I guess you'd have to change `phpphp@8.0-fpm` to `php@8.0-fpm`

**Sources**
I found out about the `use` command [here](https://gist.github.com/bgarrant/b9a2f7fb8ff06c9a45086359ded7a95e) and had success with this [workaround](https://gist.github.com/bgarrant/b9a2f7fb8ff06c9a45086359ded7a95e)

**Comment by jmarcher** [comment]
I do not use Ubuntu, I believe you need to use `valet use 8.0` 

Reference: https://packages.ubuntu.com/impish/any/php8.0

**Comment by martintern** [comment]
That works, thanks! 
So instead of a bug report it's a tutorial for me:-P
