### ISSUE TITLE
valet-linux Website Logo 404

### ISSUE THREAD

**Issue by RafaelKr** [cpriego/valet-linux#344]
Hey! I created an issue in the valet-linux-docs repo: https://github.com/cpriego/valet-linux-docs/issues/5
There seems to be not much activity, especially cpriego's account (I intentionally don't tag him) seems pretty inactive. So I would like to kindly ask if the docs-repo can also be maintained by the same people maintaining this repo?

**Comment by jmarcher** [comment]
I maintain this repo and the docs cpriego is not maintaining this anymore

Rafael Kraut ***@***.***> schrieb am Di., 2. Nov. 2021, 21:42:

**Comment by RafaelKr** [comment]
Thanks!
