### ISSUE TITLE
Bug: Cannot switch PHP versions

### ISSUE THREAD

**Issue by dima2306** [cpriego/valet-linux#349]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Fedora 35          | 8.0.13       | 2.2.29         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-linux (`valet --version`): 2.2.29
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Cannot switch PHP versions using `valet use <version>`

**What was supposed to happen?**
PHP version should have been changed.

**What actually happened?**
I think nothing. As I'm still getting errors caused by the new PHP 8 version.

**How to reproduce this?**
As Fedora 35 comes with PHP 8 by default, I used [this wizard](https://rpms.remirepo.net/wizard) to install PHP 7.4.
There is also another source of how to install PHP 7.4 on Fedora 35: https://computingforgeeks.com/how-to-install-php-74-on-fedora but I have no luck following that tutorial.

The main fact is that 7.4 is installed on the system and the `php74 --version` command proves this:
```bash
PHP 7.4.26 (cli) (built: Nov 16 2021 15:31:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

And after changing the PHP version to 7.4 using the `valet use 74-php` command I get the info:

```bash
Changing php-fpm version...
This does not affect php -v.
Stopping php74-php-fpm...
Disabling php74-php-fpm...
Php74-php-fpm has been disabled
Php74-php-fpm was already disabled
Restarting php74-php-fpm...
Enabling php74-php-fpm...
Php74-php-fpm has been enabled
php-fpm version successfully changed! 🎉
```

**What is the solution?**
N/A

Maybe I'm missing something. Can someone guide me on how to change PHP version?

**Comment by dima2306** [comment]
Any news regarding this?

**Comment by jmarcher** [comment]
That looks like a weird syntax for `valet use`, please note that this command uses the `version` part as an alias for the package manager if the package  `php<version>-fpm` (note the pattern) does not exists there is not much we can do.

**Comment by dima2306** [comment]
Hey, @jmarcher Thanks for the reply.

Yes, I noticed the pattern and this is why I pass "74-php" to `valet use`. Currently in my system PHP 7.4 is present like this:
```bash
php74-runtime-1.0-3.fc35.remi.x86_64
php74-php-pecl-grpc-1.43.0~RC1-1.fc35.remi.x86_64
php74-1.0-3.fc35.remi.x86_64
php74-php-pecl-mysql-1.0.0-0.24.20201210.6ca4fa4.fc35.remi.x86_64
php74-php-json-7.4.27-1.fc35.remi.x86_64
php74-php-common-7.4.27-1.fc35.remi.x86_64
php74-php-pdo-7.4.27-1.fc35.remi.x86_64
php74-php-cli-7.4.27-1.fc35.remi.x86_64
php74-php-fpm-7.4.27-1.fc35.remi.x86_64
php74-php-mbstring-7.4.27-1.fc35.remi.x86_64
php74-php-opcache-7.4.27-1.fc35.remi.x86_64
php74-php-sodium-7.4.27-1.fc35.remi.x86_64
php74-php-xml-7.4.27-1.fc35.remi.x86_64
php74-php-7.4.27-1.fc35.remi.x86_64
php74-php-mysqlnd-7.4.27-1.fc35.remi.x86_64
```

This is the report of `rpm -qa | grep php74`.

So what else can I do, valet still uses 8.0.x

**Comment by dima2306** [comment]
@jmarcher Hey,
Maybe you can merge this PR here also?
https://github.com/laravel/valet/pull/1192
https://github.com/laravel/valet/pull/1198
https://github.com/laravel/valet/pull/1201

I've some company projects which can't run newer PHP/Laravel versions. So, I'm stuck with old ones and literally, this is what I need, to serve some apps with specific PHP version.

Will appreciate the updates from you or any other maintainer in the free time.

**Comment by jmarcher** [comment]
Thanks, I do not have the time at the moment to merge that code.
Note that is not that simple because our codebase is already very different

I really want to see this on Valet-Linux, when I find the time will add it for sure, but if someone has the time right now it would help a lot
