### ISSUE TITLE
bash: valet: command not found

### ISSUE THREAD

**Issue by pavinthan** [cpriego/valet-linux#35]
bash: valet: command not found

**Comment by TheNodi** [comment]
Without many information, I think you didn't add composer's bin directory to your $PATH.

Usually you can do that by adding the following line to the end of `~/.profile` file and restart your terminal:
```
PATH="$HOME/.composer/vendor/bin:$PATH"
```
Although it depends on your system.

**Comment by UksusoFF** [comment]
If composer installed via apt it have other vendor path. You can find them by ```composer global help```.
```
echo "export PATH=$PATH:$HOME/.config/composer/vendor/bin" >> ~/.bashrc
source ~/.bashrc
```

**Comment by cpriego** [comment]
If you don't want to add composer global to your path just run the valet "bin" directly. You can use this command to achieve that
```
test -d ~/.composer && bash ~/.composer/vendor/bin/valet install || bash ~/.config/composer/vendor/bin/valet install
```

**Comment by cpriego** [comment]
This is now solved in the [wiki](https://github.com/cpriego/valet-linux/wiki/FAQ#why-cant-i-run-valet-install).

**Comment by core45** [comment]
This what mentioned UksusoFF worked for me in Ubuntu 18.04:
`echo "export PATH=$PATH:$HOME/.config/composer/vendor/bin" >> ~/.bashrc
source ~/.bashrc`
And in my opinion it should be mentioned in #Installation section on the main page.

**Comment by jmarcher** [comment]
Usually composer users already have the composer vendor/bin folder inside the PATH variable.

**Comment by heroh9** [comment]
~/.config/composer/vendor/bin/valet: line 36: php: command not found

I keep getting this, and I followed all the aforementioned solutions

**Comment by jmarcher** [comment]
What does `which php` show as result?

How are you using PHP CLI?

**Comment by meisaputra** [comment]
this is mine...
~/.config/composer/vendor/bin/valet: line 36: php: command not found
```
~$ which php
/opt/lampp/bin/php
```

**Comment by afiqhamzah** [comment]
any luck with this ? 

~/.config/composer/vendor/bin/valet: line 36: php: command not found

```
~$ which php 
~/.linuxbrew/bin/php
```

**Comment by jmarcher** [comment]
Please open a new issue.
BTW: Homebrew is not supported yet.

**Comment by afiqhamzah** [comment]
> Please open a new issue.
> BTW: Homebrew is not supported yet.

thanks for the reply, im glad i'd asked

**Comment by Sunwarul** [comment]
> Without many information, I think you didn't add composer's bin directory to your $PATH.
> 
> Usually you can do that by adding the following line to the end of `~/.profile` file and restart your terminal:
> 
> ```
> PATH="$HOME/.composer/vendor/bin:$PATH"
> ```
> 
> Although it depends on your system.

Thanks, worked here.

**Comment by en1tan** [comment]
Getting an error with this
`$HOME/.config/composer/vendor/bin/valet: line 36: php: command not found`

**Comment by berry807** [comment]
> Getting an error with this
> `$HOME/.config/composer/vendor/bin/valet: line 36: php: command not found`

Getting the same thing over here :(

**Comment by fabian-murillo** [comment]
I'm also receiving this same error:

`$HOME/.config/composer/vendor/bin/valet: line 36: php: command not found`

I am using linuxbrew, not sure if the above comments stating 'Hombrew is not yet supported' were in response to this error or the original poster's 'bash: valet: command not found' error. Will try to open a new issue now :crossed_fingers:

**Comment by jmarcher** [comment]
It is still the case, homebrew is still not supported. I started a beta branch a while ago but I do not have the time to finish it at the moment.

**Comment by suvrodattamitu** [comment]
PATH="$HOME/.composer/vendor/bin:$PATH"
is working fine

**Comment by Zar340** [comment]
When I run valet install command then this error occure but no any solution find .i 
  have also set the PATH directory.AppData\Roaming\Composer\vendor\bin\/../laravel/valet/valet: line 25: sudo: command not found
