### ISSUE TITLE
Bug: Always getting 502 Bad Gateway

### ISSUE THREAD

**Issue by sujit-baniya** [cpriego/valet-linux#353]
I've been using valet on ubuntu 20.  After each request, I'm getting `502 Bad Gateway`. Each time I need to run `valet restart`. 
After request the same loops continues. 

Please suggest how I could fix the issue. I've been frustrated with the 502 as I've to be ready to run the command after each request :P

**Comment by volkanersumer** [comment]
Same problem, but `valet restart` is not fixing my problem.

**Comment by matthewnessworthy** [comment]
same error, using debian bullseye

**Comment by danabrey** [comment]
This is sometimes fixed for me by running `rm ~/.valet/valet.sock` before `valet restart`

**Comment by sujit-baniya** [comment]
I've updated the example of nginx.conf that is working for me

**Comment by blobaugh** [comment]
I was receiving the same 502 response. I reinstalled and restarted valet- tried all sorts of tricks, to no avail. In the end, I realized that valet was not showing the real status of the php service. After manually starting I was able to connect without issues to sites.

The command I ran was: `sudo service php7.4-fpm start`
