### ISSUE TITLE
Bug: Cannot access external websites after restarting

### ISSUE THREAD

**Issue by danabrey** [cpriego/valet-linux#354]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 20.04.3         | 8.0.15       | 2.2.9         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**

For the past few weeks, restarting my system causes DNS to not work for anything apart from Valet-served `.test` domains, so I cannot access external websites. I can ping external IPs, but all name resolution is broken.

**What is the solution?**

At the moment, my only solution is running:

```
sudo rm /etc/resolv.conf
sudo ln -s /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
sudo systemctl restart systemd-resolve
```

This, however, obviously stopped Valet working. Running `valet install` then introduces the exact same problem as described.

Yesterday, I uninstalled Valet completely following the instructions at https://cpriego.github.io/valet-linux/#uninstalling, and then re-installed it. **This made both external and Valet DNS work, but upon restarting the same issue occurred.**

**Comment by danabrey** [comment]
Yes, that's the exact issue I experienced. I can no longer use valet-linux.

**Comment by geekfil** [comment]
I see similar behavior if the dnsmasq service is stopped.
Check if the service is running with the command "sudo service dnsmasq status" and restore it if necessary.

(sorry for my bad english)

**Comment by horlarme** [comment]
I faced the same issue but only after upgrading to Ubuntu 22.04

My solution was changing the configuration for dnsmasq (valet - /etc/dnsmasq.d/valet) to only route .test to 127.0.0.1 instead of all requests.

Steps
- `sudo nano /etc/dnsmasq.d/valet`
- change address=/./127.0.0.1
- to address=/.test/127.0.0.1
- then restarted all services related to valet using `sudo systemctl restart NetworkManager dnsmasq.service valet-dns.service`

**Comment by FaycalBorsali** [comment]
I had the same issue and my `/etc/dnsmas.d/valet` already had the correct address but I still experienced the same problem.

I just shared [a solution that could help you](https://github.com/cpriego/valet-linux/issues/368#issuecomment-1123658155)

**Comment by skino2019** [comment]
> * sudo systemctl restart NetworkManager dnsmasq.service valet-dns.service

this kind of worked for me. but i have to run `sudo systemctl restart NetworkManager dnsmasq.service valet-dns.service ` every time i restart, lock or shutdown my machine

Really hope they fix this soon. im not a fan for Laravel Sail and docker yet lol.

**Comment by iskrisis** [comment]
@skino2019 have you found solution to this? Thanks!
