### ISSUE TITLE
Cert Authority Name Invalid - Valet secure

### ISSUE THREAD

**Issue by C4pt4inM** [cpriego/valet-linux#358]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ---------------------------- | ----------- | ------------- |
| Manjaro 21.2          | 7.4  fpm    | 2.2.29         |

- [ ] The issue is reported before. tried provided solution from github but not worked.
- [ ] Searched on internet and did those things too, reinstall valet, reboot computer, use incognito, restartt browser, etc.
- [ ] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [ ] I've run `valet update` and  `valet install` before submitting my issue/feature.
- [ ] I manage 3 different linux servers, In one I manually installed certificates using `certbot`. certbot did not work with valet because domain is not ending with valid public suffix

**What is the problem?**
Running `valet secure` assings certificate to website but site is not reachable with SSL.. site throws error `NET::ERR_CERT_AUTHORITY_INVALID`

**What was supposed to happen?**
Website should be function with a valid SSL

**What actually happened?**
browser throing error `NET::ERR_CERT_AUTHORITY_INVALID`

**How to reproduce this?**
- create a folder
- do `valet link` 
- install wordpress 
- wordpress should be running without https
- do `valet secure`
- open wordpress site

**What is the solution?**
No idea

**Sources**
--

After I found out about `valet-linux` not only I use it for Laravel, I use it for every PHP based website I develop locally. so solution to this is very important to me.

**Comment by drewwalton19216801** [comment]
This is still an issue in Fedora 38.
