### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by pavinthan** [cpriego/valet-linux#36]
502 Bad Gateway

OS : Ubunthu 16.10
PHP : PHP 7.1.2-4+deb.sury.org~yakkety+1 (cli) (built: Mar  2 2017 10:40:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.2-4+deb.sury.org~yakkety+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by TheNodi** [comment]
Try to check the status of PHP-FPM and nginx to see if they're running:
```
sudo service php7.0-fpm status
sudo service nginx status
```

And check the error logs. Probably a permission error on php-fpm socket file.

**Comment by pavinthan** [comment]
● php7.1-fpm.service - The PHP 7.1 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.1-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-03-17 08:14:54 +0530; 2min 55s ago
     Docs: man:php-fpm7.1(8)
 Main PID: 4185 (php-fpm7.1)
   Status: "Processes active: 0, idle: 2, Requests: 0, slow: 0, Traffic: 0req/sec"
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/php7.1-fpm.service
           ├─4185 php-fpm: master process (/etc/php/7.1/fpm/php-fpm.conf)
           ├─4186 php-fpm: pool www
           └─4187 php-fpm: pool www

Mar 17 08:14:54 pavinthan systemd[1]: Starting The PHP 7.1 FastCGI Process Manager...
Mar 17 08:14:54 pavinthan systemd[1]: Started The PHP 7.1 FastCGI Process Manager.



● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-03-17 08:14:55 +0530; 3min 9s ago
 Main PID: 4244 (nginx)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/nginx.service
           ├─4244 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─4245 nginx: worker process
           ├─4246 nginx: worker process
           ├─4247 nginx: worker process
           └─4248 nginx: worker process

Mar 17 08:14:55 pavinthan systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 17 08:14:55 pavinthan systemd[1]: Started A high performance web server and a reverse proxy server.

**Comment by TheNodi** [comment]
They looks fine, check the errors log. They are the files `/var/log/nginx/*error.log` (every file that end with error.log). Also valet redirects it's log into `~/.valet/Log/nginx-error.log`.

**Comment by TheNodi** [comment]
Closed for inactivity.

**Comment by hamidafghan** [comment]
I had the same issue when I upgrade to Ubuntu 20.04, I solved by running `valet install`.

**Comment by kattasainaveen** [comment]
i entered in my phone saying the error encountered was: dial tcp [::1] :4444 connect: connection
and in terminal 502 bad gateway
please help
