### ISSUE TITLE
Bug: missing `--secure` flag on `valet link`

### ISSUE THREAD

**Issue by codepuncher** [cpriego/valet-linux#369]
**Basic info**

Versions are not applicable; all hosts, distros, etc.

**What is the problem?**
Missing upstream `--secure` flag on `valet link` command.

**What was supposed to happen?**
To also secure the site without running additional `valet secure` command.

**What actually happened?**
Error of `The "--secure" option does not exist.`

**How to reproduce this?**
Just run `valet link --secure`

**What is the solution?**
Implement the `--secure` flag

**Sources**
I am using a [tool](https://github.com/roots/trellis-cli/) to create Bedrock (WordPress fork) sites.
It runs `valet link --secure` but since `valet-linux` is missing this flag, the command fails.
Related open issue on mentioned tool: https://github.com/roots/trellis-cli/issues/186

**Comment by codepuncher** [comment]
Hi @jmarcher,

Why was this issue closed and marked as completed? I don't see the `--secure` flag available in the sourcecode.

Thanks

**Comment by codepuncher** [comment]
Hi @Adesin-fr, congratulations on becoming the new maintainer.
Looking forward to the new v3 `isolate` that you are working on.

Could you review this issue and my PR? I believe this should not have been closed.

Thanks

**Comment by Adesin-fr** [comment]
Hi,
It seems that the PR was not merged ! 
I'll try to marge it in the next few days, should not take too long !
