### ISSUE TITLE
Valet doesn't use the same .ini files as `php artisan serve`

### ISSUE THREAD

**Issue by astlouisf** [cpriego/valet-linux#37]
I was doing the following [laracasts tutorial](https://laracasts.com/series/laravel-from-scratch-2017) and installed valet-linux following the procedure for Fedora.

When I reached the moment to add db (postgresql) support to my website, `php artisan migrate` worked flawlessly but I was getting `PDOException in Connector.php line 68: could not find driver` when serving it.

phpinfo() revealed the following informations

```
Loaded Configuration File
-------------------------
/etc/php.ini

Scan this dir for additional .ini files
---------------------------------------
/etc/php.d

Additional .ini files parsed
----------------------------
/etc/php.d/20-bz2.ini, /etc/php.d/20-calendar.ini, /etc/php.d/20-ctype.ini, /etc/php.d/20-curl.ini, /etc/php.d/20-dom.ini, /etc/php.d/20-exif.ini, /etc/php.d/20-fileinfo.ini, /etc/php.d/20-ftp.ini, /etc/php.d/20-gd.ini, /etc/php.d/20-gettext.ini, /etc/php.d/20-iconv.ini, /etc/php.d/20-intl.ini, /etc/php.d/20-json.ini, /etc/php.d/20-mbstring.ini, /etc/php.d/20-mcrypt.ini, /etc/php.d/20-pdo.ini, /etc/php.d/20-phar.ini, /etc/php.d/20-posix.ini, /etc/php.d/20-shmop.ini, /etc/php.d/20-simplexml.ini, /etc/php.d/20-sockets.ini, /etc/php.d/20-sqlite3.ini, /etc/php.d/20-sysvmsg.ini, /etc/php.d/20-sysvsem.ini, /etc/php.d/20-sysvshm.ini, /etc/php.d/20-tokenizer.ini, /etc/php.d/20-xml.ini, /etc/php.d/20-xmlwriter.ini, /etc/php.d/20-xsl.ini, /etc/php.d/30-pdo_sqlite.ini, /etc/php.d/30-wddx.ini, /etc/php.d/30-xmlreader.ini, /etc/php.d/40-zip.ini 
```

The content of `/etc/php.d` is
```
#> ls /etc/php.d/
20-bz2.ini       20-iconv.ini     20-shmop.ini      20-xsl.ini
20-calendar.ini  20-intl.ini      20-simplexml.ini  30-mysqli.ini
20-ctype.ini     20-json.ini      20-sockets.ini    30-pdo_mysql.ini
20-curl.ini      20-mbstring.ini  20-sqlite3.ini    30-pdo_pgsql.ini
20-dom.ini       20-mcrypt.ini    20-sysvmsg.ini    30-pdo_sqlite.ini
20-exif.ini      20-mysqlnd.ini   20-sysvsem.ini    30-wddx.ini
20-fileinfo.ini  20-pdo.ini       20-sysvshm.ini    30-xmlreader.ini
20-ftp.ini       20-pgsql.ini     20-tokenizer.ini  40-zip.ini
20-gd.ini        20-phar.ini      20-xml.ini
20-gettext.ini   20-posix.ini     20-xmlwriter.ini
```

Note that according to `phpinfo()`, `20-pgsql.ini` and `30-pdo_pgsql.ini` aren't parsed (even though they are in /etc/php.d).

Using `php artisan serve` instead of valet fixed the problem. It's probably a configuration problem on my part, but the fact that both files aren't loaded seems suspicious to me.

I'm using Fedora 25 and  php 7.0.16. Php and its modules the ones from Fedora official repositories.

**Comment by TheNodi** [comment]
Fedora 25 loads `/etc/php.ini` and `/etc/php.d` for both CLI and FPM (at least on my system). Does `phpinfo()` from CLI shows the same configuration of valets's?

If you just installed the php extention you might have to restart PHP-FPM processes to pickup changes (you can use `valet restart`).

**Comment by astlouisf** [comment]
> Fedora 25 loads /etc/php.ini and /etc/php.d for both CLI and FPM (at least on my system). Does phpinfo() from CLI shows the same configuration of valets's?

No, both files are parsed from CLI

> If you just installed the php extention you might have to restart PHP-FPM processes to pickup changes (you can use valet restart).

Thanks, that did the trick.

**Comment by TheNodi** [comment]
Great, I'm gonna close the issue then.
