### ISSUE TITLE
Lost ability to browse to other sites after installation

### ISSUE THREAD

**Issue by brothman01** [cpriego/valet-linux#375]
I installed this and it seems nice because I like valet a lot but the Linux where I installed valet can no longer browse to websites. I get the "unable to connect" error in browsers when I try to go to any page.

I can ping other sites so I know the connection is ok.

I curled google.com earlier and I got the error "Valet - Not Found" but now when I curl it says connection refused. Any idea how to make my internet work normally again?

**Comment by dharnarh** [comment]
@brothman01 This is primarily an issue related to DNSMasq, it sometimes goes off when your system goes into sleep or hibernation mode. I recommend you check the status of dnsmasq `service dnsmasq status`, if it shows it stopped, you can restart it by doing `service dnsmasq start`, it happens pretty frequently and I haven't found a permanent solution myself but I found a quite handy gnome extension to start the service easily. Link below.

[PHP Laravel Valet](https://extensions.gnome.org/extension/4985/php-laravel-valet/)

I hope this helps you out

**Comment by markovic-nikola** [comment]
Same issue here (Manjaro - Arch).
dnsmasq is already active.

**Comment by C4pt4inM** [comment]
I had same issue with Fedora 36, Manjaro 21, Mnajaro 22, Popos, Debian 11, Linux Mint, openSuse TW, and now in Ubuntu 22 ( yes I am a distro hoper )

Unable to install properly , pinging google.com after install gives ip `127.0.0.1` which is from `resolv.conf` and `/opt/valet-linux/resolv.conf` 

so I had to forefully install version 2.2.28. 

these are the files from this (2.2.28) version. please match and decide what is the issue.

/etc/resolv.conf
```
options edns0 trust-ad

search .
nameserver 127.0.0.1
```

/opt/valet-linux/dns-servers
```
nameserver 127.0.0.53
nameserver 192.168.1.1
```

/opt/valet-linux/resolv.conf
```
options edns0 trust-ad

search .
nameserver 127.0.0.1
```

I dont see any difference in these files but somehow, after installation of v2.2.28 , valet-linux works perfectly, without damaging your internet service.

**Comment by jmarcher** [comment]
New release, hope it solves this problem

**Comment by gmarineau** [comment]
Same for me on ubuntu 22.04, This works with 2.2.28 but not with the last release

**Comment by LemarinelNet** [comment]
Perhaps related, but updated my ubuntu from 21.10 to 22.04 few days ago. Since, everytime my laptop is suspended, or exactly everytime I switch on/off my wifi card, dnsmasq crashes (reading in journalctl file that "no server found in /opt/valet-linux/dns-servers, will try again". 
I have to restart dnsmasq manually (service dnsmasq restart), and everything come back...

**Comment by skino2019** [comment]
anyone got a work around for this... still not working for me, I've tried all sorts, tried all the temp fixes and i just cant get it working and i hate using Homestead on a windows partition :'(

**Comment by C4pt4inM** [comment]
> 

Did you try version 2.2.28?  It seems it works for other people as well.

**Comment by skino2019** [comment]
> > 
> 
> Did you try version 2.2.28? It seems it works for other people as well.

Sorry to sound stupid but how do you go about installing the older version ?

Always pulled the latest release lol.

**Comment by skino2019** [comment]
> 

i tried this and for the most part it works. apart from i need to use Valet Link in which ever repo im currently working on in order for the sites to be served.

Which in the grand scheme of things isnt too bad.

**Comment by krisscox** [comment]
Just spent the last 2 hours trying to get my computer able to access the web again, in it's current state this project appears to be broken. I realize that maintainers are being sought after, but some warning on the website might be prudent.

**Comment by skino2019** [comment]
> Just spent the last 2 hours trying to get my computer able to access the web again, in it's current state this project appears to be broken. I realize that maintainers are being sought after, but some warning on the website might be prudent.

Agreed, if your having trouble you can do what I did and install an older version to get it all running and working

**Comment by markovic-nikola** [comment]
I had the same issue again, after a big software/system update last night.

Keep in mind I'm no expert about this topic, I ran `systemctl status dnsmasq.service`
I was getting the following error:
![image](https://user-images.githubusercontent.com/16388545/188244344-5e7affb7-73d0-4bc0-9446-596e1d51adee.png)

As a workaround, I copied the content of `/opt/valet-linux/dns-servers` into `/etc/resolv.conf`
```
nameserver 127.0.0.1
nameserver 192.168.1.1
```

And I was able to access the web again, hopefully someone finds this solution useful.

**Comment by szmazhr** [comment]
had the same issue then I found `/etc/dnsmasq.d/valet` file has content `address=/./127.0.0.1`, I just set the domain to `.test` by running command `valet domain test`  the file's content get updated to `address=/.test/127.0.0.1`  and got everything working

hope it might help some of you

**Comment by skino2019** [comment]
> had the same issue then I found `/etc/dnsmasq.d/valet` file has content `address=/./127.0.0.1`, I just set the domain to `.test` by running command `valet domain test` the file's content get updated to `address=/.test/127.0.0.1` and got everything working
> 
> hope it might help some of you

did this work after reboot? mine kept reverting...

**Comment by szmazhr** [comment]
> > had the same issue then I found `/etc/dnsmasq.d/valet` file has content `address=/./127.0.0.1`, I just set the domain to `.test` by running command `valet domain test` the file's content get updated to `address=/.test/127.0.0.1` and got everything working
> > hope it might help some of you
> 
> did this work after reboot? mine kept reverting...

works for me

**Comment by abbasmashaddy72** [comment]
Same Issue

When I restart my network manager it works for few minutes and the again unable browse website

**Comment by deepaksp** [comment]
I have faced similar issue (maybe this is what causing this error) and found out dnsmasq was not working so i checked and chrome was taking port 53 which dnsmasq uses.
so i have to change dnsmasq port and it works perfectly fine after that.

**Comment by abbasmashaddy72** [comment]
Can Please Describe it how got it working with some screenshots and commands that you had used.

**Comment by skino2019** [comment]
> 2.2.28

Run this command to pull down the last known build that didn't suffer with this issue

composer global require cpriego/valet-linux:2.2.28

**Comment by szmazhr** [comment]
> Can Please Describe it how got it working with some screenshots and commands that you had used.

Again I had same issue in other PC, here what I did

first of all i remove valet-linux 
`composer global remove cpriego/valet-linux`

ping some websites to check if internet is working fine (you can do either in terminal or use browser to browse some websites)

then require it again and install
`composer global require cpriego/valet-linux`
`valet install`

set the domain to whatever you want I used `test`
`valet domain test`

check if correct path is set
`valet paths`

if your desired path is not listed there, `cd` into your directory and `park` it
`cd your/directory`
`valet park`

at this point everyting should be ok, run your tests.
some browser force `https://`, so you have to make sure if you are on correct protocol

**Comment by Adesin-fr** [comment]
Hi ,

I've released a new version with a (hopefully successfull) fix for this issue.

If you are willing to test, you have to upgrade your valet-linux install with the command 
```composer global update```

For those who might have installed a specific version like 2.2.28, you will have to reinstall it with ```composer global require cpriego/valet-linux```

If anything goes wrong, and uninstall doesn't work as expected, you might have to issue the following commands to get internet access back again : 
```
sudo rm /etc/resolv.conf
sudo systemctl restart systemd-resolved.service
sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```

Please give us any feedback, positive or negative, so we can make this project alive ;)

**Comment by skino2019** [comment]
Absolutely spot on. Just reinstalled on - Fedora and it worked instantly didn't even need a reboot (although i have since, and still fine)

**Comment by Adesin-fr** [comment]
> Absolutely spot on. Just reinstalled on - Fedora and it worked instantly didn't even need a reboot (although i have since, and still fine)

Thanks for your feedback. The issue was fired on my computer when I was putting the PC on sleep. Have you tried this ?

**Comment by skino2019** [comment]
> > Absolutely spot on. Just reinstalled on - Fedora and it worked instantly didn't even need a reboot (although i have since, and still fine)
> 
> Thanks for your feedback. The issue was fired on my computer when I was putting the PC on sleep. Have you tried this ?

Just tried it it now. No issues on wake.

did you use the full reinstall or just the global update?

**Comment by markovic-nikola** [comment]
Has anyone tested the changes on Arch based distro?
It doesn't seem to work on Manjaro.

**Comment by MordiSacks** [comment]
On MX Linux (Based on Debian 11) I had the same issue
fixed by editing `/etc/resolv.con`

```
nameserver 127.0.0.1
nameserver 1.1.1.1
```

**Comment by DmitrySkibitsky** [comment]
Headache from this every time.

![image](https://user-images.githubusercontent.com/20288556/230731460-b2a3d3e8-45bb-487b-aba8-f5d655554c68.png)

**Comment by khadegd** [comment]
I'm using Manjaro. I needed to add `nameserver 1.1.1.1` to `/etc/resolv.conf` every time I reboot. But, I don't want to do that.

The below is excerpt from https://github.com/cpriego/valet-linux/issues/396#issue-1465167792

What is the solution?
[AppArmor](https://apparmor.net/) was loaded with the new kernel, so I have two solutions:

1. Disable AppArmor
2. Edit the profile Dnsmasq in AppArmor.

In the second case, verify if `AppArmor` was loaded with `Dnsmasq` module by running `apparmor_status` command.

```sh
sudo systemctl stop dnsmasq.service
sudo vim /etc/apparmor.d/usr.sbin.dnsmasq
```
Add following lines before `}` which is located before End of file. Don't forget to save the file.
```
#valet linux
/opt/valet-linux/ r,
/opt/valet-linux/* r,
```
Run
```
sudo systemctl restart apparmor.service
sudo systemctl start dnsmasq.service
```

You should be able to browse the internet even after reload as well as valet should be working as expected.
