### ISSUE TITLE
Getting PHP service name causes infinite loop

### ISSUE THREAD

**Issue by codepuncher** [cpriego/valet-linux#377]
When running `valet install`, `valet secure` or `valet unsecure`, it causes an infinite loop on this line:

https://github.com/cpriego/valet-linux/blob/d132f709eb066941a673511d869a9902b214b17c/cli/Valet/PhpFpm.php#L236

It will hang on "Restarting php-fpm" because of this.

**Comment by Adesin-fr** [comment]
Which OS are you using ? 
I don't have this problem on Ubuntu 22.04 and latest valet

**Comment by codepuncher** [comment]
This is on Manjaro.
The php executables are not the same name on all distros which is why you do not experience this issue.
My PR https://github.com/cpriego/valet-linux/pull/378 fixes this.

**Comment by codepuncher** [comment]
Also, the current code to "get the PHP version" is completely broken, it **needs** refactoring so please consider merging my PR.
