### ISSUE TITLE
Bug: Valet use does not change the php version accordingly

### ISSUE THREAD

**Issue by FrancisMawn** [cpriego/valet-linux#380]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Ubuntu 20.04.4 LTS         | 8.1.8       | 2.2.32        |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Using the command `valet use 8.1` output the following:
```sh
Changing php-fpm version...
This does not affect php -v.
Stopping php8.1-fpm...
Disabling php8.1-fpm...
Php8.1-fpm has been disabled
Php8.1-fpm was already disabled
PHP Logs
Installing php config
Restarting php-fpm
Restarting php8.1-fpm...
Enabling php8.1-fpm...
Php8.1-fpm has been enabled
php-fpm version successfully changed! 🎉
```

But my app is still using version 8.0.20. 

When I run `valet status` I get this output:

```sh
Php8.1-fpm is stopped...
Nginx is running...
```

I'm not sure how I'm supposed to get Valet to use a different php version. It looks similar to #349 which was closed in June.

**What was supposed to happen?**
Valet should change the php version.

**What actually happened?**
The php version remains the same.

**Comment by Adesin-fr** [comment]
Hi,

Could you test with the last Valet version ? I've tested it on my computer and don't have issues

**Comment by FrancisMawn** [comment]
@Adesin-fr Looks like it's working now! 

One thing to note though... I switched to php8.0 to test it out (which worked) but when I tried switching back to php8.1, composer didn't like it:
```
> valet use 8.1
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.26.
```

I had to add this to my global composer file for it work properly:

```json
"config": {
    "platform-check": false
}
```

**Comment by Adesin-fr** [comment]
That's a problem I've saw also : 
When you run "valet use", it also performs a "update-alternative" so the command line also uses this version.
IMHO it's not a so-good idea, because of course if you lower your php version then valet stop working as the php version requirement is not met anymore !

I'm thinking of disabling this last part (update-alternative), or just put out a warning/tip to tell the user how to switch it.

**Comment by nathan-io** [comment]
I experienced this on 2.3.10.

After a `valet use 7.2`, I wasn't able to run any further valet commands successfully due to Composer errors.

The fix was `sudo update-alternatives --config php` and then selecting option 0 for PHP 8.3:

```
$ sudo update-alternatives --config php
There are 3 choices for the alternative php (providing /usr/bin/php).

  Selection    Path             Priority   Status
------------------------------------------------------------
  0            /usr/bin/php8.3   83        auto mode
  1            /usr/bin/php7.1   71        manual mode
* 2            /usr/bin/php7.2   72        manual mode
  3            /usr/bin/php8.3   83        manual mode
```
