### ISSUE TITLE
STILL Looking for new maintainers 

### ISSUE THREAD

**Issue by jmarcher** [cpriego/valet-linux#381]
Hi guys, 

I started the Valet-Linux journey back in 2016, its been a wonderful time and it still is but right now I find myself without time to invest on the development of Valet.

Please let me know if you are interested in being a maintainer of this repo and please write some references and explain why you want to be a part of this amazing project.

I hope to see this repo with new features in the future.

**Comment by Adesin-fr** [comment]
I'm willing to help, 
I've made a fork to implement the new "isolate" feature of valet 3.0...
Almost done, have to test with other OS than Ubuntu !

**Comment by frosit** [comment]
I would be open to help maintain this thing. My roots are in Magento land and I"m actually more of a Symfony guy myself but if you check my github, blog etc. you'll see I have quite the server experience and did a lot of work on security side. I'm occassionally hired by hosting companies to do testing and provide feedback. I'm pretty known with WSL tech as well and pretty familiair with all kinds of OS'es, languages and what not. Used to hire myself to help companies build internal development teams including processes, tooling (devops), standards, training and all that. I've been using this one and other variations of valet on various systems so I know my way around this stuff but It would be wise to get a laravel guru on it as well.

**Comment by bedus-creation** [comment]
I am interested.

**Comment by jmarcher** [comment]
Thanks all for showing interest I went with @Adesin-fr 
I can already see a new release so that means good news for Valet Linux!

**Comment by Adesin-fr** [comment]
Thanks for your support ;)
I'll do my best to keep this alive !

**Comment by skino2019** [comment]
> Hi guys,
> 
> I started the Valet-Linux journey back in 2016, its been a wonderful time and it still is but right now I find myself without time to invest on the development of Valet.
> 
> Please let me know if you are interested in being a maintainer of this repo and please write some references and explain why you want to be a part of this amazing project.
> 
> I hope to see this repo with new features in the future.



> Thanks for your support ;) I'll do my best to keep this alive !

If you need any testers give  me a shout and i can go over my credentials. 

I also work with Multiple Linux Distros (Ubuntu, Fedora & Manjaro are the 3 i mainly use for dev)

**Comment by Adesin-fr** [comment]
Sure ! 
I'm working on the "isolate" command which would allow to use multiple php version per folder.
If you have some time to test, I might ask you !

**Comment by Adesin-fr** [comment]
Here we go again...

I'm not using Linux anymore for my main workstation, and I'm clearly missing time to work on the project...

So, it would be fair to say I'm not a good maintainer for this project anymore !
