### ISSUE TITLE
Bug: Can't reach a host by its domain in a VPN network because of nameserver order

### ISSUE THREAD

**Issue by RafaelKr** [cpriego/valet-linux#384]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Linux Mint 21          | 8.0.22       | 2.2.32         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `Valet v2.2.32`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

(`valet fix` results in `Command "fix" is not defined.`)

**What is the problem?**
This problem started after updating valet-linux to 2.2.32

I have added an OpenVPN network via NetworkManager. When I want to reach a host inside this network via its domain (e.g. `host1.company.local`) the IP can't be resolved.

Although the nameserver of the VPN is correctly added as first line of `/opt/valet-linux/dns-servers`
```
nameserver 172.18.[AAA].1
nameserver 192.168.178.1
nameserver fd00::[TRUNCATED]
```

**What was supposed to happen?**
When running `nslookup host1.company.local` it should look like
```
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	host1.company.local
Address: 172.16.[XXX].58
```

**What actually happened?**
Running `nslookup host1.company.local` actually looks like
```
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find host1.company.local: NXDOMAIN
```

**How to reproduce this?**
I don't really know

**What is the solution?**
I could work around this by setting `strict-order` inside `/etc/dnsmasq.conf` as described here https://unix.stackexchange.com/a/106729/320221

**Sources**
> All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

I found the latest release (2.2.34) removed exactly that `strict-order` option: https://github.com/cpriego/valet-linux/commit/d132f709eb066941a673511d869a9902b214b17c

Edit: Interesting, that commit with the `strict-order` removal should be `2.2.34` and I'm on `2.2.32`. But `strict-order` is not included in my `/etc/dnsmasq.d/options`.

**Comment by CreepPork** [comment]
I also, do not understand why my change was reverted. There's no obvious explanation for the revert. If I want to access internal resources via DNS, then it's no longer possible.
