### ISSUE TITLE
Bug: Version detection

### ISSUE THREAD

**Issue by nuernbergerA** [cpriego/valet-linux#389]
`valet update` will always update due to version detection issues.

The latest git tags is "wrong" (missing 'v')
![image](https://user-images.githubusercontent.com/13331388/193738482-9821fb7d-9d92-4709-bc74-ceeb6723b570.png)

https://github.com/cpriego/valet-linux/blob/master/cli/valet.php#L21
is v2.2.32
latest tag = [2.2.35](https://github.com/cpriego/valet-linux/tree/2.2.35)

`Valet::onLatestVersion` could trim the 'v' from the tag for comparison to prevent wrong tagging issues

**Comment by nuernbergerA** [comment]
@Adesin-fr is there anything i can do to help?

**Comment by Adesin-fr** [comment]
Wow !
Shame on me !!
I'll fix it now !

**Comment by Adesin-fr** [comment]
@nuernbergerA Thanks for reporting,
I've made a new release, hope this fix this issue !
