### ISSUE TITLE
Valet not found in title. 404 - Not Found in page

### ISSUE THREAD

**Issue by jericopulvera** [cpriego/valet-linux#39]
did valet park. 
open test.dev
404 - Not Found

**Comment by TheNodi** [comment]
Where did you run `valet park` from? What's the content of that folder?

**Comment by jericopulvera** [comment]
from the Code directory where my projects live

**Comment by cpriego** [comment]
Please check Nginx and php-fpm are running with the help of `valet status`. Also please ping any address  with your chosen TLD (.dev is the default) like `foo.dev` to see if it resolves to `127.0.0.1`

**Comment by flick36** [comment]
The ping doesn't reslove to `127.0.0.1` in my case it resolves to `127.0.53.53` i'm on manjaro

**Comment by jericopulvera** [comment]
I removed my homestead hosts IP and it works.

**Comment by flick36** [comment]
In order for me to resolve to `127.0.0.1` i had to add:

```
[main]
plugins=keyfile
dns=dnsmasq
```
to my `/etc/NetworkManager/NetworkManager.conf` file, since it was empty (apparently valet didnt changue this?)
