### ISSUE TITLE
Bug: could not find driver

### ISSUE THREAD

**Issue by abbasmashaddy72** [cpriego/valet-linux#392]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Manjaro 21.3.7          | 8.111       | 2.2.36         |

**What is the problem?**
Illuminate\Database\QueryException
could not find driver

It is working fine when I am running artisan serve, but not working from valet.
It is also working fine with newly created Laravel project.

**Sources**
For More Details, Please Click on the Below Link.
[https://flareapp.io/share/67OKeja7#F68](https://flareapp.io/share/67OKeja7#F68)

@jmarcher @cpriego

**Comment by Adesin-fr** [comment]
Seems you're missing your database driver. 
Your php.ini could also miss the section for enabling sql drivers.
Perhaps your FPM version is different from your command line php version.
You should check with a simple phpinfo() run thru valet which php version you have.
