### ISSUE TITLE
Bug: Creating a proxy breaks all links

### ISSUE THREAD

**Issue by octoper** [cpriego/valet-linux#393]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 22.04.1 LTS          | 8.1.7     | 2.2.36        |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When I'm creating a Proxy every link I've made or trying to make points to the proxy.

**What was supposed to happen?**
It is supposed to just create a proxy and not break anything else.

**What actually happened?**
After a proxy has been created every link I've made before or trying to make it points to the proxy.

**How to reproduce this?**
- Create a Proxy
- Try to access the a previous link or create a new link

**Comment by zilahir** [comment]
Hi! 

I am too experiencing this issue! I am assuming this had not yet been released as the latest release dates back earlier than this one. Do you have any roadmap in mind, when this might gets released? 

Thank you in advance!
