### ISSUE TITLE
Suggestion: Support natively Laravel vite TLS

### ISSUE THREAD

**Issue by cbaconnier** [cpriego/valet-linux#395]
The current version (2.2.36) does not support natively [Laravel Vite](https://github.com/laravel/vite-plugin) TLS.

- **Laravel Vite** looks for the certificates in the folder `~/.config/valet/Certificates/` and this path is [hardcoded](https://github.com/laravel/vite-plugin/blob/f599658c5f5fb8bef2841855e318d0ce27be615f/src/index.ts#L501) 
- **Valet Linux** store the certificates in the folder `~/.valet/Certificates/` and this path is [hardcoded](https://github.com/cpriego/valet-linux/blob/55a59eacdc446f03ca5ec43546c329d95524c290/server.php#L7)

In order to make this works, I see two possibilities or two workaround:

1. **Valet Linux**  should support both paths
2. **Laravel Vite** should support both paths

Workaround: Make a symlink 😊

```bash
ln -s ~/.valet ~/.config/valet
```

Edit:  
An another workaround would be to use a bunch of [configuration](https://laravel.com/docs/9.x/vite#working-with-a-secure-development-server) on each projects

```js
import fs from 'fs'; 
 
const host = 'my-app.test'; 
 
export default defineConfig({
    // ...
    server: { 
        host, 
        hmr: { host }, 
        https: { 
            key: fs.readFileSync(`/path/to/${host}.key`), 
            cert: fs.readFileSync(`/path/to/${host}.crt`), 
        }, 
    }, 
});
```

**Comment by Adesin-fr** [comment]
> An another workaround would be to use a bunch of [configuration](https://laravel.com/docs/9.x/vite#working-with-a-secure-development-server) on each projects

For sure this workaround is very anoying, and I can't imagine this being a good solution ;)

The symlink could be an easy and quick (and dirty !) solution, but I'm not a big fan of symlinks : Changing valet's configuration should be easy enough. 

Just a warning about this : before changing it, on valet's upgrade , we must make sure that we will also copy the conf to the new location !

**Comment by ru44** [comment]
The workaround you suggested of creating a symbolic link could work, as it would make Laravel Vite find the certificates in the correct folder. However, this may not be the most elegant solution and could potentially cause issues if other applications depend on the ~/.config/valet/Certificates/ path.

A better solution would be to modify the Laravel Vite configuration to allow for both paths. You could submit a pull request to the Laravel Vite repository on GitHub to add this functionality, or you could modify your own local copy of the Laravel Vite code.

Another option, as you mentioned, would be to specify the path to the certificates in each project's configuration. This would allow you to use the correct path for each project, but would require more setup for each individual project.

**Comment by Vethavear** [comment]
That would be great. Workaround with symlink indeed works, many thanks for that. I swapped from iOS to Linux and this was last part I needed to make it work!
