### ISSUE TITLE
Bug: Valet x VPN (NordLayer)

### ISSUE THREAD

**Issue by devsquad-alvaro-meireles** [cpriego/valet-linux#399]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 22          | 8.1.2-1ubuntu2.9       | 2.2.36         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `2.2.36`

**What is the problem?**
Valet works successfully, but the company I work for uses a VPN service (NordLayer). When starting the VPN, I am able to continue using the site I opened before starting the VPN (via Valet), but any new site I open (Valet) I am faced with a DNS error in the browser:

![image](https://user-images.githubusercontent.com/98560934/205097020-a59bb281-aaf5-46e1-a6a0-aa6fa728cd16.png)

**What was supposed to happen?**
Some DNS conflicts with the VPN.

**How to reproduce this?**
1. Try to install some VPN such as NordLayer
2. Start the VPN
3. Try to open any website using Valet that was not opened before starting the VPN.

**Comment by Adesin-fr** [comment]
I'm not a VPN guru, but I wonder that the VPN is taking over the local DNS, then dnsmasq is never asked to resolve domains...

Could you first try to override a single local test domain in your /etc/hosts file :

**Comment by jmarcher** [comment]
I would disable VPN when using Valet, it definitely take over the local DNS records,
