### ISSUE TITLE
Intermittent fails in GitHub Actions

### ISSUE THREAD

**Issue by patrickomeara** [cpriego/valet-linux#404]
Hi all,

I'm trying to use this as a replacement for the built in artisan server (`php artisan serve`) in GitHub Actions, as I am having issues with the built in server falling over all the time while running dusk tests in CI. 

Nginx is a much more stable server so when I came across this project I thought I would give it a go in CI.

Very rarely it's fine and I get a green build.

However, most of the time I am getting a 502 bad gateway error with the following nginx error log, and many others like it:

```
Error: 2022/12/13 23:56:43 [error] 16305#16305: *41 recv() failed (104: Unknown error) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /task/edit/7b49be1d-a7e5-4854-bf48-c5aace45c5bc HTTP/1.1", upstream: "fastcgi://unix:/home/runner/.valet/valet.sock:", host: "web.test:8888"
```

I have added the following lines (under `increase buffers`) to the nginx conf to combat the header size being an issue:
```
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/home/runner/.valet/valet.sock;
        fastcgi_index /home/runner/.composer/vendor/cpriego/valet-linux/server.php;
        
        # increase buffers
        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
        fastcgi_busy_buffers_size 64k;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /home/runner/.composer/vendor/cpriego/valet-linux/server.php;
    }
```

Is there anything else I can try to get around this issue and have Valet Linux running on GitHub Actions?

Thanks in advance.

**Comment by Adesin-fr** [comment]
Hi,

That's not what valet was made for, but perhaps you have some good reason to do so  ?
How are you using it ? Do you need to serve multiple sites in the same tests CI suite ?

**Comment by patrickomeara** [comment]
Hi @Adesin-fr thanks so much for your reply.

The problem I am trying to solve is the SPA in dusk is making a lot of requests to the API, currently served by `artisan serve`. As the built in artisan server is single threaded it intermittently falls over giving the browser a `Failed to load resource: net::ERR_EMPTY_RESPONSE` error which breaks the test suite. If I re run the test suite several times I can get a full pass, there are no patterns to the server dying other than when several requests are made in a short time.

My first solution was to run nginx or apache in CI instead of the built in artisan server so that multiple requests could be handled, however this was a lot more difficult than it seemed. Then I stumbled across Valet Linux and thought my problems had been solved. I made some progress but hit a wall as above.

I understand this is not what valet was made for, just hoped someone may be able to shed some light on this.

This seems like a great port, well done.

**Comment by Adesin-fr** [comment]
I think you are taking your problem the wrong way, 
Artisan serve should not die neither block in any way...
Perhaps you have some issues in your code that leads to abnormal responses, or even not answering completely your request, hence the ERR_EMPTY_RESPONSE...

Since this issue is not in the "normal workflow" for valet, I'm closing this issue

**Comment by patrickomeara** [comment]
Thanks for your help @Adesin-fr. 

Much appreciated.
