### ISSUE TITLE
Bug: phpmyadmin errors on php 8.1

### ISSUE THREAD

**Issue by Lukicdev** [cpriego/valet-linux#405]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ubuntu 20.04.5 LTS          | 8.1.13       | 2.2.37         |

I updated php to 8.1 and my projects are working fine but I am getting this error in phpmyadmin: 

![image](https://user-images.githubusercontent.com/47175420/209355417-f39440b3-b4b5-4fd0-a661-5f75a4946d60.png)

I am getting a load of `http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated` deprications, something like this: 

![image](https://user-images.githubusercontent.com/47175420/209355519-0098205f-5232-4572-9e16-395dd002938f.png)

![image](https://user-images.githubusercontent.com/47175420/209355953-ff366b80-634e-4303-b9f9-07e06941cb63.png)

When I switch to php 7.4 phpmyadmin works fine.

**Comment by i74ifa** [comment]
update your phpmyadmin
