### ISSUE TITLE
Bug: Valet installation fails on Fedora 37

### ISSUE THREAD

**Issue by akoshodi** [cpriego/valet-linux#406]
| Fedora 37 (i3 spin) | PHP 8..1 | Valet v2.3.0 |
| ------------------------- | ----------- | ------------- |
| Ex: Manjaro 18.3          | 7.3.1       | 2.2.3         |

Running `valet install`  fails with the error "Unable to find a match: php8.1-fpm"  even though php-fpm is installed.

![valet-error](https://user-images.githubusercontent.com/769829/210965238-ff6946d4-9cac-4426-87ca-ed5cf1aeff75.png)

I installed fpm using `dnf install php-fpm`  which installed version php-fpm-8.1.13 while valet attempts to install it with `dnf install php8.1-fpm` which causes it to fail as indicated in the above image

**Comment by AhmedAnbar** [comment]
same here with php 7.4 installed fpm using `dnf install php74-fpm`

![error](https://user-images.githubusercontent.com/4220036/211154548-5d155cf1-c2d8-4ea1-95db-bd4ff5e7a97b.png)

**Comment by akoshodi** [comment]
Found a temporary solution inspired by https://github.com/cpriego/valet-linux/issues/402#issuecomment-1373959372
To get dnf to install the PHP modules the way Fedora expects i.e `dnf install php-fpm` , replace php{$this->version}-fpm with php-fpm in the install function in ~/.config/composer/vendor/cpriego/valet-linux/cli/Valet/PhpFpm.php as seen in the screenshot below

![valet-fix](https://user-images.githubusercontent.com/769829/211181201-d6e01e9b-ff5f-4ccd-9b67-d7a9d01d2fa7.png)

**Comment by m-hazem** [comment]
Faced same issue. I am using Fedora 37
i used @akoshodi workaround  comment to make it works

**Comment by faridsa** [comment]
@akoshodi fix works for me too, under Fedora 37.

**Comment by mc0de** [comment]
Dnf installation was broken by assuming this package manager names packages in same way as apt, I assume the author didn't even test it on redhat based distros https://github.com/cpriego/valet-linux/commit/6e9b617ba7404b16dba464c7f9089be8aff76d12

PhpFpm.php completely disregards Fedora's package naming, this file needs complete refactoring or "dirty" hacks.

https://github.com/cpriego/valet-linux/commit/6e9b617ba7404b16dba464c7f9089be8aff76d12#diff-d8e7b9c98bc6a045292f784be0d98860c26b463a1dd29f36256fed1d2ad62752

install() method should check against package manager class in use instead of blatantly asking version by Ubuntu naming scheme.

**Comment by akoshodi** [comment]
I also posted about this in Valet Linux Plus, and the issue has been now been fixed there  https://github.com/genesisweb/valet-linux-plus/issues/69

**Comment by mc0de** [comment]
> I also posted about this in Valet Linux Plus, and the issue has now been been fixed there  https://github.com/genesisweb/valet-linux-plus/issues/69

well, this is not the actual fix. i've reviewed that earlier. that would break all other installation processes for other distros. more like "it works on my machine" hack.

**Comment by mc0de** [comment]
PR has been merged, this can be closed for RedHat based distros.

**Comment by rabol** [comment]
Sorry to post on a closed issue, but I get the same error ``` Dnf was unable to install [php8.4-fpm]. ``` on fedora 43, but in my case the file ``` ~/.config/composer/vendor/cpriego/valet-linux/cli/Valet/PhpFpm.php ``` does not exists

A permanent fix or a note in the docs would be really nice
