### ISSUE TITLE
Bug: valet share not working

### ISSUE THREAD

**Issue by Jamesking56** [cpriego/valet-linux#407]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| PopOS 22.04         | 8.1.13       | 2.3.0         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `2.3.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Running `valet share` shows an error in ngrok:

```
ERROR:  unknown shorthand flag: 'o' in -ost-header=rewrite
```

**What was supposed to happen?**
The site generates an ngrok URL that I can share my local site with.

**What actually happened?**
ngrok shows this error and the screen carries on trying to ping `127.0.0.1 port 4040` and eventually errors out.

**How to reproduce this?**
Not entirely sure, I just run `valet share` and it happens.

**What is the solution?**
Not sure at the moment, I don't know what is causing ngrok to show this error.

**Comment by shamsPathan** [comment]
I just created a PR by fixing that issue.

https://github.com/cpriego/valet-linux/pull/408

**Comment by shamsPathan** [comment]
Fix PR
https://github.com/cpriego/valet-linux/pull/409

**Comment by ijasxyz** [comment]
ChatGPT !!

![image](https://user-images.githubusercontent.com/535233/213927596-1cbd056a-fea7-430e-a430-1c267140e1ef.png)

**Comment by jmarcher** [comment]
Fixed in 2.3.1
