### ISSUE TITLE
config port

### ISSUE THREAD

**Issue by julianraj** [cpriego/valet-linux#41]
I am using nginx in port 82.Currently valet loads up in port 80 which is used by apache.
How can I configure valet to use nginx's port?

**Comment by TheNodi** [comment]
There's no current way of changing port rather then manually change nginx configs.

This might be something useful to implement.

**Comment by cpriego** [comment]
Added in version [2.0.10](https://github.com/cpriego/valet-linux/releases/tag/v2.0.10)
