### ISSUE TITLE
Bug:  Problem with valet-linux proxy operation

### ISSUE THREAD

**Issue by frankl1n-dev** [cpriego/valet-linux#421]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Manjaro 18.3          | 7.3.1       | 2.2.3         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
after using valet link <domain-app> without any problem.
i decided to make a valet link <domain-2-app> then valet proxy <host> on this domain-2-app.
this creates a conf file in ~/.valet/Nginx
which redirects domain-app to domain-2-app
any attempt to go to domain-app fails
because the domain-2-app configuration file located in ~/valet/Nginx recovers all requests.

**What was supposed to happen?**
normally i think that despite the proxy that created the domain-2-app configuration file, domain-app should still continue to serve the right project.

**What actually happened?**
domain-2-app displays the domain-2-app project.
and the domain-app displays the domain-2-app project

**How to reproduce this?**
- create a laravel project
- then valet link laravel
- then create a vue project 
- then launch the vue project ex: npm run dev 
- then valet link vue
- and valet proxy vue <the host started by npm run dev>.
and voila

**What is the solution?**
generate a configuration file for each link with valet I think... 
really not much solution to propose dsl

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by jcuema** [comment]
I have the same problem.
Has anyone found a solution?
