### ISSUE TITLE
Bug: Issue with php8.2-fpm package name.

### ISSUE THREAD

**Issue by Meklad** [cpriego/valet-linux#425]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Arch rolling     | 8.2         | 2.2.7         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `2.3.7`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When try to run valet install an error with php8.2-fpm happens:
1- php fpm already installed on my machine.
2- an error happens while the installer try to pull the package from ache repositories, the write name for the package is "php-fpm", but the error tell me that "Pacman was unable to install [php8.2-fpm]." and thereis no package name on the arch repo with this name, and the right name is "php-fpm".

**What was supposed to happen?**
Becouse the php-fpm already installed end running and not disable by "systemctl", the valet installer supposed to find the php-fpm running.

**What actually happened?**
This error message return "In Pacman.php line 79: Pacman was unable to install [php8.2-fpm]."

**How to reproduce this?**
1- install php-fpm using packman "packman -S php-fpm"
2- run "valet install"
3- the output of the command fail when try to install php8.2-fpm:
"[php8.2-fpm] is not installed, installing it now via Pacman... 🍻"
"error: target not found: php8.2-fpm"
"In Pacman.php line 79:"
"Pacman was unable to install [php8.2-fpm]."
"install [--ignore-selinux]"

**What is the solution?**
The correct name for php fpm on arch repository in the base repositories or the aur-repositories "php-fpm" not "php8.2-fpm"

**Sources**
This is a screenshot to the command and the output:
![ArcoLinux_2023-10-29_14-23-17](https://github.com/cpriego/valet-linux/assets/20451697/f1cda5e1-ad88-49f6-8cc3-4f5f7ade5224)

**Comment by arcanna** [comment]
Confirming everything from @Meklad  above - reproduced on Manjaro/Arch

**Comment by gabrielmoura** [comment]
Unfortunately I'm facing the same problem.
I saw a pull-request for this problem.
Waiting to be merged.

**Comment by jmarcher** [comment]
The PR needs some work

**Comment by attisimon** [comment]
I have the same problem on openSUSE Tumbleweed. 
I have php-fpm (php8-fpm) installed, but when trying to run 'valet install' I get the 'Package not found: php8.2-fpm' problem.

**Comment by attisimon** [comment]
Still having this issue on openSUSE Tumbleweed, now with `Package not found: php8.3-fpm`

**Comment by attisimon** [comment]
For a moment I thought I will get it to work by setting the php version to 8, but it only works halfway. Although it sees `php8-fpm`,  I still need to get `valet install` to finish, but this command still looks for `php8.3-fpm`, instead of `php8-fpm`.

```
:~> valet use 8
Changing php-fpm version...
This does not affect php -v.
Stopping php-fpm...
Disabling php8.3-fpm...
Php-fpm has been disabled
Php-fpm was already disabled
Changing php version from 8.3 to 8... 
PHP Logs
Installing php config
Restarting php-fpm
Restarting php8-fpm...
Enabling php8-fpm...
Php-fpm has been enabled
php-fpm version successfully changed! 🎉
```
```
:~> valet install
Nginx was already enabled
Stopping nginx...
[php8.3-fpm] is not installed, installing it now via PackageKit... 🍻
Transaction:    Resolving
Status:         Waiting in queue
Status:         Starting
Status:         Querying
Package not found: php8.3-fpm
Transaction:    Resolving
Status:         Waiting in queue
Status:         Starting
Status:         Querying
Package not found: php8.3-fpm
Command failed: This tool could not find any available package.


In PackageKit.php line 79:
                                                  
  PackageKit was unable to install [php8.3-fpm].  
                                                  
install [--ignore-selinux]

```

I can link projects with `valet link` and these show up correctly in `valet links`, but the URL does not load up in the browser.

**Comment by attisimon** [comment]
Hello!

I have checked this again and I have the same issue on openSUSE Tumbleweed.
I have php-fpm installed already and it is version 8.3, but I think the naming convention is different and that's why it is not found.

![image](https://github.com/user-attachments/assets/a9947121-b3db-4a6c-a2e4-bdc3627a80c4)

**Comment by attisimon** [comment]
FYI: I also tried to set valet to use version 8, hoping to trick it somehow to use a different name, but I have the same error:

![image](https://github.com/user-attachments/assets/e3dcc875-f2e8-45fb-b633-c14d7889016e)
