### ISSUE TITLE
Bug: When connecting to Mullvad (VPN) all DNS requests fail

### ISSUE THREAD

**Issue by mbootsman** [cpriego/valet-linux#427]
**Basic info**
Ubuntu 23.10
PHP Version 8.2

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Manjaro 18.3          | 7.3.1       | 2.2.3         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After installing Valet Linux, and connecting to a VPN with Mullvad, DNS stops working. When disconnecting Mullvad all DNS works again.

**What was supposed to happen?**
DNS should still work when connecting to Mullvad

**How to reproduce this?**
1 Install Valet Linux
2 Install Mullvad VPN
3 Load a website in your browser
4 Connect with Mullvad VPN
5 Reload the site (this fails)
6 Disconnect Mulllvad VPN
7 Reload the site (this now succeeds)

When Valet Linux is removed, and the same steps (3-7) are performed, everything works normal.

**Comment by jmarcher** [comment]
There nothing we can do, using a VPN overwrites the local DNS values.
