### ISSUE TITLE
Bug: Can't using PHP 8.3

### ISSUE THREAD

**Issue by ludoguenet** [cpriego/valet-linux#428]
Distro : Linux Mint 21.2
PHP : 8.3 
Valet version : ValetLinux+ v1.6.7

Hello,

I'm actually using Valet Linux + and wanted to use it for PHP 8.3.

so I installed PHP 8.3 via `apt install php8.3-fpm`

Then I `composer globale update`

It used to work with PHP 8.2 but no longer does when I `valet use 8.3` this error message shows up : 

![reror](https://github.com/cpriego/valet-linux/assets/36139526/ab475bfe-45f8-4e5b-b516-aacabac097a4)

**Comment by jmarcher** [comment]
PHP 8.3 was just released, it may take a while or you could open a PR to add it, I'm not using Linux at the moment.

**Comment by atefBB** [comment]
I have an issue with php8.2, it prints this message:
` [php8.2-fpm] is not installed, installing it now via Apt... 🍻
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php8.2-fpm
E: Couldn't find any package by glob 'php8.2-fpm'
E: Couldn't find any package by regex 'php8.2-fpm'

Enabling php8.1-fpm...
Php8.1-fpm has been enabled
Changing version failed

In Apt.php line 86:
                                           
  Apt was unable to install [php8.2-fpm].`
  any ideas to solve it ?
