### ISSUE TITLE
Php-fpm is not running...

### ISSUE THREAD

**Issue by geradrum** [cpriego/valet-linux#43]
I'm getting this message

```
Php-fpm is not running...
Nginx is not running...
```

when  I run `valet status`.

`dnsmasq` is also not running, so valet is not working.

------------------

El problema que tengo en Antergos y Arch es el de este mismo issue, pero con las instrucciones que me proporcionaste para fedora (descomentando la linea `Defaults env_keep +="HOME"`) la instalación continua perfectamente, pero a la hora abrir cualquier dominio `.dev` Chrome me tira el error de ERR ICANN NAME COLLISION lo que quiere decir que los DNS no están funcionando, al igual que php-fpm y nginx no están corriendo. Lo que se me hace algo raro es que la primera vez que instalé Antergos de manera limpia la instalación de valet funcionó sin ningún problema y se ejecutó como debería ser, al reinstalar Antergos (igual limpio, eliminando y formateando particiones) comenzó este error. Instalé Arch para comprobar que no sucediera el mismo error, pero no, paso exactamente lo mismo, `php-fpm`, `nginx` y `dnsmasq` se instalan al ejecutar `valet install` via pacman pero no se ejecutan.

**Comment by cpriego** [comment]
@geradrum Hola Gerardo, hubo unas actualizaciones importantes corrigiendo unos errores de Arch. ¿podrías corroborar que funciona?

**Comment by geradrum** [comment]
@cpriego Justo estoy a punto de instalar Arch en una laptop nueva, una vez terminada la instalación procedo a instalar php, composer y la actualización y te confirmo.

**Comment by geradrum** [comment]
@cpriego He acabado de instalar valet, te dejo un screenshot:

<img width="551" alt="captura de pantalla 2017-04-22 a la s 22 05 38" src="https://cloud.githubusercontent.com/assets/9123134/25310331/004fd07c-27a8-11e7-99a0-07751359370f.png">

Antes de iniciar valet he agregado a los paths las carpetas correspondientes en otra sesión del terminal y después he ejecutado `valet start`.

Ahora no tuve el problema #33 pero persiste el mismo de `php-fpm` y `nginx`.

**Comment by cpriego** [comment]
@geradrum podrías por favor compartir el contenido de `systemctl status nginx` y `systemctl status php-fpm`? Porque realicé una instalación desde 0 de Arch y no me dió ninguno de esos errores con nginx o php-fpm.

**Comment by geradrum** [comment]
@cpriego 
<img width="488" alt="captura de pantalla 2017-04-23 a la s 12 32 45" src="https://cloud.githubusercontent.com/assets/9123134/25315823/1e00c5ee-2821-11e7-932a-15718677d3a7.png">

**Comment by geradrum** [comment]
@cpriego También quería comentarte sobre otro problema que tuve, ajeno a este issue y aun pasa en la instalación limpia y aprovechando que instalaste Arch ya que no estoy seguro si esto también pasa en alguna otra distribución es `valet unlink` no elimina los directorios. Te dejo un Screenshot

<img width="426" alt="captura de pantalla 2017-04-23 a la s 12 33 20" src="https://cloud.githubusercontent.com/assets/9123134/25315850/9be1bfcc-2821-11e7-9baa-3c54fb1b1981.png">

**Comment by cpriego** [comment]
Ah! ya vi! eso me pasó también pero es simple configuración.
```
sudo systemctl enable php-fpm.service
sudo systemctl enable nginx.service
```

Deja verifico lo de `unlink`

**Comment by geradrum** [comment]
@cpriego Sobre habilitar los servicios ya lo he intentado...

<img width="424" alt="captura de pantalla 2017-04-23 a la s 13 39 43" src="https://cloud.githubusercontent.com/assets/9123134/25316326/7fd078c4-282a-11e7-8efb-18355b7d1664.png">

La solución que tuve hace tiempo para esto es modificar los archivos de configuración, en este caso crear el grupo y añadirlo al archivo de configuración de php-fpm.

<img width="429" alt="captura de pantalla 2017-04-23 a la s 13 39 55" src="https://cloud.githubusercontent.com/assets/9123134/25316333/9d33847e-282a-11e7-9bf8-738e42761d2b.png">

**Comment by cpriego** [comment]
Duda, ¿en la salida de `groups` aparece tu nombre de usuario? Al parecer el problema radica en que al momento que se creó tu usuario no se creó el grupo del mismo nombre. Al no existir el grupo (que valet está tomando del usuario) causa errores. Voy a corregir eso no asumiendo que existe un grupo con el nombre del usuario.

Estoy creando una rama con la corrección y te pediré me ayudes haciendo pruebas.

**Comment by geradrum** [comment]
Eso iba a comentarte (sobre la falta del grupo), y si aparece mi nombre de usuario como grupo.
Y claro, con las pruebas las que gustes.

**Comment by cpriego** [comment]
Listo! Porfa corre:
```
composer global require "cpriego/valet-linux:dev-groups"
valet install
```
para obtener los últimos cambios y verificar si eso soluciona el problema

**Comment by geradrum** [comment]
<img width="429" alt="captura de pantalla 2017-04-23 a la s 14 43 01" src="https://cloud.githubusercontent.com/assets/9123134/25316853/363c394c-2833-11e7-8613-c3d705375d18.png">

**Comment by cpriego** [comment]
Acabo de actualizar la rama
```
composer global update
```

**Comment by geradrum** [comment]
@cpriego Perdón la demora, `php-fpm` ya esta corriendo...

<img width="425" alt="captura de pantalla 2017-04-23 a la s 16 30 03" src="https://cloud.githubusercontent.com/assets/9123134/25317643/2c45ce58-2842-11e7-8dfa-ce49d3fc0d67.png">

Pero nginx igual tiene problemas por el grupo.

<img width="428" alt="captura de pantalla 2017-04-23 a la s 16 31 03" src="https://cloud.githubusercontent.com/assets/9123134/25317646/448560dc-2842-11e7-8d17-abc67e559390.png">

**Comment by cpriego** [comment]
@geradrum porfa corre nginx con `sudo nginx` para ver el mensaje que arroja.

**Comment by geradrum** [comment]
@cpriego Es el mensaje de la imagen de arriba (la 2da), falla al obtener el nombre del grupo `getgram("gerardo") failed`...

**Comment by cpriego** [comment]
Ah! perfecto, ya encontré el problema. Si en la configuración de Nginx no se especifica el grupo, nginx asume que tu grupo es tu nombre de usuario (que aunque sí existe no te lo está detectando). Agregaré el parámetro de grupo en la configuración de nginx para solucionarlo. 

Mientras tanto, ¿podrías hacer lo siguiente?
1. Revisar el valor de `group` en tu archivo `/etc/php/php-fpm.d/valet.conf` y copiarlo.
2. Pegar ese valor de grupo **después** de tu nombre de usuario en `/etc/nginx/nginx.conf`
3. Guardar los cambios y `sudo nginx` o `valet restart`
4. Decirme si funciona.

**Comment by geradrum** [comment]
Si funciona, he lo que estado haciendo manualmente para hacer funcionar valet:

Agregar a `/etc/nginx/nginx.conf` en la primera linea el grupo

`user <usuario> <grupo>` -> `user gerardo users` y ahora ya tengo en `valet status`:

```
Php-fpm is running...
Nginx is running...
```

**Comment by geradrum** [comment]
@cpriego Bueno, quedó todo solucionado, muchas gracias.

**Comment by cpriego** [comment]
Gracias a ti @geradrum, fuiste de muchísima ayuda 😃. Ya puedes volver a la versión regular de **Valet** con el comando `composer global require "cpriego/valet-linux"`

**Comment by geradrum** [comment]
@cpriego Actualizado. Solo una cosa, ¿pudiste checar lo de `unlink`? conmigo no esta funcionando...

**Comment by cpriego** [comment]
@geradrum sí, lo que pasa es que `link` se debe usar **dentro** de la carpeta que quieres "linkear". El segundo parámetro es para darle un alias a la **url**.

## Caso de uso sin alias
| Directorio | Comando | URL |
|-------------|-------------|-----|
| `/home/user/alskdfja` | `cd /home/user/alskdfja && valet link` | alskdfja.dev |
| `/home/user/alskdfja` | `cd /home/user/alskdfja && valet unlink` | 404 |
| `/home/user/alskdfja` | `valet unlink alskdfja` | 404 |

## Caso de uso con alias
| Directorio | Comando | URL |
|-------------|-------------|-----|
| `/home/user/alskdfja` | `cd /home/user/alskdfja && valet link foo` | foo.dev |
| `/home/user/alskdfja` | `cd /home/user/alskdfja && valet unlink` |  404 |
| `/home/user/alskdfja` | `valet unlink foo` |  404 |

**Comment by geradrum** [comment]
Ah bien, perdón. Gracias.

Bueno, cualquier otra prueba que necesites con Arch me avisas.
