### ISSUE TITLE
Bug: Subdomains not working and redirecting to the same domain

### ISSUE THREAD

**Issue by CorbenPoot** [cpriego/valet-linux#438]
**Basic info**

I have this valet setup for three directories:

- mydomain.com
- pub.mydomain.com
- client.mydomain.com

Now when I visit pub.mydomain.com I actually get to see the content of mydomain.com even though the valet links command shows that the links are correct.

**Comment by CorbenPoot** [comment]
Here is the fix:

Go to ~/.config/composer/vendor/cpriego/valet-linux/server.php.

Look for the following part: 
```
if ($slug == $siteName || $slug == $domain) {
```

Now remove the $slug == $domain part.

**Comment by CorbenPoot** [comment]
Can someone fix this permanently perhaps?

**Comment by jmarcher** [comment]
You can always open a PR
