### ISSUE TITLE
Valet Share

### ISSUE THREAD

**Issue by zhiephie** [cpriego/valet-linux#45]
After run command `valet share`

`Forwarding                    http://181d8844.ngrok.io -> oms.dev:null`

why oms.dev:null ?

**Comment by cpriego** [comment]
Hi @zhiephie you probably don't have the `port` key set in the config file (I assume you upgraded via composer). You can fix it by running:

```
valet port 80
```

**Comment by zhiephie** [comment]
Ah, Thanks @cpriego. Now worked it.
