### ISSUE TITLE
valet doesn't work when valet restarting

### ISSUE THREAD

**Issue by engmmrj** [cpriego/valet-linux#46]
valet doesn't work when valet restarting , Shoud restart network-manager to working

valet restart && systemctl restrat network-manager

**Comment by TheNodi** [comment]
Can you share your system details? (OS, PHP, NetworkManager)

Are you on the latest Valet version?

**Comment by TheNodi** [comment]
Closed for inactivity.

Let us know if anyone else is experiencing this problem.

**Comment by engmmrj** [comment]
My os is Ubuntu and PHP 7
I used latest version

**Comment by TheNodi** [comment]
I guess there's been an error installing dnsmasq.

Try to remove dnsmasq and then run `valet install` again, see if it fixes the error.

**Comment by TheNodi** [comment]
Closed for inactivity.
