### ISSUE TITLE
Valet not pointing to 127.0.0.1

### ISSUE THREAD

**Issue by spacebuckwheat** [cpriego/valet-linux#48]
![screenshot from 2017-04-08 22-54-32](https://cloud.githubusercontent.com/assets/20656462/24829944/985e2e86-1cae-11e7-867c-b97fef1c9e54.png)

I've already added

```
[main]
plugins=keyfile
dns=dnsmasq
```
to my 

> /etc/NetworkManager/NetworkManager.conf

but still, it's pointing to 127.0.53.53

I'm using `Ubuntu 16.04`

**Comment by TheNodi** [comment]
127.0.53.53 is an alert meaning "the TLD you used has another master DNS", basically your computer is hitting a public DNS server instead of dnsmasq.

You can check which dns is responding using the command:
```
dig test.dev
```

Ironically that address still "points" to localhost so it should work anyway.

**Comment by spacebuckwheat** [comment]
![screenshot from 2017-04-12 10-14-54](https://cloud.githubusercontent.com/assets/20656462/24938318/fac8bc1e-1f68-11e7-830a-d48fe2ae3f39.png)

I'm not really good at network stuff. But as I've understand `test.dev` is using the `127.0.53.53` ip. Am I right?
And for some reason I still can't access my `local-directory.dev` site

![screenshot from 2017-04-12 10-22-55](https://cloud.githubusercontent.com/assets/20656462/24938483/0eed3e44-1f6a-11e7-96ce-7cb2ba400f22.png)

**Comment by fcoedno** [comment]
Same thing here, using Arch Linux

**Comment by fcoedno** [comment]
Problem solved for me. i added

`[main]
plugins=keyfile
dns=dnsmasq`

to my NetworkManager configuration file, then reinstalled nginx adn started the nginx.service again. In fact, there was an error starting the service, that's why i couldn't my local-directory.dev site.

@TheNodi check if you can manualy start the nginx.service, in arch this would be:

`systemctl start nginx.service`

**Comment by spacebuckwheat** [comment]
@fcoedno thanks for the tip. I'll try that when I get home.

**Comment by spacebuckwheat** [comment]
@fcoedno @TheNodi @cpriego 

i think I've found something that concludes ( base on my understanding ) why I can't access my `local-directory.dev` site.

![screenshot from 2017-04-13 19-51-27](https://cloud.githubusercontent.com/assets/20656462/25003611/d95088f8-2082-11e7-9062-aa811d228d0c.png)

tho I can't find out why nginx can't access port 80 when in fact nginx itself uses the port.
![screenshot from 2017-04-13 19-56-09](https://cloud.githubusercontent.com/assets/20656462/25003721/64af302a-2083-11e7-84f0-8c5c34f464c5.png)

**Comment by cpriego** [comment]
That last image was really helpful. For some reason nginx is running as www-data. With Valet, nginx should be run with **your** username, otherwise it is unable to access your files.

Could you please show the contents of your `/etc/nginx/nginx.conf` file?

**Comment by erwinsaget** [comment]
@spacebuckwheat I'm using 17.04 and ran into a similar issue. As a temporary workaround I added 
`nameserver 127.0.1.1`

to /etc/resolv.conf. 

Still looking for a permanent solution myself.

**Comment by spacebuckwheat** [comment]
@cpriego here my `nginx.conf` file settings

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
```

**Comment by spacebuckwheat** [comment]
@cpriego after updating my dnsmasq on my OS, `*.dev` sites are now pointing to `127.0.0.1` but wasn't  accessing the right directories when using `valet park` and thus using the `/var/www` directory in every `*.dev` site.

**Comment by cpriego** [comment]
Yes, you need to reinstall valet with `valet install` to correct the `/etc/nginx/nignx.conf` misconfiguration. The file was overwritten when you reinstalled nginx.

**Comment by spacebuckwheat** [comment]
wow.. works like magic. thanks @cpriego.

**Comment by abhaymaniyar** [comment]
I found a workaround.
Today is the second day I am doing something related to Laravel so please bare with me if this does not work. :)
Run command `ping anything.test` if it pings to 127.0.0.1 then we are good to go. 
Now just run `valet link` inside the directory you are willing to place your websites in and now you should be able to access your sites on browser using `any_project.test`.
