### ISSUE TITLE
404 - Not Found, yet everything else seems fine

### ISSUE THREAD

**Issue by num3thod** [cpriego/valet-linux#50]
Elementary Os Loki (Ubuntu 16.04)
PHP version 7.1 with all dependencies
`valet status` returns
`Php7.1-fpm is running...
Nginx is running...
`
Valet config.json is
`{
    "domain": "dev",
    "paths": [
        "/home/moose/projects"
    ]
}
`
Pinging any .dev domain returns 127.0.0.1

Just can't understand why I get 404 time I create a new Laravel project in /home/moose/projects

**Comment by TheNodi** [comment]
What is the directory name and what domain are you trying to visit?
Are you getting the Valet's 404 page on every .dev domain even if folder exists?
Have you tried the "link" command to see if it works?

**Comment by num3thod** [comment]
Was just about to post an update. FIXED.

To answer you questions:
- directory was /home/moose/projects
- domain was a laravel project in the projects directory
- was 404 no matter if the folder existed or not
- link command did not work either

The problem was in running `composer global require cpriego/valet-linux ` as sudo. KIDS, DO NOT RUN composer as sudo, especially cpriego/valet-linux. If you did, remove the package and then run require again (without sudo), valet install, etc.
