### ISSUE TITLE
Valet only supports the Mac operating system.

### ISSUE THREAD

**Issue by Gardezi1** [cpriego/valet-linux#62]
Hello guys, 

I have followed this tutorial https://github.com/cpriego/valet-linux/wiki/Getting-Started
but I'm still getting this error `Valet only supports the Mac operating system.` when running `valet install`. Please tell me what is going wrong. Thanks

**Comment by Rohan-Jalil** [comment]
Well just found what was going wrong. It's the same issue like this one https://github.com/cpriego/valet-linux/issues/30

Sorry for posing a duplicate :)

**Comment by Gardezi1** [comment]
Well just found what was going wrong. It's the same issue like this one #30

Sorry for posting a duplicate :)
