### ISSUE TITLE
404 status code for static files

### ISSUE THREAD

**Issue by woren951** [cpriego/valet-linux#65]
In my custom driver all my static files returned with 404 error. But if i open one of them at the same address with the status code of 404 i can read files but status code of this file be 404.
![2017-05-05 16-19-49](https://cloud.githubusercontent.com/assets/13134148/25747025/b0b3f258-31ae-11e7-9fa6-7859ef6890da.png)

**Comment by cpriego** [comment]
@woren951 I would need to see the custom driver and the output of `cat $HOME/.valet/Log/nginx-error.log`

**Comment by woren951** [comment]
@cpriego  my nginx error log is empty. And my custom driver class:
`<?php

class StarlightValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        // return true;
        return file_exists($sitePath.'/engine/index.php') &&
               file_exists($sitePath.'/artisan') &&
               file_exists($sitePath.'/engine/static.php');
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        header('access-control-allow-origin: *');

        if (strpos($uri, '/static/') !== 0) {
            return false;
        }

        if ($this->isActualFile($storagePath = rtrim($sitePath, '/') . $uri)) {
            return $storagePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        // return $sitePath.'/index.php';

        header('access-control-allow-origin: *');

        if (strpos($uri, '/static/') === 0) {
            return $sitePath.'/engine/static.php';
        }

        return $sitePath.'/engine/index.php';
    }
}
`

**Comment by cpriego** [comment]
@woren951 sorry for the delay. In your custom driver I see you're trying to invoke a method `$this->isActualFile()` but I don't see that method in the code you shared with us.

**Comment by woren951** [comment]
@cpriego I extend class [ValetDriver](https://github.com/cpriego/valet-linux/blob/master/cli/drivers/ValetDriver.php) and use [this method](https://github.com/cpriego/valet-linux/blob/master/cli/drivers/ValetDriver.php#L150) from the this class.

**Comment by TheNodi** [comment]
Driver looks correct to me. The only places where valet set return code to 404 it also exits the execution, so I don't get how this could happen. Try to run `valet install` in case there's an nginx misconfiguration that doesn't parse correctly the `X-Accel-Redirect` header.

Try to double check `engine/static.php`, I had a similar problem with a Yii2 project run using valet. It wasn't really getting the paths right (referencing somehow the valet's `server.php` file, never got to check it deeper), it can be happening here too.

Side Note: You can remove `header('access-control-allow-origin: *');` from `frontControllerPath()`, since `isStaticFile()` is always called so the header is already set.
