### ISSUE TITLE
[DomainException] Crouton

### ISSUE THREAD

**Issue by jonasedemalm** [cpriego/valet-linux#67]
Hello,

I am trying to get valet running on ubuntu using crouton.

But whenever i run **valet install** or almost any valet commands, it returns this;

```
[DomainException]                  
  Unable to determine service name.
```
I saw that someone else had the same problem in a closed issue. But i have everything up to date and still cant get past this

**Comment by cpriego** [comment]
Hi @jonasedemalm. I don't know which version of Ubuntu is available through crouton or what packages it includes (is not a typical ubuntu installation). Valet needs at least Ubuntu 14.04, with network manager installed (that´s not usually an issue) and either the `service` or `systemd` packages.

**Comment by jonasedemalm** [comment]
Thank you for your fast reply!
I understand crouton is a bit odd. Might have to ditch it for a full install..

However, if you have some more hints, heres some info.
Still no go after installing network manager

```
(xenial)jonas@localhost:~$ which systemd
/bin/systemd

(xenial)jonas@localhost:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

(xenial)jonas@localhost:~$ which networkmanager
(xenial)jonas@localhost:~$ which network-manager
(xenial)jonas@localhost:~$ sudo apt-get install network-manager
```

**Comment by cpriego** [comment]
I see you have Xenial installed and that's great news. Now I know se can do some troubleshooting.

Please try the following commands and paste the **full** output.
```
valet install
systemctl status nginx
systemctl status NetworkManager
systemctl status dnsmasq
```

**Comment by jonasedemalm** [comment]
Hm dont know if this is very helpful, but atleast its something

```
(xenial)jonas@localhost:~$ valet install
Enabling nginx.service ...

                                     
  [DomainException]                  
  Unable to determine service name.  
                                     

install [--ignore-selinux]

(xenial)jonas@localhost:~$ systemctl status nginx
Failed to get properties: Launch helper exited with unknown return code 1
(xenial)jonas@localhost:~$ systemctl status NetworkManager
Failed to get properties: Launch helper exited with unknown return code 1
(xenial)jonas@localhost:~$ systemctl status dnsmasq 
Failed to get properties: Launch helper exited with unknown return code 1

```

**Comment by cpriego** [comment]
Actually it is very helpful. As you can see systemd is, for some reason and I suspect the crouton custom build, not working. It can't get the service's properties and information.

**Comment by jonasedemalm** [comment]
So the most convenient solution would probably be to do a pure linux install then.

**Comment by jonasedemalm** [comment]
Ditched crouton for a fresh install of galliumos. Now valet works like a charm.

For anyone coming here in the future, go with gallium on your chromebooks! Its so much better than crouton in any way.

**Comment by stevethomas** [comment]
For what it's worth, I just installed this package on Debian Jessie (Raspbian actually), and got the same error. 

It seemed the only thing making valet install fail was the attempted use of network-manager which was not installed by default. Just install with `sudo apt-get install network-manager`. 

Also for whatever reason, *.dev resolved to 127.0.53.53 instead of 127.0.0.1, I had to add an entry in /etc/hosts.

**Comment by Sacro** [comment]
*.dev resolves to 127.0.53.53 to let you know that someone owns it and you should stop using it,  use a domain you own instead.

**Comment by jonasedemalm** [comment]
What? Is .dev even a tld? And who cares about the domain names used for local development environments?

**Comment by Sacro** [comment]
Yes, it is. Sorry, I just float around GitHub looking for that IP and trying to get people to correct their setups.

**Comment by zhonger** [comment]
@jonasedemalm I have meet the same trouble as you in Ubuntu 16.04.2 LTS, Just as @stevethomas  says, `sudo apt install network-manager` has worked. There is no need to do other things.

**Comment by stevethomas** [comment]
I just learned that .dev is a _proposed_ TLD (not cool Google!), although i'm not convinced that is related to this issue.

In laravel valet world, .dev is the standard TLD for locally hosted applications. I'm thinking the IP resolution problem is something to do with how dnsmasq / network manager works on debian, although I don't know enough about the topic to comment any further.

As I mentioned, editing /etc/hosts for locally hosted .dev domains seems an easy enough workaround if you only want to run a few sites in valet.

**Comment by cpriego** [comment]
@stevethomas did you reinstall valet after installing network-manager? The TLD issue was fixed for debian jessie many commits ago.

**Comment by stevethomas** [comment]
@cpriego yes I did, and the installation was successful. 

I am running the latest valet-linux, 2.0.20. I am running Rasbian (full) OS with all packages updated. 

Here is my installation script from a clean install:

````
#!/bin/bash

# disable config override prompts
export DEBIAN_FRONTEND=noninteractive

echo "installing Touchscreen Door Lock dependencies"

# unclutter: disables mouse in kiosk
# unattended-upgrades:  to patch OS automatically
# apt-transport-https, lsb-release, ca-certificates: support for PHP7 from custom repository
# libnss3-tools, jq, xsel: valet dependencies
echo "installing system dependencies..."
sudo apt-get install -y unclutter unattended-upgrades apt-transport-https lsb-release ca-certificates libnss3-tools jq xsel network-manager

# copy autostart config
echo "installing autostart configuration..."
cp bin/autostart /home/pi/.config/lxsession/LXDE-pi/autostart

# install prerequisite php7.0 packages for valet installer. Don't install base package php7.0 as it comes with apache
sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
sudo sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
sudo apt-get update
sudo apt-get install -y php7.0-cli php7.0-curl php7.0-sqlite3

# unclear whether `valet install` is installing all of these laravel dependencies
# apt-get install -y php7.0-cli php7.0-common php7.0-curl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache php7.0-readline php7.0-xml php7.0-zip

# composer
echo "installing composer..."
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo HOME=/root php composer-setup.php --install-dir=/usr/local/bin --filename=composer
php -r "unlink('composer-setup.php');"

# put composer in path
echo "installing .bash_profile..."
cp bin/.bash_profile ~/.bash_profile
. ~/.bash_profile

# install valet & configure valet (also installs some more PHP dependencies)
echo "installing valet..."
composer global require cpriego/valet-linux
valet install

# Install application
composer install --no-dev
cp .env.example .env
sed -i 's/APP_ENV=local/APP_ENV=production/' .env
sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
sed -i 's/APP_URL=http:\/\/localhost/APP_URL=http:\/\/project.dev/' .env
php artisan key:generate
touch database/database.sqlite
php artisan migrate --no-interaction
valet link
````

**Comment by thelambofgoat** [comment]
I experienced the same problem on Ubuntu 16.04

`[DomainException]                  
  Unable to determine service name.`

While running valet (and nginx).

Uninstalling and reinstalling of valet solved the issue, the problem (in my occasion) was that for some reason (maybe some error) php7.0-fpm wasn't installed when installing valet first time. Maybe this info will help someone)

**Comment by maheeshan** [comment]
can someone help me with this error
![image](https://user-images.githubusercontent.com/20036800/38455133-15446874-3a91-11e8-9c1c-db5c3c738365.png)
![image](https://user-images.githubusercontent.com/20036800/38455139-2237f0dc-3a91-11e8-8615-20bb466cee57.png)

**Comment by zhonger** [comment]
@maheeshan As I saw in your screenshots, I think that it's a software error like `E: Sub-process /usr/bin/dpkg returned an error cod (1)`.  Such error maybe because an old softwareversion conf don't work in the new software version. This problem can be solved by these steps:
```bash
sudo mv /var/lib/dpkg/info/nginx*
sudo apt -f install
```
If it cannot be worked, please do `journalctl -xe` to know the details of error and let's do a help.

**Comment by amadeann** [comment]
@maheeshan I had a similar issue and stopping apache2 first, as in this answer:
https://askubuntu.com/a/788367/494526
resolved it.
