### ISSUE TITLE
Fresh install and not able to valet

### ISSUE THREAD

**Issue by nkiermaier** [cpriego/valet-linux#68]
This page isn’t working

test.dev is currently unable to handle this request.
HTTP ERROR 500

**Comment by nkiermaier** [comment]
NM.  Got it working. 
 It could be more clearly stated where the valet log files are in the wiki.

**Comment by cpriego** [comment]
Added log files location in wiki.

**Comment by simplenotezy** [comment]
I ave same problem

**Comment by TheNodi** [comment]
Error 500 can be anything, you should check out the log files to see a more detailed explanation of the error.

See https://github.com/cpriego/valet-linux/wiki/FAQ#where-can-i-find-the-log-files

**Comment by sinyadal** [comment]
This page isn’t working

app.dev is currently unable to handle this request.
HTTP ERROR 500

This is my .valet/Log/nginx-error.log output

Thanks.

`2017/08/22 19:01:53 [error] 3738#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:02:27 [error] 3738#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "foo.dev"
2017/08/22 19:03:21 [error] 3738#0: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "localhost"
2017/08/22 19:04:43 [error] 3738#0: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:04:44 [error] 3738#0: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:04:58 [error] 3738#0: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:05:42 [error] 5874#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:05:43 [error] 5874#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:07:39 [error] 5874#0: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:07:52 [error] 5874#0: *8 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "phpmyadmin.dev"
2017/08/22 19:14:48 [error] 6513#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
2017/08/22 19:14:48 [error] 6513#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php:7
Stack trace:
#0 {main}
  thrown in /home/syd/.config/composer/vendor/cpriego/valet-linux/server.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/syd/.valet/valet.sock:", host: "app.dev"
`

**Comment by sinyadal** [comment]
Okay I fixed it, phpunit not installed.
