### ISSUE TITLE
DomainException on WSL

### ISSUE THREAD

**Issue by alshstf** [cpriego/valet-linux#69]
Got a DomainException-issue with latest valet on ubuntu 16.04 @ Windows subsystem for Linux:
```
alshstf@magicPC:~$ valet install
[sudo] password for alshstf:
sh: 1: /home/alshstf/.composer/vendor/cpriego/valet-linux/cli/scripts/update.sh: Permission denied
Enabling nginx.service ...


  [DomainException]
  Unable to determine service name.


install [--ignore-selinux]
```
dnsmasq, network-manager and nginx are installed and running

**Comment by ODDsama** [comment]
I have this problem too.

**Comment by TheNodi** [comment]
Are you using bash on Ubuntu on Windows 10, Valet is not supported on that environment. There're way to many differences from the original Ubuntu OS, especially on how the network works.
