### ISSUE TITLE
WordPress HTTP ERROR 500 Valet WordPress Arch Linux

### ISSUE THREAD

**Issue by etmartinkazoo** [cpriego/valet-linux#72]
For some reason, Laravel valet is working wonderfully on Arch Linux but WordPress via Valet goes through everything but breaks to a HTTP ERROR 500 after I put in the DB Name, Username, and Password...

Anyone else have a similar issue?

Thanks!

**Comment by etmartinkazoo** [comment]
Just as a clarification it breaks when I hit submit on the Setup Configuration File page of the WordPress install...

**Comment by TheNodi** [comment]
Sorry to be so late.

Have you checked out the nginx logs? You can find them in `~/.valet/Logs/` directory, they might give us more information.

**Comment by etmartinkazoo** [comment]
Found the answer. PHP7 and WordPress where conflicting as connect_mysql() is deprecated in PHP7. Needed to install mysqli PHP extension... Good learning experience. Could be useful information for others using Valet as a Local WordPress dev tool on Linux.

Thanks

**Comment by TheNodi** [comment]
Perfect, I'm going to close the issue since you've found the problem.
