### ISSUE TITLE
Custom URL rewrite configuration for specific project

### ISSUE THREAD

**Issue by aureliusm** [cpriego/valet-linux#74]
Hi,

how can I write website-specific nginx configuration for different projects? I need it for my older projects that had .htaccess file.

Thanks!

**Comment by tomicakorac** [comment]
You can write a custom valet driver. You can read more about that topic in the official documentation:

https://laravel.com/docs/5.4/valet#custom-valet-drivers

**Comment by aureliusm** [comment]
Thanks, it works perfectly!
