### ISSUE TITLE
How to make valet share give me a const domain?

### ISSUE THREAD

**Issue by Insua** [cpriego/valet-linux#75]
Coz I use some Pay and Oauth api,both of they need a auth domain,and they only let me to edit auth domain few times one month.
When I use valte share,it give me a random domain.So I want a const domain,How to define it?

**Comment by cpriego** [comment]
I'm afraid that's out of the scope of Valet. 

The ngrok free version (the one Valet uses) does not allow for this. You need to create an account and pay at least $5 a month ([see plans](https://ngrok.com/product#pricing)) to be able to define a constant domain and then it is just plain easier to use ngrok directly.

The other options is to use a dynamic dns service and open the ports in your computer and router. (I know, it is a pain).

If you really want the option I'd recommend getting the basic plan and then it is as simple as running this command:
```
./ngrok http -host-header=rewrite "your-app.dev" -hostname=custom.domain.dev
```

**Comment by Insua** [comment]
thx a lot
