### ISSUE TITLE
Global function conflicts with local Laravel install

### ISSUE THREAD

**Issue by krzystof** [cpriego/valet-linux#76]
Hi,
I ran into this issue:
```
PHP Fatal error:  Cannot redeclare info() (previously declared in 
/home/xxx/xxx/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:517) in
 /home/xxx/.config/composer/vendor/cpriego/valet-linux/cli/includes/helpers.php on line 20 
```
Am I doing something wrong with the autoloader? Or should the global functions be replaced by a namespaced class? I'm happy to do it if needed.

**Comment by TheNodi** [comment]
Is it showing in the browser when you navigate to the local laravel installation?
Can you please add information about OS and PHP Version?

**Comment by krzystof** [comment]
No, that was on the Command line. I tried to run `phpstan`, installed globally as well, and this shows up.
I am on Ubuntu Mate 17.04 - php7.1

**Comment by TheNodi** [comment]
My guess is that phpstan is loading the local composer autoloader to analyze your code and this is conflicting with the laravel framework. Valet and Laravel are not ment to be installed togheter and usually there's no reason to have a composer local valet or a globally installed Laravel. 

Going back to the error, is it the only command that gives that?

A few possible solutions/workarounds:
- Install phpstan locally, so it shouldn't load the global composer autoloader.
- Try to use [consolidation/cgr](https://github.com/consolidation/cgr) to install your global packages, so when you're running phpstan it doesn't load valet.

**Comment by krzystof** [comment]
So far, yes that's the only command. I went for the local packages. Thanks for your help

**Comment by duongductrong** [comment]
Can you tell me this issue was solved?

I use OS ubuntu 20.04, php 7.3
