### ISSUE TITLE
Error on run command valet install

### ISSUE THREAD

**Issue by marcelohfilho** [cpriego/valet-linux#77]
PHP Fatal error:  Cannot declare class Facade, because the name is already in use in /home/user/.config/composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 3
PHP Stack trace:
PHP   1. {main}() /home/user/.config/composer/vendor/cpriego/valet-linux/cli/valet.php:0
PHP   2. require() /home/user/.config/composer/vendor/cpriego/valet-linux/cli/valet.php:10
PHP   3. ComposerAutoloaderInit0b2dbe3729bd3fa99906a36570ae8788::getLoader() /home/user/.config/composer/vendor/autoload.php:7
PHP   4. composerRequire0b2dbe3729bd3fa99906a36570ae8788() /home/user/.config/composer/vendor/composer/autoload_real.php:56

I'm using elementaryOS (based on Ubuntu), valet version is 2.2.3 and PHP is 7.1

**Comment by marcelohfilho** [comment]
On PHP 7.0 (7.0.20-2) the error message changes

PHP Fatal error:  Cannot declare class CommandLine, because the name is already in use in /home/user/.config/composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 43
PHP Stack trace:
PHP   1. {main}() /home/user/.config/composer/vendor/cpriego/valet-linux/cli/valet.php:0
PHP   2. require() /home/user/.config/composer/vendor/cpriego/valet-linux/cli/valet.php:10
PHP   3. ComposerAutoloaderInit0b2dbe3729bd3fa99906a36570ae8788::getLoader() /home/user/.config/composer/vendor/autoload.php:7
PHP   4. composerRequire0b2dbe3729bd3fa99906a36570ae8788() /home/user/.config/composer/vendor/composer/autoload_real.php:56

**Comment by TheNodi** [comment]
You need to remove `jmarcher/valet-linux`, the two packages aren't compatible.
```
composer global remove jmarcher/valet-linux
```
