### ISSUE TITLE
nginx.conf has error when group name has a space

### ISSUE THREAD

**Issue by richardfleming** [cpriego/valet-linux#78]
In the ``nginx.conf`` file, when a group name has a space, the user variable will be passed too many parameters.

This is fixed by opening the file manually and placing quotes around the group name.

Could the default behaviour be to have quotes around the values?

**Comment by cpriego** [comment]
Hi @richardfleming, my first question would be, how did you manage to create a group name (or username) with a white space for that is not standard behavior and not recommended at all?

Seriously, best case scenario, you face easy-to-fix issues just like this one. Worst case, you brick your installation.

Sorry for the unasked advice. This fix is quite simple (it only requires adding four quotes to a file) and has (apparently) no consequences.

Does anyone have a good reason to not do it?

**Comment by richardfleming** [comment]
Yeah, it is backward... but it's what happens when your Linux workstation is joined to a Windows domain via sssd and realmd and you're logged in as said Windows domain user.

Needless to say, my group is _domain users_.

Cheers,

Rich

**Comment by cpriego** [comment]
Don't worry, the file won't be changing soon. I was authentically curious about this situation as I have never seen it before. Apparently quoting the username and group affects nothing negatively so I'll be able to make the change.
