### ISSUE TITLE
Updates to wiki page "Requirements: Arch"

### ISSUE THREAD

**Issue by ShikherVerma** [cpriego/valet-linux#88]
I recently setup valet-linux on my arch linux installation. The [Arch wiki page](https://github.com/cpriego/valet-linux/wiki/Requirements:%20Arch) of this repo is not up to date. And I don't have permission to edit it. So leaving updates here:

## Requirements for Arch and derivatives

 - OS dependencies: `pacman -S nss jq xsel networkmanager`
 - PHP : `pacman -S php` ( need >= 5.6 ; check version with `php -v` after installing)
 - PHP Extension: `php-mcrypt` ( `php` package comes with a lot of compiled in modules. Including `cli, curl, mbstring, xml, zip`. If you don't find an extension, it could be that it is now a part of the `php` package. To check compiled in modules run `php -m`)
 - Optional PHP Packages: [php-sqlite](https://wiki.archlinux.org/index.php/PHP#Sqlite), [mysql/mariadb](https://wiki.archlinux.org/index.php/PHP#MySQL.2FMariaDB), [php-pgsql](https://wiki.archlinux.org/index.php/PHP#PostgreSQL)
- Install [composer](https://wiki.archlinux.org/index.php/PHP#Composer), php package manager

**Comment by cpriego** [comment]
Thanks @ShikherVerma, I have included this in the [official page](https://cpriego.github.io/valet-linux/) in the [requirements section](https://cpriego.github.io/valet-linux/requirements)
