### ISSUE TITLE
Disable automatic valet start on boot

### ISSUE THREAD

**Issue by ShikherVerma** [cpriego/valet-linux#89]
I have other projects that bind to port 80. Its frustrating to `valet stop` every time I boot.
How do I disable valet from starting automatically on boot ? / How is valet started automatically on boot?
I want to manually run `valet start` when I work on my laravel projects.

**Comment by TheNodi** [comment]
Valet is using nginx as a web server, so if you need to disable valet on boot just disable nginx service. 
You can also disable php-fpm unless you're using it anywhere else, `valet start` will start it as well.

**Comment by ShikherVerma** [comment]
Yeah I could disable all the things individually but I wanted a cleaner solution. Do you know how valet is starting at boot? maybe `valet install` puts `valet start` in some startup script? I like fixing the root cause of a problem rather than masking the symptoms.

**Comment by TheNodi** [comment]
I'm quite sure Valet is not setting anything to run on startup. 
On some OS (Ubuntu if I remember correctly is one of them) nginx is enabled on boot by default after installing it using apt-get.
On Fedora for example nginx is not enable by default, so I need to type `valet start` every time I reboot my computer (or I must enable it manually, but I like this way).

If you disable it on boot you should be good to go.

**Comment by ShikherVerma** [comment]
Oh I see. Okay.

**Comment by cpriego** [comment]
@ShikherVerma you have two options here.

1. Disable the nginx service from startup with `sudo systemctl disable nginx.service`
2. Change the valet port with the `valet port <Port Number>` command.

**Comment by ShikherVerma** [comment]
@cpriego thanks. I'll most probably change valet's port number.

**Comment by grove86nickson** [comment]
@cpriego thanks from me too...
