### ISSUE TITLE
valet share 502 error

### ISSUE THREAD

**Issue by jankulma** [cpriego/valet-linux#93]
I'm getting 502 bad gateway when I try to display the publicly accessible URL.

![screenshot from 2017-08-28 00-18-33](https://user-images.githubusercontent.com/18684426/29754499-ad5d2354-8b86-11e7-8771-0e6b3246cbaf.png)
![screenshot from 2017-08-28 00-18-37](https://user-images.githubusercontent.com/18684426/29754502-b028456e-8b86-11e7-8624-c21fa68b9159.png)

I tried to run `valet unsecure blog && valet share` but it didn't work neither.

I'm just exploring features of Valet and this one seems really exciting - any help to get this running would be really appreciated.

**Comment by cpriego** [comment]
It seems ngrok is not able to resolve the blog.dev address in your computer. Can you access that address with within browser?

**Comment by jankulma** [comment]
Yes I can

**Comment by cpriego** [comment]
Hmmm, it's an odd behavior I'm not able to replicate

 - Do you have a firewall enabled?
 - Could you share your distro and valet version please?
 - Could you share the output your $HOME/.valet/Log/ files?

**Comment by jankulma** [comment]
Ubuntu GNOME 17.04, Valet v2.0.20, no output in logs.

**Comment by TheNodi** [comment]
Try to execute:
```
valet port 80
```

Then try again `valet share`.

**Comment by jankulma** [comment]
@TheNodi I'm already on port 80.

**Comment by TheNodi** [comment]
Sorry I was busy and gave a quick reply without explanation.

I think ngrok is not picking up the correct port number, since it's trying to connect to `127.0.0.1:0`. It might be missing in `config.json` and everything should default to 80. Unfortunatly the share command behaves a bit differently.

Can you give me the output of the following command?
```
cat "$HOME/.valet/config.json" | jq -r ".port"
```

And the content of `~/.valet/config.json`?

**Comment by jankulma** [comment]
@TheNodi 

```
$ cat "$HOME/.valet/config.json" | jq -r ".port"
80
```
```
$ cat ~/.valet/config.json
{
    "domain": "dev",
    "paths": [
        "/home/jan/fun"
    ],
    "port": "80"
}
```
`/home/jan/fun` that's where valet is parked, `/home/jan/fun/blog` is where I run `valet share`

**Comment by TheNodi** [comment]
While ngrok is running, can you screenshot http://127.0.0.1:4040/status page? I'm interested in `Configuration > command_line` and `Configuration > command_line (http)` sections.

Ngrok looks misconfigured, but I can't replicate the issue either.

**Comment by jankulma** [comment]
![screenshot from 2017-08-29 20-05-55](https://user-images.githubusercontent.com/18684426/29836452-97d4b9e6-8cf5-11e7-9ca7-d2374d8a0684.png)

**Comment by TheNodi** [comment]
Does it still says `dial tcp 127.0.0.1:0` even if in the status tab it's written `blog.dev:80`?

It's resolving `blog.dev` to `127.0.0.1` correctly, but it looks to be loosing the port information somewhere (going from 80 to 0). Might it be an ngrok bug?

To be sure, can you give me the output of:
```
dig blog.dev
```

**Comment by jankulma** [comment]
@TheNodi 
![screenshot from 2017-08-29 20-33-22](https://user-images.githubusercontent.com/18684426/29837763-66add858-8cf9-11e7-9f90-eebcae88aaa0.png)

**Comment by TheNodi** [comment]
Everything looks fine on the valet side of things. 

Try to execute ngrok manually:
```
~/.config/composer/vendor/cpriego/valet-linux/bin/ngrok http "blog.dev:80" -host-header=rewrite
```

**Comment by jankulma** [comment]
@TheNodi works!

..and when I type "blog.dev:0" the error occurs again!

Why is valet missing the port setting?

**Comment by TheNodi** [comment]
It should not, in the screenshot from ngrok's status page it had the port setting (`Addr blog.dev:80`), while in the original screenshot it was missing (`Forwarding http://***.ngrok.io -> blog.dev:`, note the final `:`, should be `:80`). 

In theory `valet port 80` should had fixed it because I think port field was missing from the config, but I don't understand why ngrok has the port correctly setup and still doesn't work.

If you run `valet share`, does it still shows `blog.dev:` instead of `blog.dev:80` in the terminal?

**Comment by cpriego** [comment]
@jankulma Did you install **[all of the required dependencies](https://cpriego.github.io/valet-linux/requirements#ubuntu)**? Because it seems you are missing the **`jq`** program which Valet depends on. @TheNodi

**Comment by TheNodi** [comment]
@cpriego He should have jq, looking at https://github.com/cpriego/valet-linux/issues/93#issuecomment-325742701 , there're no errors.

**Comment by jankulma** [comment]
@cpriego I had not jq installed until @TheNodi asked to run cat "$HOME/.valet/config.json" | jq -r ".port"

Thank you guys!

**Comment by TheNodi** [comment]
That's a great news!

@cpriego Given jq is being used in sub-terminal (https://github.com/cpriego/valet-linux/blob/master/valet#L58) and giving no visible error to the user, should we add a check for it?

**Comment by cpriego** [comment]
Indeed @TheNodi, we definitely need a check for OS dependent packages: jq, xsel, nss-tools and, if possible network-manager)
