### ISSUE TITLE
Dynamic subdomains not working

### ISSUE THREAD

**Issue by LucasLeandro1204** [cpriego/valet-linux#95]
Acording to https://github.com/laravel/valet/issues/124, subdomains point to the project automatically, but I'm getting 404 when trying to acess by {subdomain}.project-domain.dev

Version: v2.0.20.

Thanks.

**Comment by TheNodi** [comment]
We have never implemented https://github.com/laravel/valet/pull/318 which means subdomains are not supported yet unless you link them manually. 

If anyone wants to send a PR with those changes it would be highly appreciated, else I'll do it as soon as I end my current work on Valet.

**Comment by cpriego** [comment]
@LucasLeandro1204 I have implemented the feature. Will be available in the next release.
