### ISSUE TITLE
Is Debian 9 supported?

### ISSUE THREAD

**Issue by jimmerioles** [cpriego/valet-linux#97]
Hi i'm planning on upgrading to Debian 9, just want to know if somebody tested this in Debian 9 and if it works out of the box? or are there any needed tweaks? hiccups?

**Comment by cpriego** [comment]
Valet Linux works with debian 8.9, so, in theory should work with debian 9. The easiest way to test it might be using a VM. I've been very short on time lately so I probably won't be able to try it soon.

**Comment by Ljz7** [comment]
The v2.0.21 was ok some weeks ago with Debian 9.1. But after a composer update and v2.0.22, the `valet install` command does not work anymore.
